// Generated by scripts/media/films-manifest.mjs (scripts/media/build_films.sh). Do not edit.
export type FilmSource = { mp4: string; webm: string; mp4Bytes: number; webmBytes: number }
export type FilmMedia = { duration: number; width: number; height: number; audio: boolean; sources: Record<'1080' | '720', FilmSource>; preview: { mp4: string; webm: string }; hero?: { mp4: string; webm: string; mobileMp4: string; mobileWebm: string }; poster: { src: string; small: string; jpg: string } }
export const filmMedia: Record<string, FilmMedia> = {
 "reel-2026": {
  "duration": 112.45,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/reel-2026-720.mp4?v=4de9ec8522",
    "webm": "/video/films/reel-2026-720.webm?v=4de9ec8522",
    "mp4Bytes": 27483610,
    "webmBytes": 19941945
   },
   "1080": {
    "mp4": "/video/films/reel-2026-1080.mp4?v=4de9ec8522",
    "webm": "/video/films/reel-2026-1080.webm?v=4de9ec8522",
    "mp4Bytes": 48515043,
    "webmBytes": 38484005
   }
  },
  "preview": {
   "mp4": "/video/films/reel-2026-preview.mp4?v=4de9ec8522",
   "webm": "/video/films/reel-2026-preview.webm?v=4de9ec8522"
  },
  "hero": {
   "mp4": "/video/films/reel-2026-hero.mp4?v=4de9ec8522",
   "webm": "/video/films/reel-2026-hero.webm?v=4de9ec8522",
   "mobileMp4": "/video/films/reel-2026-hero-720.mp4?v=4de9ec8522",
   "mobileWebm": "/video/films/reel-2026-hero-720.webm?v=4de9ec8522"
  },
  "poster": {
   "src": "/video/films/reel-2026-poster-1920.avif?v=4de9ec8522",
   "small": "/video/films/reel-2026-poster-960.avif?v=4de9ec8522",
   "jpg": "/video/films/reel-2026-poster.jpg?v=4de9ec8522"
  }
 },
 "the-house": {
  "duration": 146.56,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/the-house-720.mp4?v=111f31b3b3",
    "webm": "/video/films/the-house-720.webm?v=111f31b3b3",
    "mp4Bytes": 29939583,
    "webmBytes": 25939062
   },
   "1080": {
    "mp4": "/video/films/the-house-1080.mp4?v=111f31b3b3",
    "webm": "/video/films/the-house-1080.webm?v=111f31b3b3",
    "mp4Bytes": 48589809,
    "webmBytes": 50191534
   }
  },
  "preview": {
   "mp4": "/video/films/the-house-preview.mp4?v=111f31b3b3",
   "webm": "/video/films/the-house-preview.webm?v=111f31b3b3"
  },
  "poster": {
   "src": "/video/films/the-house-poster-1920.avif?v=111f31b3b3",
   "small": "/video/films/the-house-poster-960.avif?v=111f31b3b3",
   "jpg": "/video/films/the-house-poster.jpg?v=111f31b3b3"
  }
 },
 "villa-paris": {
  "duration": 116.87,
  "width": 1920,
  "height": 1086,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/villa-paris-720.mp4?v=4d71b0a6c3",
    "webm": "/video/films/villa-paris-720.webm?v=4d71b0a6c3",
    "mp4Bytes": 24314544,
    "webmBytes": 20258627
   },
   "1080": {
    "mp4": "/video/films/villa-paris-1080.mp4?v=4d71b0a6c3",
    "webm": "/video/films/villa-paris-1080.webm?v=4d71b0a6c3",
    "mp4Bytes": 47659436,
    "webmBytes": 39323191
   }
  },
  "preview": {
   "mp4": "/video/films/villa-paris-preview.mp4?v=4d71b0a6c3",
   "webm": "/video/films/villa-paris-preview.webm?v=4d71b0a6c3"
  },
  "poster": {
   "src": "/video/films/villa-paris-poster-1920.avif?v=4d71b0a6c3",
   "small": "/video/films/villa-paris-poster-960.avif?v=4d71b0a6c3",
   "jpg": "/video/films/villa-paris-poster.jpg?v=4d71b0a6c3"
  }
 },
 "la-resina-six": {
  "duration": 59.97,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/la-resina-six-720.mp4?v=de4a5751bf",
    "webm": "/video/films/la-resina-six-720.webm?v=de4a5751bf",
    "mp4Bytes": 9409481,
    "webmBytes": 8405812
   },
   "1080": {
    "mp4": "/video/films/la-resina-six-1080.mp4?v=de4a5751bf",
    "webm": "/video/films/la-resina-six-1080.webm?v=de4a5751bf",
    "mp4Bytes": 20424056,
    "webmBytes": 16579826
   }
  },
  "preview": {
   "mp4": "/video/films/la-resina-six-preview.mp4?v=de4a5751bf",
   "webm": "/video/films/la-resina-six-preview.webm?v=de4a5751bf"
  },
  "poster": {
   "src": "/video/films/la-resina-six-poster-1920.avif?v=de4a5751bf",
   "small": "/video/films/la-resina-six-poster-960.avif?v=de4a5751bf",
   "jpg": "/video/films/la-resina-six-poster.jpg?v=de4a5751bf"
  }
 },
 "villa-las-fuentes": {
  "duration": 100.8,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/villa-las-fuentes-720.mp4?v=219e4ee843",
    "webm": "/video/films/villa-las-fuentes-720.webm?v=219e4ee843",
    "mp4Bytes": 21274581,
    "webmBytes": 17606695
   },
   "1080": {
    "mp4": "/video/films/villa-las-fuentes-1080.mp4?v=219e4ee843",
    "webm": "/video/films/villa-las-fuentes-1080.webm?v=219e4ee843",
    "mp4Bytes": 43913332,
    "webmBytes": 34115245
   }
  },
  "preview": {
   "mp4": "/video/films/villa-las-fuentes-preview.mp4?v=219e4ee843",
   "webm": "/video/films/villa-las-fuentes-preview.webm?v=219e4ee843"
  },
  "poster": {
   "src": "/video/films/villa-las-fuentes-poster-1920.avif?v=219e4ee843",
   "small": "/video/films/villa-las-fuentes-poster-960.avif?v=219e4ee843",
   "jpg": "/video/films/villa-las-fuentes-poster.jpg?v=219e4ee843"
  }
 },
 "villa-soal": {
  "duration": 61.5,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/villa-soal-720.mp4?v=ec0a859401",
    "webm": "/video/films/villa-soal-720.webm?v=ec0a859401",
    "mp4Bytes": 13478609,
    "webmBytes": 10801058
   },
   "1080": {
    "mp4": "/video/films/villa-soal-1080.mp4?v=ec0a859401",
    "webm": "/video/films/villa-soal-1080.webm?v=ec0a859401",
    "mp4Bytes": 26468598,
    "webmBytes": 20871876
   }
  },
  "preview": {
   "mp4": "/video/films/villa-soal-preview.mp4?v=ec0a859401",
   "webm": "/video/films/villa-soal-preview.webm?v=ec0a859401"
  },
  "poster": {
   "src": "/video/films/villa-soal-poster-1920.avif?v=ec0a859401",
   "small": "/video/films/villa-soal-poster-960.avif?v=ec0a859401",
   "jpg": "/video/films/villa-soal-poster.jpg?v=ec0a859401"
  }
 },
 "villa-pareja": {
  "duration": 104.53,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/villa-pareja-720.mp4?v=e1dba0ad78",
    "webm": "/video/films/villa-pareja-720.webm?v=e1dba0ad78",
    "mp4Bytes": 23394538,
    "webmBytes": 18087251
   },
   "1080": {
    "mp4": "/video/films/villa-pareja-1080.mp4?v=e1dba0ad78",
    "webm": "/video/films/villa-pareja-1080.webm?v=e1dba0ad78",
    "mp4Bytes": 45576346,
    "webmBytes": 35050611
   }
  },
  "preview": {
   "mp4": "/video/films/villa-pareja-preview.mp4?v=e1dba0ad78",
   "webm": "/video/films/villa-pareja-preview.webm?v=e1dba0ad78"
  },
  "poster": {
   "src": "/video/films/villa-pareja-poster-1920.avif?v=e1dba0ad78",
   "small": "/video/films/villa-pareja-poster-960.avif?v=e1dba0ad78",
   "jpg": "/video/films/villa-pareja-poster.jpg?v=e1dba0ad78"
  }
 }
}
