// Generated by scripts/media/films-manifest.mjs (scripts/media/build_films.sh). Do not edit.
export type FilmSource = { mp4: string; webm: string; mp4Bytes: number; webmBytes: number }
export type FilmMedia = { duration: number; width: number; height: number; audio: boolean; sources: Record<'1080' | '720', FilmSource>; preview: { mp4: string; webm: string }; hero?: { mp4: string; webm: string; mobileMp4: string; mobileWebm: string }; poster: { src: string; small: string; jpg: string } }
export const filmMedia: Record<string, FilmMedia> = {
 "reel-2026": {
  "duration": 112.45,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/reel-2026-720.mp4?v=f7eeb8b0c1",
    "webm": "/video/films/reel-2026-720.webm?v=f7eeb8b0c1",
    "mp4Bytes": 27483610,
    "webmBytes": 19941945
   },
   "1080": {
    "mp4": "/video/films/reel-2026-1080.mp4?v=f7eeb8b0c1",
    "webm": "/video/films/reel-2026-1080.webm?v=f7eeb8b0c1",
    "mp4Bytes": 54325442,
    "webmBytes": 38484005
   }
  },
  "preview": {
   "mp4": "/video/films/reel-2026-preview.mp4?v=f7eeb8b0c1",
   "webm": "/video/films/reel-2026-preview.webm?v=f7eeb8b0c1"
  },
  "hero": {
   "mp4": "/video/films/reel-2026-hero.mp4?v=f7eeb8b0c1",
   "webm": "/video/films/reel-2026-hero.webm?v=f7eeb8b0c1",
   "mobileMp4": "/video/films/reel-2026-hero-720.mp4?v=f7eeb8b0c1",
   "mobileWebm": "/video/films/reel-2026-hero-720.webm?v=f7eeb8b0c1"
  },
  "poster": {
   "src": "/video/films/reel-2026-poster-1920.avif?v=f7eeb8b0c1",
   "small": "/video/films/reel-2026-poster-960.avif?v=f7eeb8b0c1",
   "jpg": "/video/films/reel-2026-poster.jpg?v=f7eeb8b0c1"
  }
 },
 "the-house": {
  "duration": 146.56,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/the-house-720.mp4?v=4925071a22",
    "webm": "/video/films/the-house-720.webm?v=4925071a22",
    "mp4Bytes": 29778171,
    "webmBytes": 25948655
   },
   "1080": {
    "mp4": "/video/films/the-house-1080.mp4?v=4925071a22",
    "webm": "/video/films/the-house-1080.webm?v=4925071a22",
    "mp4Bytes": 61636391,
    "webmBytes": 50198095
   }
  },
  "preview": {
   "mp4": "/video/films/the-house-preview.mp4?v=4925071a22",
   "webm": "/video/films/the-house-preview.webm?v=4925071a22"
  },
  "poster": {
   "src": "/video/films/the-house-poster-1920.avif?v=4925071a22",
   "small": "/video/films/the-house-poster-960.avif?v=4925071a22",
   "jpg": "/video/films/the-house-poster.jpg?v=4925071a22"
  }
 },
 "villa-paris": {
  "duration": 116.87,
  "width": 1920,
  "height": 1086,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/villa-paris-720.mp4?v=44aa016692",
    "webm": "/video/films/villa-paris-720.webm?v=44aa016692",
    "mp4Bytes": 23962978,
    "webmBytes": 20256729
   },
   "1080": {
    "mp4": "/video/films/villa-paris-1080.mp4?v=44aa016692",
    "webm": "/video/films/villa-paris-1080.webm?v=44aa016692",
    "mp4Bytes": 47136107,
    "webmBytes": 39313178
   }
  },
  "preview": {
   "mp4": "/video/films/villa-paris-preview.mp4?v=44aa016692",
   "webm": "/video/films/villa-paris-preview.webm?v=44aa016692"
  },
  "poster": {
   "src": "/video/films/villa-paris-poster-1920.avif?v=44aa016692",
   "small": "/video/films/villa-paris-poster-960.avif?v=44aa016692",
   "jpg": "/video/films/villa-paris-poster.jpg?v=44aa016692"
  }
 },
 "la-resina-six": {
  "duration": 59.97,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/la-resina-six-720.mp4?v=a9d77f94c0",
    "webm": "/video/films/la-resina-six-720.webm?v=a9d77f94c0",
    "mp4Bytes": 9358549,
    "webmBytes": 8415597
   },
   "1080": {
    "mp4": "/video/films/la-resina-six-1080.mp4?v=a9d77f94c0",
    "webm": "/video/films/la-resina-six-1080.webm?v=a9d77f94c0",
    "mp4Bytes": 20258645,
    "webmBytes": 16223213
   }
  },
  "preview": {
   "mp4": "/video/films/la-resina-six-preview.mp4?v=a9d77f94c0",
   "webm": "/video/films/la-resina-six-preview.webm?v=a9d77f94c0"
  },
  "poster": {
   "src": "/video/films/la-resina-six-poster-1920.avif?v=a9d77f94c0",
   "small": "/video/films/la-resina-six-poster-960.avif?v=a9d77f94c0",
   "jpg": "/video/films/la-resina-six-poster.jpg?v=a9d77f94c0"
  }
 },
 "villa-soal": {
  "duration": 61.5,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/villa-soal-720.mp4?v=54d98cef3d",
    "webm": "/video/films/villa-soal-720.webm?v=54d98cef3d",
    "mp4Bytes": 13378529,
    "webmBytes": 10799595
   },
   "1080": {
    "mp4": "/video/films/villa-soal-1080.mp4?v=54d98cef3d",
    "webm": "/video/films/villa-soal-1080.webm?v=54d98cef3d",
    "mp4Bytes": 26349850,
    "webmBytes": 20870876
   }
  },
  "preview": {
   "mp4": "/video/films/villa-soal-preview.mp4?v=54d98cef3d",
   "webm": "/video/films/villa-soal-preview.webm?v=54d98cef3d"
  },
  "poster": {
   "src": "/video/films/villa-soal-poster-1920.avif?v=54d98cef3d",
   "small": "/video/films/villa-soal-poster-960.avif?v=54d98cef3d",
   "jpg": "/video/films/villa-soal-poster.jpg?v=54d98cef3d"
  }
 },
 "villa-pareja": {
  "duration": 104.53,
  "width": 1920,
  "height": 1080,
  "audio": true,
  "sources": {
   "720": {
    "mp4": "/video/films/villa-pareja-720.mp4?v=3178054364",
    "webm": "/video/films/villa-pareja-720.webm?v=3178054364",
    "mp4Bytes": 23249395,
    "webmBytes": 18068841
   },
   "1080": {
    "mp4": "/video/films/villa-pareja-1080.mp4?v=3178054364",
    "webm": "/video/films/villa-pareja-1080.webm?v=3178054364",
    "mp4Bytes": 45231878,
    "webmBytes": 35016673
   }
  },
  "preview": {
   "mp4": "/video/films/villa-pareja-preview.mp4?v=3178054364",
   "webm": "/video/films/villa-pareja-preview.webm?v=3178054364"
  },
  "poster": {
   "src": "/video/films/villa-pareja-poster-1920.avif?v=3178054364",
   "small": "/video/films/villa-pareja-poster-960.avif?v=3178054364",
   "jpg": "/video/films/villa-pareja-poster.jpg?v=3178054364"
  }
 }
}
