// Generated by scripts/media/replace_home_reel.sh from the Home reel master.
export const homeReel = {
  "desktop": "/video/home-reel.mp4?v=0e63762e8e39",
  "mobile": "/video/home-reel-720.mp4?v=0e63762e8e39",
  "poster": "/video/home-reel-poster.avif?v=0e63762e8e39",
  "mobilePoster": "/video/home-reel-720-poster.avif?v=0e63762e8e39"
} as const
