// Generated by scripts/media/replace_home_reel.sh from REEL Galvan Arquitectos Octubre 2026 - 40seg.mp4. Shared by Home and Projects.
export const homeReel = {
  "desktop": "/video/home-reel.mp4?v=45374750bdc6",
  "mobile": "/video/home-reel-720.mp4?v=45374750bdc6",
  "poster": "/video/home-reel-poster.avif?v=45374750bdc6",
  "mobilePoster": "/video/home-reel-720-poster.avif?v=45374750bdc6"
} as const
