// Generated by scripts/og/generate.py: Open Graph image per page path. Do not edit by hand.
export const ogImages: Record<string, { image: string; alt: string }> = {
 "/": {
  "image": "/og/home.jpg",
  "alt": "Spaces for living well."
 },
 "/journal": {
  "image": "/og/journal.jpg",
  "alt": "Questions before your project."
 },
 "/es/guias": {
  "image": "/og/es--guias.jpg",
  "alt": "Preguntas antes de tu proyecto."
 },
 "/examples/villa-renovation": {
  "image": "/og/examples--villa-renovation.jpg",
  "alt": "COMPLETE VILLA RENOVATION"
 },
 "/examples/interior-design": {
  "image": "/og/examples--interior-design.jpg",
  "alt": "INTERIOR DESIGN"
 },
 "/examples/landscape-design": {
  "image": "/og/examples--landscape-design.jpg",
  "alt": "LANDSCAPE DESIGN"
 },
 "/villa-architecture": {
  "image": "/og/villa-architecture.jpg",
  "alt": "New-build villas on the Costa del Sol"
 },
 "/villa-renovation": {
  "image": "/og/villa-renovation.jpg",
  "alt": "Luxury villa renovations on the Costa del Sol"
 },
 "/interior-design": {
  "image": "/og/interior-design.jpg",
  "alt": "Interior design for villas on the Costa del Sol"
 },
 "/landscape-design": {
  "image": "/og/landscape-design.jpg",
  "alt": "Landscape design for villas on the Costa del Sol"
 },
 "/es/arquitectura-villas": {
  "image": "/og/es--arquitectura-villas.jpg",
  "alt": "Villas de nueva construcción en la Costa del Sol"
 },
 "/es/reformas-villas": {
  "image": "/og/es--reformas-villas.jpg",
  "alt": "Reformas integrales de villas en la Costa del Sol"
 },
 "/es/interiorismo": {
  "image": "/og/es--interiorismo.jpg",
  "alt": "Interiorismo para villas en la Costa del Sol"
 },
 "/es/paisajismo": {
  "image": "/og/es--paisajismo.jpg",
  "alt": "Paisajismo para villas en la Costa del Sol"
 },
 "/villa-architecture/marbella": {
  "image": "/og/villa-architecture--marbella.jpg",
  "alt": "New-build villas in Marbella"
 },
 "/villa-architecture/benahavis": {
  "image": "/og/villa-architecture--benahavis.jpg",
  "alt": "New-build villas in Benahavís"
 },
 "/villa-architecture/los-monteros": {
  "image": "/og/villa-architecture--los-monteros.jpg",
  "alt": "New-build villas in Los Monteros"
 },
 "/villa-architecture/nueva-andalucia": {
  "image": "/og/villa-architecture--nueva-andalucia.jpg",
  "alt": "New-build villas in Nueva Andalucía"
 },
 "/villa-architecture/estepona": {
  "image": "/og/villa-architecture--estepona.jpg",
  "alt": "New-build villas in Estepona"
 },
 "/villa-architecture/guadalmina": {
  "image": "/og/villa-architecture--guadalmina.jpg",
  "alt": "New-build villas in Guadalmina"
 },
 "/villa-architecture/la-zagaleta": {
  "image": "/og/villa-architecture--la-zagaleta.jpg",
  "alt": "New-build villas in La Zagaleta"
 },
 "/villa-architecture/golden-mile": {
  "image": "/og/villa-architecture--golden-mile.jpg",
  "alt": "New-build villas on the Golden Mile"
 },
 "/villa-architecture/rio-real": {
  "image": "/og/villa-architecture--rio-real.jpg",
  "alt": "New-build villas in Río Real"
 },
 "/villa-architecture/elviria": {
  "image": "/og/villa-architecture--elviria.jpg",
  "alt": "New-build villas in Elviria"
 },
 "/villa-renovation/marbella": {
  "image": "/og/villa-renovation--marbella.jpg",
  "alt": "Luxury villa renovations in Marbella"
 },
 "/villa-renovation/benahavis": {
  "image": "/og/villa-renovation--benahavis.jpg",
  "alt": "Luxury villa renovations in Benahavís"
 },
 "/villa-renovation/los-monteros": {
  "image": "/og/villa-renovation--los-monteros.jpg",
  "alt": "Luxury villa renovations in Los Monteros"
 },
 "/villa-renovation/nueva-andalucia": {
  "image": "/og/villa-renovation--nueva-andalucia.jpg",
  "alt": "Luxury villa renovations in Nueva Andalucía"
 },
 "/villa-renovation/estepona": {
  "image": "/og/villa-renovation--estepona.jpg",
  "alt": "Luxury villa renovations in Estepona"
 },
 "/villa-renovation/guadalmina": {
  "image": "/og/villa-renovation--guadalmina.jpg",
  "alt": "Luxury villa renovations in Guadalmina"
 },
 "/villa-renovation/la-zagaleta": {
  "image": "/og/villa-renovation--la-zagaleta.jpg",
  "alt": "Luxury villa renovations in La Zagaleta"
 },
 "/villa-renovation/golden-mile": {
  "image": "/og/villa-renovation--golden-mile.jpg",
  "alt": "Luxury villa renovations on the Golden Mile"
 },
 "/villa-renovation/rio-real": {
  "image": "/og/villa-renovation--rio-real.jpg",
  "alt": "Luxury villa renovations in Río Real"
 },
 "/villa-renovation/elviria": {
  "image": "/og/villa-renovation--elviria.jpg",
  "alt": "Luxury villa renovations in Elviria"
 },
 "/interior-design/marbella": {
  "image": "/og/interior-design--marbella.jpg",
  "alt": "Interior design for villas in Marbella"
 },
 "/interior-design/benahavis": {
  "image": "/og/interior-design--benahavis.jpg",
  "alt": "Interior design for villas in Benahavís"
 },
 "/interior-design/los-monteros": {
  "image": "/og/interior-design--los-monteros.jpg",
  "alt": "Interior design for villas in Los Monteros"
 },
 "/interior-design/nueva-andalucia": {
  "image": "/og/interior-design--nueva-andalucia.jpg",
  "alt": "Interior design for villas in Nueva Andalucía"
 },
 "/interior-design/estepona": {
  "image": "/og/interior-design--estepona.jpg",
  "alt": "Interior design for villas in Estepona"
 },
 "/interior-design/guadalmina": {
  "image": "/og/interior-design--guadalmina.jpg",
  "alt": "Interior design for villas in Guadalmina"
 },
 "/interior-design/la-zagaleta": {
  "image": "/og/interior-design--la-zagaleta.jpg",
  "alt": "Interior design for villas in La Zagaleta"
 },
 "/interior-design/golden-mile": {
  "image": "/og/interior-design--golden-mile.jpg",
  "alt": "Interior design for villas on the Golden Mile"
 },
 "/interior-design/rio-real": {
  "image": "/og/interior-design--rio-real.jpg",
  "alt": "Interior design for villas in Río Real"
 },
 "/interior-design/elviria": {
  "image": "/og/interior-design--elviria.jpg",
  "alt": "Interior design for villas in Elviria"
 },
 "/landscape-design/marbella": {
  "image": "/og/landscape-design--marbella.jpg",
  "alt": "Landscape design for villas in Marbella"
 },
 "/landscape-design/benahavis": {
  "image": "/og/landscape-design--benahavis.jpg",
  "alt": "Landscape design for villas in Benahavís"
 },
 "/landscape-design/los-monteros": {
  "image": "/og/landscape-design--los-monteros.jpg",
  "alt": "Landscape design for villas in Los Monteros"
 },
 "/landscape-design/nueva-andalucia": {
  "image": "/og/landscape-design--nueva-andalucia.jpg",
  "alt": "Landscape design for villas in Nueva Andalucía"
 },
 "/landscape-design/estepona": {
  "image": "/og/landscape-design--estepona.jpg",
  "alt": "Landscape design for villas in Estepona"
 },
 "/landscape-design/guadalmina": {
  "image": "/og/landscape-design--guadalmina.jpg",
  "alt": "Landscape design for villas in Guadalmina"
 },
 "/landscape-design/la-zagaleta": {
  "image": "/og/landscape-design--la-zagaleta.jpg",
  "alt": "Landscape design for villas in La Zagaleta"
 },
 "/landscape-design/golden-mile": {
  "image": "/og/landscape-design--golden-mile.jpg",
  "alt": "Landscape design for villas on the Golden Mile"
 },
 "/landscape-design/rio-real": {
  "image": "/og/landscape-design--rio-real.jpg",
  "alt": "Landscape design for villas in Río Real"
 },
 "/landscape-design/elviria": {
  "image": "/og/landscape-design--elviria.jpg",
  "alt": "Landscape design for villas in Elviria"
 },
 "/es/arquitectura-villas/marbella": {
  "image": "/og/es--arquitectura-villas--marbella.jpg",
  "alt": "Villas de nueva construcción en Marbella"
 },
 "/es/arquitectura-villas/benahavis": {
  "image": "/og/es--arquitectura-villas--benahavis.jpg",
  "alt": "Villas de nueva construcción en Benahavís"
 },
 "/es/arquitectura-villas/los-monteros": {
  "image": "/og/es--arquitectura-villas--los-monteros.jpg",
  "alt": "Villas de nueva construcción en Los Monteros"
 },
 "/es/arquitectura-villas/nueva-andalucia": {
  "image": "/og/es--arquitectura-villas--nueva-andalucia.jpg",
  "alt": "Villas de nueva construcción en Nueva Andalucía"
 },
 "/es/arquitectura-villas/estepona": {
  "image": "/og/es--arquitectura-villas--estepona.jpg",
  "alt": "Villas de nueva construcción en Estepona"
 },
 "/es/arquitectura-villas/guadalmina": {
  "image": "/og/es--arquitectura-villas--guadalmina.jpg",
  "alt": "Villas de nueva construcción en Guadalmina"
 },
 "/es/arquitectura-villas/la-zagaleta": {
  "image": "/og/es--arquitectura-villas--la-zagaleta.jpg",
  "alt": "Villas de nueva construcción en La Zagaleta"
 },
 "/es/arquitectura-villas/milla-de-oro": {
  "image": "/og/es--arquitectura-villas--milla-de-oro.jpg",
  "alt": "Villas de nueva construcción en la Milla de Oro"
 },
 "/es/arquitectura-villas/rio-real": {
  "image": "/og/es--arquitectura-villas--rio-real.jpg",
  "alt": "Villas de nueva construcción en Río Real"
 },
 "/es/arquitectura-villas/elviria": {
  "image": "/og/es--arquitectura-villas--elviria.jpg",
  "alt": "Villas de nueva construcción en Elviria"
 },
 "/es/reformas-villas/marbella": {
  "image": "/og/es--reformas-villas--marbella.jpg",
  "alt": "Reformas integrales de villas en Marbella"
 },
 "/es/reformas-villas/benahavis": {
  "image": "/og/es--reformas-villas--benahavis.jpg",
  "alt": "Reformas integrales de villas en Benahavís"
 },
 "/es/reformas-villas/los-monteros": {
  "image": "/og/es--reformas-villas--los-monteros.jpg",
  "alt": "Reformas integrales de villas en Los Monteros"
 },
 "/es/reformas-villas/nueva-andalucia": {
  "image": "/og/es--reformas-villas--nueva-andalucia.jpg",
  "alt": "Reformas integrales de villas en Nueva Andalucía"
 },
 "/es/reformas-villas/estepona": {
  "image": "/og/es--reformas-villas--estepona.jpg",
  "alt": "Reformas integrales de villas en Estepona"
 },
 "/es/reformas-villas/guadalmina": {
  "image": "/og/es--reformas-villas--guadalmina.jpg",
  "alt": "Reformas integrales de villas en Guadalmina"
 },
 "/es/reformas-villas/la-zagaleta": {
  "image": "/og/es--reformas-villas--la-zagaleta.jpg",
  "alt": "Reformas integrales de villas en La Zagaleta"
 },
 "/es/reformas-villas/milla-de-oro": {
  "image": "/og/es--reformas-villas--milla-de-oro.jpg",
  "alt": "Reformas integrales de villas en la Milla de Oro"
 },
 "/es/reformas-villas/rio-real": {
  "image": "/og/es--reformas-villas--rio-real.jpg",
  "alt": "Reformas integrales de villas en Río Real"
 },
 "/es/reformas-villas/elviria": {
  "image": "/og/es--reformas-villas--elviria.jpg",
  "alt": "Reformas integrales de villas en Elviria"
 },
 "/es/interiorismo/marbella": {
  "image": "/og/es--interiorismo--marbella.jpg",
  "alt": "Interiorismo para villas en Marbella"
 },
 "/es/interiorismo/benahavis": {
  "image": "/og/es--interiorismo--benahavis.jpg",
  "alt": "Interiorismo para villas en Benahavís"
 },
 "/es/interiorismo/los-monteros": {
  "image": "/og/es--interiorismo--los-monteros.jpg",
  "alt": "Interiorismo para villas en Los Monteros"
 },
 "/es/interiorismo/nueva-andalucia": {
  "image": "/og/es--interiorismo--nueva-andalucia.jpg",
  "alt": "Interiorismo para villas en Nueva Andalucía"
 },
 "/es/interiorismo/estepona": {
  "image": "/og/es--interiorismo--estepona.jpg",
  "alt": "Interiorismo para villas en Estepona"
 },
 "/es/interiorismo/guadalmina": {
  "image": "/og/es--interiorismo--guadalmina.jpg",
  "alt": "Interiorismo para villas en Guadalmina"
 },
 "/es/interiorismo/la-zagaleta": {
  "image": "/og/es--interiorismo--la-zagaleta.jpg",
  "alt": "Interiorismo para villas en La Zagaleta"
 },
 "/es/interiorismo/milla-de-oro": {
  "image": "/og/es--interiorismo--milla-de-oro.jpg",
  "alt": "Interiorismo para villas en la Milla de Oro"
 },
 "/es/interiorismo/rio-real": {
  "image": "/og/es--interiorismo--rio-real.jpg",
  "alt": "Interiorismo para villas en Río Real"
 },
 "/es/interiorismo/elviria": {
  "image": "/og/es--interiorismo--elviria.jpg",
  "alt": "Interiorismo para villas en Elviria"
 },
 "/es/paisajismo/marbella": {
  "image": "/og/es--paisajismo--marbella.jpg",
  "alt": "Paisajismo para villas en Marbella"
 },
 "/es/paisajismo/benahavis": {
  "image": "/og/es--paisajismo--benahavis.jpg",
  "alt": "Paisajismo para villas en Benahavís"
 },
 "/es/paisajismo/los-monteros": {
  "image": "/og/es--paisajismo--los-monteros.jpg",
  "alt": "Paisajismo para villas en Los Monteros"
 },
 "/es/paisajismo/nueva-andalucia": {
  "image": "/og/es--paisajismo--nueva-andalucia.jpg",
  "alt": "Paisajismo para villas en Nueva Andalucía"
 },
 "/es/paisajismo/estepona": {
  "image": "/og/es--paisajismo--estepona.jpg",
  "alt": "Paisajismo para villas en Estepona"
 },
 "/es/paisajismo/guadalmina": {
  "image": "/og/es--paisajismo--guadalmina.jpg",
  "alt": "Paisajismo para villas en Guadalmina"
 },
 "/es/paisajismo/la-zagaleta": {
  "image": "/og/es--paisajismo--la-zagaleta.jpg",
  "alt": "Paisajismo para villas en La Zagaleta"
 },
 "/es/paisajismo/milla-de-oro": {
  "image": "/og/es--paisajismo--milla-de-oro.jpg",
  "alt": "Paisajismo para villas en la Milla de Oro"
 },
 "/es/paisajismo/rio-real": {
  "image": "/og/es--paisajismo--rio-real.jpg",
  "alt": "Paisajismo para villas en Río Real"
 },
 "/es/paisajismo/elviria": {
  "image": "/og/es--paisajismo--elviria.jpg",
  "alt": "Paisajismo para villas en Elviria"
 },
 "/journal/architecture-and-interior-design-how-they-work-together": {
  "image": "/og/journal--architecture-and-interior-design-how-they-work-together.jpg",
  "alt": "Architecture and interior design: how they work together"
 },
 "/journal/reading-architectural-drawings-and-preparing-your-questions": {
  "image": "/og/journal--reading-architectural-drawings-and-preparing-your-questions.jpg",
  "alt": "Reading architectural drawings and preparing your questions"
 },
 "/journal/renders-and-photographs-understanding-a-design-proposal": {
  "image": "/og/journal--renders-and-photographs-understanding-a-design-proposal.jpg",
  "alt": "Renders and photographs: understanding a design proposal"
 },
 "/journal/following-your-villa-project-from-abroad": {
  "image": "/og/journal--following-your-villa-project-from-abroad.jpg",
  "alt": "Following your villa project from abroad"
 },
 "/journal/renovate-or-rebuild-your-villa": {
  "image": "/og/journal--renovate-or-rebuild-your-villa.jpg",
  "alt": "Renovate your villa or build new? How to approach the decision"
 },
 "/journal/what-to-study-on-a-plot-before-designing": {
  "image": "/og/journal--what-to-study-on-a-plot-before-designing.jpg",
  "alt": "What to study on a plot before designing your villa"
 },
 "/journal/planning-permissions-what-to-ask-your-architect": {
  "image": "/og/journal--planning-permissions-what-to-ask-your-architect.jpg",
  "alt": "Planning permissions: what to ask your architect"
 },
 "/journal/budget-and-fees-defining-the-scope-first": {
  "image": "/og/journal--budget-and-fees-defining-the-scope-first.jpg",
  "alt": "Budget and fees: why it pays to define the scope first"
 },
 "/journal/site-supervision-and-contractor-coordination": {
  "image": "/og/journal--site-supervision-and-contractor-coordination.jpg",
  "alt": "Site supervision and contractor coordination: what they mean, and what they do not"
 },
 "/journal/designing-the-garden-from-the-start": {
  "image": "/og/journal--designing-the-garden-from-the-start.jpg",
  "alt": "Why the garden should be designed from the start of the project"
 },
 "/es/guias/arquitectura-interiorismo-como-se-relacionan": {
  "image": "/og/es--guias--arquitectura-interiorismo-como-se-relacionan.jpg",
  "alt": "Arquitectura e interiorismo: cómo se relacionan en un proyecto"
 },
 "/es/guias/planos-arquitectura-como-leerlos-preparar-dudas": {
  "image": "/og/es--guias--planos-arquitectura-como-leerlos-preparar-dudas.jpg",
  "alt": "Planos de arquitectura: cómo leerlos y preparar tus dudas"
 },
 "/es/guias/renders-y-fotografias-entender-una-propuesta": {
  "image": "/og/es--guias--renders-y-fotografias-entender-una-propuesta.jpg",
  "alt": "Renders y fotografías: cómo entender una propuesta de diseño"
 },
 "/es/guias/seguir-tu-proyecto-desde-otro-pais": {
  "image": "/og/es--guias--seguir-tu-proyecto-desde-otro-pais.jpg",
  "alt": "Cómo seguir el proyecto de tu villa desde otro país"
 },
 "/es/guias/reformar-o-construir-de-nuevo": {
  "image": "/og/es--guias--reformar-o-construir-de-nuevo.jpg",
  "alt": "¿Reformar tu villa o construir de nuevo? Cómo plantear la decisión"
 },
 "/es/guias/parcela-que-estudiar-antes-de-disenar": {
  "image": "/og/es--guias--parcela-que-estudiar-antes-de-disenar.jpg",
  "alt": "Qué estudiar en una parcela antes de diseñar tu villa"
 },
 "/es/guias/licencias-que-preguntar-al-arquitecto": {
  "image": "/og/es--guias--licencias-que-preguntar-al-arquitecto.jpg",
  "alt": "Licencias de obra: qué preguntar a tu arquitecto"
 },
 "/es/guias/presupuesto-y-honorarios-definir-el-alcance": {
  "image": "/og/es--guias--presupuesto-y-honorarios-definir-el-alcance.jpg",
  "alt": "Presupuesto y honorarios: por qué conviene definir antes el alcance"
 },
 "/es/guias/direccion-de-obra-y-coordinacion": {
  "image": "/og/es--guias--direccion-de-obra-y-coordinacion.jpg",
  "alt": "Dirección de obra y coordinación de empresas: qué significa y qué no"
 },
 "/es/guias/disenar-el-jardin-desde-el-principio": {
  "image": "/og/es--guias--disenar-el-jardin-desde-el-principio.jpg",
  "alt": "Por qué diseñar el jardín desde el principio del proyecto"
 }
}
