// Generated by scripts/og/generate.py: Open Graph image per page path. Do not edit by hand.
export const ogImages: Record<string, { image: string; alt: string }> = {
 "/": {
  "image": "/og/home.jpg",
  "alt": "Spaces for living well."
 },
 "/es": {
  "image": "/og/es.jpg",
  "alt": "Espacios para vivir mejor."
 },
 "/journal": {
  "image": "/og/journal.jpg",
  "alt": "Questions before your project."
 },
 "/es/guias": {
  "image": "/og/es--guias.jpg",
  "alt": "Preguntas antes de tu proyecto."
 },
 "/projects": {
  "image": "/og/projects.jpg",
  "alt": "Architecture, spaces and ways of living."
 },
 "/es/proyectos": {
  "image": "/og/es--proyectos.jpg",
  "alt": "Arquitectura, espacios y formas de vivir."
 },
 "/studio": {
  "image": "/og/studio.jpg",
  "alt": "Design and personal attention. From the idea to the site."
 },
 "/es/estudio": {
  "image": "/og/es--estudio.jpg",
  "alt": "Diseño y trato directo. De la idea a la obra."
 },
 "/contact": {
  "image": "/og/contact.jpg",
  "alt": "Tell us about your project."
 },
 "/es/contacto": {
  "image": "/og/es--contacto.jpg",
  "alt": "Cuéntanos tu proyecto."
 },
 "/villa-architecture": {
  "image": "/og/villa-architecture.jpg",
  "alt": "New-build villas on the Costa del Sol"
 },
 "/villa-renovation": {
  "image": "/og/villa-renovation.jpg",
  "alt": "Luxury villa renovations on the Costa del Sol"
 },
 "/es/arquitectura-villas": {
  "image": "/og/es--arquitectura-villas.jpg",
  "alt": "Villas de nueva construcción en la Costa del Sol"
 },
 "/es/reformas-villas": {
  "image": "/og/es--reformas-villas.jpg",
  "alt": "Reformas integrales de villas en la Costa del Sol"
 },
 "/villa-architecture/marbella": {
  "image": "/og/villa-architecture--marbella.jpg",
  "alt": "New-build villas in Marbella"
 },
 "/villa-architecture/benahavis": {
  "image": "/og/villa-architecture--benahavis.jpg",
  "alt": "New-build villas in Benahavís"
 },
 "/villa-architecture/los-monteros": {
  "image": "/og/villa-architecture--los-monteros.jpg",
  "alt": "New-build villas in Los Monteros"
 },
 "/villa-architecture/nueva-andalucia": {
  "image": "/og/villa-architecture--nueva-andalucia.jpg",
  "alt": "New-build villas in Nueva Andalucía"
 },
 "/villa-architecture/estepona": {
  "image": "/og/villa-architecture--estepona.jpg",
  "alt": "New-build villas in Estepona"
 },
 "/villa-architecture/guadalmina": {
  "image": "/og/villa-architecture--guadalmina.jpg",
  "alt": "New-build villas in Guadalmina"
 },
 "/villa-architecture/la-zagaleta": {
  "image": "/og/villa-architecture--la-zagaleta.jpg",
  "alt": "New-build villas in La Zagaleta"
 },
 "/villa-architecture/golden-mile": {
  "image": "/og/villa-architecture--golden-mile.jpg",
  "alt": "New-build villas on the Golden Mile"
 },
 "/villa-architecture/rio-real": {
  "image": "/og/villa-architecture--rio-real.jpg",
  "alt": "New-build villas in Río Real"
 },
 "/villa-architecture/elviria": {
  "image": "/og/villa-architecture--elviria.jpg",
  "alt": "New-build villas in Elviria"
 },
 "/villa-renovation/marbella": {
  "image": "/og/villa-renovation--marbella.jpg",
  "alt": "Luxury villa renovations in Marbella"
 },
 "/villa-renovation/benahavis": {
  "image": "/og/villa-renovation--benahavis.jpg",
  "alt": "Luxury villa renovations in Benahavís"
 },
 "/villa-renovation/los-monteros": {
  "image": "/og/villa-renovation--los-monteros.jpg",
  "alt": "Luxury villa renovations in Los Monteros"
 },
 "/villa-renovation/nueva-andalucia": {
  "image": "/og/villa-renovation--nueva-andalucia.jpg",
  "alt": "Luxury villa renovations in Nueva Andalucía"
 },
 "/villa-renovation/estepona": {
  "image": "/og/villa-renovation--estepona.jpg",
  "alt": "Luxury villa renovations in Estepona"
 },
 "/villa-renovation/guadalmina": {
  "image": "/og/villa-renovation--guadalmina.jpg",
  "alt": "Luxury villa renovations in Guadalmina"
 },
 "/villa-renovation/la-zagaleta": {
  "image": "/og/villa-renovation--la-zagaleta.jpg",
  "alt": "Luxury villa renovations in La Zagaleta"
 },
 "/villa-renovation/golden-mile": {
  "image": "/og/villa-renovation--golden-mile.jpg",
  "alt": "Luxury villa renovations on the Golden Mile"
 },
 "/villa-renovation/rio-real": {
  "image": "/og/villa-renovation--rio-real.jpg",
  "alt": "Luxury villa renovations in Río Real"
 },
 "/villa-renovation/elviria": {
  "image": "/og/villa-renovation--elviria.jpg",
  "alt": "Luxury villa renovations in Elviria"
 },
 "/es/arquitectura-villas/marbella": {
  "image": "/og/es--arquitectura-villas--marbella.jpg",
  "alt": "Villas de nueva construcción en Marbella"
 },
 "/es/arquitectura-villas/benahavis": {
  "image": "/og/es--arquitectura-villas--benahavis.jpg",
  "alt": "Villas de nueva construcción en Benahavís"
 },
 "/es/arquitectura-villas/los-monteros": {
  "image": "/og/es--arquitectura-villas--los-monteros.jpg",
  "alt": "Villas de nueva construcción en Los Monteros"
 },
 "/es/arquitectura-villas/nueva-andalucia": {
  "image": "/og/es--arquitectura-villas--nueva-andalucia.jpg",
  "alt": "Villas de nueva construcción en Nueva Andalucía"
 },
 "/es/arquitectura-villas/estepona": {
  "image": "/og/es--arquitectura-villas--estepona.jpg",
  "alt": "Villas de nueva construcción en Estepona"
 },
 "/es/arquitectura-villas/guadalmina": {
  "image": "/og/es--arquitectura-villas--guadalmina.jpg",
  "alt": "Villas de nueva construcción en Guadalmina"
 },
 "/es/arquitectura-villas/la-zagaleta": {
  "image": "/og/es--arquitectura-villas--la-zagaleta.jpg",
  "alt": "Villas de nueva construcción en La Zagaleta"
 },
 "/es/arquitectura-villas/milla-de-oro": {
  "image": "/og/es--arquitectura-villas--milla-de-oro.jpg",
  "alt": "Villas de nueva construcción en la Milla de Oro"
 },
 "/es/arquitectura-villas/rio-real": {
  "image": "/og/es--arquitectura-villas--rio-real.jpg",
  "alt": "Villas de nueva construcción en Río Real"
 },
 "/es/arquitectura-villas/elviria": {
  "image": "/og/es--arquitectura-villas--elviria.jpg",
  "alt": "Villas de nueva construcción en Elviria"
 },
 "/es/reformas-villas/marbella": {
  "image": "/og/es--reformas-villas--marbella.jpg",
  "alt": "Reformas integrales de villas en Marbella"
 },
 "/es/reformas-villas/benahavis": {
  "image": "/og/es--reformas-villas--benahavis.jpg",
  "alt": "Reformas integrales de villas en Benahavís"
 },
 "/es/reformas-villas/los-monteros": {
  "image": "/og/es--reformas-villas--los-monteros.jpg",
  "alt": "Reformas integrales de villas en Los Monteros"
 },
 "/es/reformas-villas/nueva-andalucia": {
  "image": "/og/es--reformas-villas--nueva-andalucia.jpg",
  "alt": "Reformas integrales de villas en Nueva Andalucía"
 },
 "/es/reformas-villas/estepona": {
  "image": "/og/es--reformas-villas--estepona.jpg",
  "alt": "Reformas integrales de villas en Estepona"
 },
 "/es/reformas-villas/guadalmina": {
  "image": "/og/es--reformas-villas--guadalmina.jpg",
  "alt": "Reformas integrales de villas en Guadalmina"
 },
 "/es/reformas-villas/la-zagaleta": {
  "image": "/og/es--reformas-villas--la-zagaleta.jpg",
  "alt": "Reformas integrales de villas en La Zagaleta"
 },
 "/es/reformas-villas/milla-de-oro": {
  "image": "/og/es--reformas-villas--milla-de-oro.jpg",
  "alt": "Reformas integrales de villas en la Milla de Oro"
 },
 "/es/reformas-villas/rio-real": {
  "image": "/og/es--reformas-villas--rio-real.jpg",
  "alt": "Reformas integrales de villas en Río Real"
 },
 "/es/reformas-villas/elviria": {
  "image": "/og/es--reformas-villas--elviria.jpg",
  "alt": "Reformas integrales de villas en Elviria"
 },
 "/journal/reading-architectural-drawings-and-preparing-your-questions": {
  "image": "/og/journal--reading-architectural-drawings-and-preparing-your-questions.jpg",
  "alt": "Reading architectural drawings and preparing your questions"
 },
 "/journal/renders-and-photographs-understanding-a-design-proposal": {
  "image": "/og/journal--renders-and-photographs-understanding-a-design-proposal.jpg",
  "alt": "Renders and photographs: understanding a design proposal"
 },
 "/journal/following-your-villa-project-from-abroad": {
  "image": "/og/journal--following-your-villa-project-from-abroad.jpg",
  "alt": "Following your villa project from abroad"
 },
 "/journal/renovate-or-rebuild-your-villa": {
  "image": "/og/journal--renovate-or-rebuild-your-villa.jpg",
  "alt": "Renovate your villa or build new? How to decide"
 },
 "/journal/what-to-study-on-a-plot-before-designing": {
  "image": "/og/journal--what-to-study-on-a-plot-before-designing.jpg",
  "alt": "What to study on a plot before designing your villa"
 },
 "/journal/planning-permissions-what-to-ask-your-architect": {
  "image": "/og/journal--planning-permissions-what-to-ask-your-architect.jpg",
  "alt": "Planning permissions: what to ask your architect"
 },
 "/journal/budget-and-fees-defining-the-scope-first": {
  "image": "/og/journal--budget-and-fees-defining-the-scope-first.jpg",
  "alt": "Budget and fees: why it pays to define the scope first"
 },
 "/journal/site-supervision-and-contractor-coordination": {
  "image": "/og/journal--site-supervision-and-contractor-coordination.jpg",
  "alt": "Site supervision and contractor coordination"
 },
 "/journal/choosing-an-architect-in-marbella": {
  "image": "/og/journal--choosing-an-architect-in-marbella.jpg",
  "alt": "How to choose an architect in Marbella"
 },
 "/journal/buying-a-villa-to-renovate": {
  "image": "/og/journal--buying-a-villa-to-renovate.jpg",
  "alt": "Buying a villa to renovate: what to check"
 },
 "/journal/building-licence-in-marbella": {
  "image": "/og/journal--building-licence-in-marbella.jpg",
  "alt": "Building licence in Marbella: the process"
 },
 "/journal/building-on-a-sloping-plot-in-benahavis": {
  "image": "/og/journal--building-on-a-sloping-plot-in-benahavis.jpg",
  "alt": "Building on a sloping plot in Benahavís"
 },
 "/journal/working-with-a-spanish-architect-from-abroad": {
  "image": "/og/journal--working-with-a-spanish-architect-from-abroad.jpg",
  "alt": "Working with a Spanish architect from abroad"
 },
 "/es/guias/planos-arquitectura-como-leerlos-preparar-dudas": {
  "image": "/og/es--guias--planos-arquitectura-como-leerlos-preparar-dudas.jpg",
  "alt": "Planos de arquitectura: cómo leerlos y preparar tus dudas"
 },
 "/es/guias/renders-y-fotografias-entender-una-propuesta": {
  "image": "/og/es--guias--renders-y-fotografias-entender-una-propuesta.jpg",
  "alt": "Renders y fotografías: cómo entender una propuesta de diseño"
 },
 "/es/guias/seguir-tu-proyecto-desde-otro-pais": {
  "image": "/og/es--guias--seguir-tu-proyecto-desde-otro-pais.jpg",
  "alt": "Cómo seguir el proyecto de tu villa desde otro país"
 },
 "/es/guias/reformar-o-construir-de-nuevo": {
  "image": "/og/es--guias--reformar-o-construir-de-nuevo.jpg",
  "alt": "¿Reformar tu villa o construir de nuevo?"
 },
 "/es/guias/parcela-que-estudiar-antes-de-disenar": {
  "image": "/og/es--guias--parcela-que-estudiar-antes-de-disenar.jpg",
  "alt": "Qué estudiar en una parcela antes de diseñar tu villa"
 },
 "/es/guias/licencias-que-preguntar-al-arquitecto": {
  "image": "/og/es--guias--licencias-que-preguntar-al-arquitecto.jpg",
  "alt": "Licencias de obra: qué preguntar a tu arquitecto"
 },
 "/es/guias/presupuesto-y-honorarios-definir-el-alcance": {
  "image": "/og/es--guias--presupuesto-y-honorarios-definir-el-alcance.jpg",
  "alt": "Presupuesto y honorarios: definir antes el alcance"
 },
 "/es/guias/direccion-de-obra-y-coordinacion": {
  "image": "/og/es--guias--direccion-de-obra-y-coordinacion.jpg",
  "alt": "Dirección de obra y coordinación de empresas"
 },
 "/es/guias/como-elegir-arquitecto-en-marbella": {
  "image": "/og/es--guias--como-elegir-arquitecto-en-marbella.jpg",
  "alt": "Cómo elegir arquitecto en Marbella"
 },
 "/es/guias/comprar-villa-para-reformar": {
  "image": "/og/es--guias--comprar-villa-para-reformar.jpg",
  "alt": "Comprar una villa para reformar: qué revisar"
 },
 "/es/guias/licencia-de-obra-en-marbella": {
  "image": "/og/es--guias--licencia-de-obra-en-marbella.jpg",
  "alt": "Licencia de obra en Marbella: el proceso"
 },
 "/es/guias/construir-en-parcela-en-pendiente-benahavis": {
  "image": "/og/es--guias--construir-en-parcela-en-pendiente-benahavis.jpg",
  "alt": "Construir en parcela en pendiente en Benahavís"
 },
 "/es/guias/arquitecto-espanol-desde-el-extranjero": {
  "image": "/og/es--guias--arquitecto-espanol-desde-el-extranjero.jpg",
  "alt": "Trabajar con un arquitecto en España desde fuera"
 },
 "/projects/the-house": {
  "image": "/og/projects--the-house.jpg",
  "alt": "The House"
 },
 "/projects/villa-silver": {
  "image": "/og/projects--villa-silver.jpg",
  "alt": "Villa Silver"
 },
 "/projects/la-resina": {
  "image": "/og/projects--la-resina.jpg",
  "alt": "La Resina"
 },
 "/projects/villa-las-fuentes": {
  "image": "/og/projects--villa-las-fuentes.jpg",
  "alt": "Villa Las Fuentes"
 },
 "/projects/villa-paris": {
  "image": "/og/projects--villa-paris.jpg",
  "alt": "Villa París"
 },
 "/projects/villa-soal": {
  "image": "/og/projects--villa-soal.jpg",
  "alt": "Villa Soal"
 },
 "/projects/orion": {
  "image": "/og/projects--orion.jpg",
  "alt": "Orion"
 },
 "/projects/la-montua": {
  "image": "/og/projects--la-montua.jpg",
  "alt": "La Montua"
 },
 "/projects/villa-alcala": {
  "image": "/og/projects--villa-alcala.jpg",
  "alt": "Villa Alcalá"
 },
 "/projects/villas-p8": {
  "image": "/og/projects--villas-p8.jpg",
  "alt": "Villas P8"
 },
 "/projects/the-villas": {
  "image": "/og/projects--the-villas.jpg",
  "alt": "The Villas"
 },
 "/projects/altos-de-los-monteros": {
  "image": "/og/projects--altos-de-los-monteros.jpg",
  "alt": "Altos de los Monteros"
 },
 "/projects/villa-feliz": {
  "image": "/og/projects--villa-feliz.jpg",
  "alt": "Villa Feliz"
 },
 "/projects/bleu-royal": {
  "image": "/og/projects--bleu-royal.jpg",
  "alt": "Bleu Royal"
 },
 "/projects/alcala": {
  "image": "/og/projects--alcala.jpg",
  "alt": "Alcalá"
 },
 "/projects/elviria": {
  "image": "/og/projects--elviria.jpg",
  "alt": "Elviria"
 },
 "/projects/cortijo-nagueles": {
  "image": "/og/projects--cortijo-nagueles.jpg",
  "alt": "Cortijo Nagüeles"
 },
 "/projects/villa-pareja": {
  "image": "/og/projects--villa-pareja.jpg",
  "alt": "Villa Pareja"
 },
 "/projects/sirio": {
  "image": "/og/projects--sirio.jpg",
  "alt": "Sirio"
 },
 "/projects/carril-del-relojero": {
  "image": "/og/projects--carril-del-relojero.jpg",
  "alt": "Carril del Relojero"
 },
 "/projects/villa-ambar": {
  "image": "/og/projects--villa-ambar.jpg",
  "alt": "Villa Ámbar"
 },
 "/projects/villa-pino": {
  "image": "/og/projects--villa-pino.jpg",
  "alt": "Villa Pino"
 },
 "/projects/atalaya": {
  "image": "/og/projects--atalaya.jpg",
  "alt": "Atalaya"
 },
 "/projects/hotel-boutique": {
  "image": "/og/projects--hotel-boutique.jpg",
  "alt": "Hotel Boutique"
 },
 "/projects/huerta-belon": {
  "image": "/og/projects--huerta-belon.jpg",
  "alt": "Huerta Belón"
 },
 "/projects/castilla": {
  "image": "/og/projects--castilla.jpg",
  "alt": "Castilla"
 },
 "/projects/parcelas-del-golf": {
  "image": "/og/projects--parcelas-del-golf.jpg",
  "alt": "Parcelas del Golf"
 },
 "/es/proyectos/the-house": {
  "image": "/og/es--proyectos--the-house.jpg",
  "alt": "The House"
 },
 "/es/proyectos/villa-silver": {
  "image": "/og/es--proyectos--villa-silver.jpg",
  "alt": "Villa Silver"
 },
 "/es/proyectos/la-resina": {
  "image": "/og/es--proyectos--la-resina.jpg",
  "alt": "La Resina"
 },
 "/es/proyectos/villa-las-fuentes": {
  "image": "/og/es--proyectos--villa-las-fuentes.jpg",
  "alt": "Villa Las Fuentes"
 },
 "/es/proyectos/villa-paris": {
  "image": "/og/es--proyectos--villa-paris.jpg",
  "alt": "Villa París"
 },
 "/es/proyectos/villa-soal": {
  "image": "/og/es--proyectos--villa-soal.jpg",
  "alt": "Villa Soal"
 },
 "/es/proyectos/orion": {
  "image": "/og/es--proyectos--orion.jpg",
  "alt": "Orion"
 },
 "/es/proyectos/la-montua": {
  "image": "/og/es--proyectos--la-montua.jpg",
  "alt": "La Montua"
 },
 "/es/proyectos/villa-alcala": {
  "image": "/og/es--proyectos--villa-alcala.jpg",
  "alt": "Villa Alcalá"
 },
 "/es/proyectos/villas-p8": {
  "image": "/og/es--proyectos--villas-p8.jpg",
  "alt": "Villas P8"
 },
 "/es/proyectos/the-villas": {
  "image": "/og/es--proyectos--the-villas.jpg",
  "alt": "The Villas"
 },
 "/es/proyectos/altos-de-los-monteros": {
  "image": "/og/es--proyectos--altos-de-los-monteros.jpg",
  "alt": "Altos de los Monteros"
 },
 "/es/proyectos/villa-feliz": {
  "image": "/og/es--proyectos--villa-feliz.jpg",
  "alt": "Villa Feliz"
 },
 "/es/proyectos/bleu-royal": {
  "image": "/og/es--proyectos--bleu-royal.jpg",
  "alt": "Bleu Royal"
 },
 "/es/proyectos/alcala": {
  "image": "/og/es--proyectos--alcala.jpg",
  "alt": "Alcalá"
 },
 "/es/proyectos/elviria": {
  "image": "/og/es--proyectos--elviria.jpg",
  "alt": "Elviria"
 },
 "/es/proyectos/cortijo-nagueles": {
  "image": "/og/es--proyectos--cortijo-nagueles.jpg",
  "alt": "Cortijo Nagüeles"
 },
 "/es/proyectos/villa-pareja": {
  "image": "/og/es--proyectos--villa-pareja.jpg",
  "alt": "Villa Pareja"
 },
 "/es/proyectos/sirio": {
  "image": "/og/es--proyectos--sirio.jpg",
  "alt": "Sirio"
 },
 "/es/proyectos/carril-del-relojero": {
  "image": "/og/es--proyectos--carril-del-relojero.jpg",
  "alt": "Carril del Relojero"
 },
 "/es/proyectos/villa-ambar": {
  "image": "/og/es--proyectos--villa-ambar.jpg",
  "alt": "Villa Ámbar"
 },
 "/es/proyectos/villa-pino": {
  "image": "/og/es--proyectos--villa-pino.jpg",
  "alt": "Villa Pino"
 },
 "/es/proyectos/atalaya": {
  "image": "/og/es--proyectos--atalaya.jpg",
  "alt": "Atalaya"
 },
 "/es/proyectos/hotel-boutique": {
  "image": "/og/es--proyectos--hotel-boutique.jpg",
  "alt": "Hotel Boutique"
 },
 "/es/proyectos/huerta-belon": {
  "image": "/og/es--proyectos--huerta-belon.jpg",
  "alt": "Huerta Belón"
 },
 "/es/proyectos/castilla": {
  "image": "/og/es--proyectos--castilla.jpg",
  "alt": "Castilla"
 },
 "/es/proyectos/parcelas-del-golf": {
  "image": "/og/es--proyectos--parcelas-del-golf.jpg",
  "alt": "Parcelas del Golf"
 },
 "/areas/benahavis": {
  "image": "/og/areas--benahavis.jpg",
  "alt": "Architect in Benahavís"
 },
 "/areas/los-monteros": {
  "image": "/og/areas--los-monteros.jpg",
  "alt": "Architect in Los Monteros"
 },
 "/areas/nueva-andalucia": {
  "image": "/og/areas--nueva-andalucia.jpg",
  "alt": "Architect in Nueva Andalucía"
 },
 "/areas/estepona": {
  "image": "/og/areas--estepona.jpg",
  "alt": "Architect in Estepona"
 },
 "/areas/guadalmina": {
  "image": "/og/areas--guadalmina.jpg",
  "alt": "Architect in Guadalmina"
 },
 "/areas/la-zagaleta": {
  "image": "/og/areas--la-zagaleta.jpg",
  "alt": "Architect in La Zagaleta"
 },
 "/areas/golden-mile": {
  "image": "/og/areas--golden-mile.jpg",
  "alt": "Architect on the Golden Mile"
 },
 "/areas/rio-real": {
  "image": "/og/areas--rio-real.jpg",
  "alt": "Architect in Río Real"
 },
 "/areas/elviria": {
  "image": "/og/areas--elviria.jpg",
  "alt": "Architect in Elviria"
 },
 "/legal-notice": {
  "image": "/og/legal-notice.jpg",
  "alt": "Legal notice"
 },
 "/privacy-policy": {
  "image": "/og/privacy-policy.jpg",
  "alt": "Privacy policy"
 },
 "/cookie-policy": {
  "image": "/og/cookie-policy.jpg",
  "alt": "Cookie policy"
 },
 "/es/zonas/benahavis": {
  "image": "/og/es--zonas--benahavis.jpg",
  "alt": "Arquitecto en Benahavís"
 },
 "/es/zonas/los-monteros": {
  "image": "/og/es--zonas--los-monteros.jpg",
  "alt": "Arquitecto en Los Monteros"
 },
 "/es/zonas/nueva-andalucia": {
  "image": "/og/es--zonas--nueva-andalucia.jpg",
  "alt": "Arquitecto en Nueva Andalucía"
 },
 "/es/zonas/estepona": {
  "image": "/og/es--zonas--estepona.jpg",
  "alt": "Arquitecto en Estepona"
 },
 "/es/zonas/guadalmina": {
  "image": "/og/es--zonas--guadalmina.jpg",
  "alt": "Arquitecto en Guadalmina"
 },
 "/es/zonas/la-zagaleta": {
  "image": "/og/es--zonas--la-zagaleta.jpg",
  "alt": "Arquitecto en La Zagaleta"
 },
 "/es/zonas/milla-de-oro": {
  "image": "/og/es--zonas--milla-de-oro.jpg",
  "alt": "Arquitecto en la Milla de Oro"
 },
 "/es/zonas/rio-real": {
  "image": "/og/es--zonas--rio-real.jpg",
  "alt": "Arquitecto en Río Real"
 },
 "/es/zonas/elviria": {
  "image": "/og/es--zonas--elviria.jpg",
  "alt": "Arquitecto en Elviria"
 },
 "/es/aviso-legal": {
  "image": "/og/es--aviso-legal.jpg",
  "alt": "Aviso legal"
 },
 "/es/politica-privacidad": {
  "image": "/og/es--politica-privacidad.jpg",
  "alt": "Política de privacidad"
 },
 "/es/politica-cookies": {
  "image": "/og/es--politica-cookies.jpg",
  "alt": "Política de cookies"
 },
 "/international-clients": {
  "image": "/og/international-clients.jpg",
  "alt": "Architect in Marbella for international clients"
 },
 "/es/clientes-internacionales": {
  "image": "/og/es--clientes-internacionales.jpg",
  "alt": "Arquitecto en Marbella para clientes que viven fuera"
 }
}
