// Generated by scripts/media/build_models.py from scripts/media/models.json. Do not edit.
import type { ProjectImage } from './projects/types'
export type ModelImage = ProjectImage & { thumb: string }
export const studioModelMedia: { id: string; images: ModelImage[] }[] = [
 {
  "id": "altos-de-los-monteros",
  "images": [
   {
    "file": "altos_monteros (2).webp",
    "src": "/media/studio/models/altos-de-los-monteros/altos-monteros-2-76887734622b-1600.avif",
    "srcset": "/media/studio/models/altos-de-los-monteros/altos-monteros-2-76887734622b-800.avif 800w, /media/studio/models/altos-de-los-monteros/altos-monteros-2-76887734622b-1600.avif 1600w, /media/studio/models/altos-de-los-monteros/altos-monteros-2-76887734622b-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JQBfnMX1buPWPTr0QjqqFAAD+cN1FQ9doERNCzyzH9IdZ2jkMnpRZd7Ud+XyUh/w4iWVLhIJ1968uGDKLG9+mDlLwXK+ei0D7bLgqx75aRdQ4cSK52ly+QwJe9fFDS1KnOxko0nB6wMetV86LHK+d9y4NAAAA",
    "thumb": "/media/studio/models/altos-de-los-monteros/altos-monteros-2-76887734622b-400.avif"
   },
   {
    "file": "altos_monteros (1).webp",
    "src": "/media/studio/models/altos-de-los-monteros/altos-monteros-1-765a459936d7-1600.avif",
    "srcset": "/media/studio/models/altos-de-los-monteros/altos-monteros-1-765a459936d7-800.avif 800w, /media/studio/models/altos-de-los-monteros/altos-monteros-1-765a459936d7-1600.avif 1600w, /media/studio/models/altos-de-los-monteros/altos-monteros-1-765a459936d7-2560.avif 2560w",
    "width": 3628,
    "height": 1738,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JaAC/OCFfHZeuwfmst5PBLsAA/suRr3jXrFOe+vB2CDUDuviYjQY+gozCZ5YkUshNUc4Dpsh01mtqY3a+GbHMPVNTG2l7cZn9Kc7tAWWO+pZ4vYE6HMfvj7Jfjt9eil3PUJAcqGaUbovccmAAAA==",
    "thumb": "/media/studio/models/altos-de-los-monteros/altos-monteros-1-765a459936d7-400.avif"
   },
   {
    "file": "altos_monteros (3).webp",
    "src": "/media/studio/models/altos-de-los-monteros/altos-monteros-3-7572b2b7d8e1-1600.avif",
    "srcset": "/media/studio/models/altos-de-los-monteros/altos-monteros-3-7572b2b7d8e1-800.avif 800w, /media/studio/models/altos-de-los-monteros/altos-monteros-3-7572b2b7d8e1-1600.avif 1600w, /media/studio/models/altos-de-los-monteros/altos-monteros-3-7572b2b7d8e1-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoYAAwAPu1iqU2ppaQiMAgBMB2JQBfnA+Q2NAzTFeFnTHeAAP68c1hsODsIU7pQFOS6z7kvThkPYmPpXWpCCeUSrx9aVoeDBlddk+CCi2hbxXyrV77QXk3w67G58hcS/5qyZK4Zei7S3ZAX2rb0lD1PGrgDCIJQX5wgpYrJdX0BAAAA",
    "thumb": "/media/studio/models/altos-de-los-monteros/altos-monteros-3-7572b2b7d8e1-400.avif"
   },
   {
    "file": "altos_monteros (4).webp",
    "src": "/media/studio/models/altos-de-los-monteros/altos-monteros-4-2ea6a44e9d8e-1600.avif",
    "srcset": "/media/studio/models/altos-de-los-monteros/altos-monteros-4-2ea6a44e9d8e-800.avif 800w, /media/studio/models/altos-de-los-monteros/altos-monteros-4-2ea6a44e9d8e-1600.avif 1600w, /media/studio/models/altos-de-los-monteros/altos-monteros-4-2ea6a44e9d8e-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBACdASoYAAwAPu1iqk2ppaQiMAgBMB2JZgC2yYvC3tuCgZma7P9rAAD+2Ls5f0NgrOC70iegjSsGcpX6/SWW4G/kCnTCSN4c0AgNT8fYQK6sCm23r4nRtsVBgFTDim9LYJrKNxODfWU+MUIsg7oQbtycoa21JDU9ddd/3pmtvNehfmAAAA==",
    "thumb": "/media/studio/models/altos-de-los-monteros/altos-monteros-4-2ea6a44e9d8e-400.avif"
   },
   {
    "file": "altos_monteros (5).webp",
    "src": "/media/studio/models/altos-de-los-monteros/altos-monteros-5-d9df4eeabc29-1600.avif",
    "srcset": "/media/studio/models/altos-de-los-monteros/altos-monteros-5-d9df4eeabc29-800.avif 800w, /media/studio/models/altos-de-los-monteros/altos-monteros-5-d9df4eeabc29-1600.avif 1600w, /media/studio/models/altos-de-los-monteros/altos-monteros-5-d9df4eeabc29-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoYAAwAPu1iqk4ppaQiMAgBMB2JYgC/OCHgpD0puu+s09Lp2EAA/ujKju7cTENkac0gtCHmCCseo09l+SQKe19JT3P2Z7peEunJVrRcPycf+Zz2PqB6HVBS9fFFBeQf2RoW3MuOFWfTE5fZ2mYK+lu/x+Ed3X4QKiSm3ZgAAAA=",
    "thumb": "/media/studio/models/altos-de-los-monteros/altos-monteros-5-d9df4eeabc29-400.avif"
   },
   {
    "file": "altos_monteros (6).webp",
    "src": "/media/studio/models/altos-de-los-monteros/altos-monteros-6-0a9122a8caca-1600.avif",
    "srcset": "/media/studio/models/altos-de-los-monteros/altos-monteros-6-0a9122a8caca-800.avif 800w, /media/studio/models/altos-de-los-monteros/altos-monteros-6-0a9122a8caca-1600.avif 1600w, /media/studio/models/altos-de-los-monteros/altos-monteros-6-0a9122a8caca-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAwCdASoYAAwAPu1iqU2ppaOiMAgBMB2JZAC/OBjyiPgga/OYAAD+2VjXc7bgGujx3FAq6RNxjkNF+h/UTjT8jKu9lzMY5mKM6w/ltyujTYDnVfzhoQcC/nEugK6n9HoNmFQdCE5a+70sGK2BM6J3hvmU1QvVOlE/6P8yiUYYM3Kfe8NdJY2MbeHDREBUAAA=",
    "thumb": "/media/studio/models/altos-de-los-monteros/altos-monteros-6-0a9122a8caca-400.avif"
   }
  ]
 },
 {
  "id": "la-montua",
  "images": [
   {
    "file": "montua (2).webp",
    "src": "/media/studio/models/la-montua/montua-2-910cbdaee5f3-1600.avif",
    "srcset": "/media/studio/models/la-montua/montua-2-910cbdaee5f3-800.avif 800w, /media/studio/models/la-montua/montua-2-910cbdaee5f3-1600.avif 1600w, /media/studio/models/la-montua/montua-2-910cbdaee5f3-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQAwCdASoYAAwAPu1iqk4ppaQiMAgBMB2JQBYdg3HaMKFd+B13U0AA1pGsCmqYnmkqjoPhiOPocjIHeRQMfmjJVXF8Tz6Sjix8sEAZujrrfIcw1bY/THzIByb633UlVW2+aGAoTQvR4G4g9I5gQFTX97Er5//3yb3EDczidSUTYsaCyQcxQAAA",
    "thumb": "/media/studio/models/la-montua/montua-2-910cbdaee5f3-400.avif"
   },
   {
    "file": "montua (3).webp",
    "src": "/media/studio/models/la-montua/montua-3-9ddef901c2a0-1600.avif",
    "srcset": "/media/studio/models/la-montua/montua-3-9ddef901c2a0-800.avif 800w, /media/studio/models/la-montua/montua-3-9ddef901c2a0-1600.avif 1600w, /media/studio/models/la-montua/montua-3-9ddef901c2a0-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADQAwCdASoYAAwAPu1oqk6ppiQiMAgBMB2JZAC7AB5ow42rOG9DNQAA8ijDaN8yGHEE0f/rGSX35r7K+42auja88hOuI5tD8E2qRYScBenY7nCQSRFZrOPit+ONEEqH2IJUSy+VYNYH0mer4pQrUqG0Q33CWvRsnZ6qTsIWdqTvhuHPMIZ8l4catODs4AAA",
    "thumb": "/media/studio/models/la-montua/montua-3-9ddef901c2a0-400.avif"
   },
   {
    "file": "montua (1).webp",
    "src": "/media/studio/models/la-montua/montua-1-724d3724bec4-1600.avif",
    "srcset": "/media/studio/models/la-montua/montua-1-724d3724bec4-800.avif 800w, /media/studio/models/la-montua/montua-1-724d3724bec4-1600.avif 1600w, /media/studio/models/la-montua/montua-1-724d3724bec4-2560.avif 2560w",
    "width": 3287,
    "height": 1663,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoYAAwAPu1iqU2ppaQiMAgBMB2JYgC2yBeE3zjUCyB5DffwAADhGfRtuL22OEAAMKHu36e555MeK2DcCj/JkcVHdRwpAqE0Q+TeA/ck3s5qSUF/ILh9RVkkAD0wF8m1nxMEq5358Au1ZuaASGURN0ITFzSZ+pUW4sWP5qvZCIyJCrx3lvoAAA==",
    "thumb": "/media/studio/models/la-montua/montua-1-724d3724bec4-400.avif"
   },
   {
    "file": "montua (4).webp",
    "src": "/media/studio/models/la-montua/montua-4-5ea27b98108a-1600.avif",
    "srcset": "/media/studio/models/la-montua/montua-4-5ea27b98108a-800.avif 800w, /media/studio/models/la-montua/montua-4-5ea27b98108a-1600.avif 1600w, /media/studio/models/la-montua/montua-4-5ea27b98108a-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBACdASoYAAwAPu1iqU2ppaQiMAgBMB2JYgBV0FvzNTkkDNn1PkPA+fC8AADr6fIwALuokOcwDnzr3VrPtJqz7nAfAlA/Wgl+5IgpXiYU3L17uwWNr7GAO6VYxjMV9/WJ0KoHhrs3U/isP6R6vR/CZPCmmsbvEEYPrs6foFdG8vHk6TgcSgpEcBraKSAMGXVAAA==",
    "thumb": "/media/studio/models/la-montua/montua-4-5ea27b98108a-400.avif"
   },
   {
    "file": "montua (5).webp",
    "src": "/media/studio/models/la-montua/montua-5-93c6c328a288-1600.avif",
    "srcset": "/media/studio/models/la-montua/montua-5-93c6c328a288-800.avif 800w, /media/studio/models/la-montua/montua-5-93c6c328a288-1600.avif 1600w, /media/studio/models/la-montua/montua-5-93c6c328a288-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JQAB8ljp9zfz8sJYmIKkUAAAA/jt+rXx7D4ActrbSJtVkqA3sEp8nsXGLkFx8igvCBjEaU9Xi6e6z3nCr3GqSMk4uFFcaJ3jt/sk2GTZCCSbuAjJv8QuCJ2d8rzdRNQXRLpCAGIWQcqwZOhoqxcYx7OKDLAvIaRLpTc+WCaJqmE/3AAA=",
    "thumb": "/media/studio/models/la-montua/montua-5-93c6c328a288-400.avif"
   },
   {
    "file": "montua (6).webp",
    "src": "/media/studio/models/la-montua/montua-6-7fb8b68ad83d-1600.avif",
    "srcset": "/media/studio/models/la-montua/montua-6-7fb8b68ad83d-800.avif 800w, /media/studio/models/la-montua/montua-6-7fb8b68ad83d-1600.avif 1600w, /media/studio/models/la-montua/montua-6-7fb8b68ad83d-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYAAwAPu1iqU2ppaQiMAgBMB2JZgC/OCFrLVbNMSeEo19SgAD+JXKJ6XT7QfHU0oV21PIwQl1O7XtmVzgosJ1uhTz0q3uUI5qBqMZwajyexnSTPq9aOidpvgqS7fZijuwZKmlRiKv449yGBaifw/gqL/ri0jpOPuZA4vZ/AeaHNbLLQ8fjp3nic8pEQwAA",
    "thumb": "/media/studio/models/la-montua/montua-6-7fb8b68ad83d-400.avif"
   }
  ]
 },
 {
  "id": "villa-pareja",
  "images": [
   {
    "file": "pareja (1).webp",
    "src": "/media/studio/models/villa-pareja/pareja-1-21f79f05c50b-1600.avif",
    "srcset": "/media/studio/models/villa-pareja/pareja-1-21f79f05c50b-800.avif 800w, /media/studio/models/villa-pareja/pareja-1-21f79f05c50b-1600.avif 1600w, /media/studio/models/villa-pareja/pareja-1-21f79f05c50b-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoYAAwAPu1iqU2ppaQiMAgBMB2JQAAJQX8UCYcReXbMMAAA/XhGxPTUjtIKKwhGcBqvjUeb4gtq0jzrHWnuE6Sg5WrmjR77GNgAFc0s/fYOMbGeEG4Mn4XK13dC9fzJ+fc6FCqgTPQnKb7PpWN01dpAAAA=",
    "thumb": "/media/studio/models/villa-pareja/pareja-1-21f79f05c50b-400.avif"
   },
   {
    "file": "pareja (5).webp",
    "src": "/media/studio/models/villa-pareja/pareja-5-d13a61a4df6c-1600.avif",
    "srcset": "/media/studio/models/villa-pareja/pareja-5-d13a61a4df6c-800.avif 800w, /media/studio/models/villa-pareja/pareja-5-d13a61a4df6c-1600.avif 1600w, /media/studio/models/villa-pareja/pareja-5-d13a61a4df6c-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAwBACdASoYAAwAPu1iqU2ppaQiMAgBMB2JYgC06dwLgsYb90j+6qtgQAAA/uNNTcT16/pVWOWgkh3grD/GtdGOyhxHNFkIjATy68+onhlunYp/59JHlK1vDcyN910AeTFmDhynqubF9/vVzYRfTBM4LMaMip0hG78277UNi/K63jJylDobegp6VyrV0HGer7ZQMegA",
    "thumb": "/media/studio/models/villa-pareja/pareja-5-d13a61a4df6c-400.avif"
   },
   {
    "file": "pareja (2).webp",
    "src": "/media/studio/models/villa-pareja/pareja-2-c355a2a22b47-1600.avif",
    "srcset": "/media/studio/models/villa-pareja/pareja-2-c355a2a22b47-800.avif 800w, /media/studio/models/villa-pareja/pareja-2-c355a2a22b47-1600.avif 1600w, /media/studio/models/villa-pareja/pareja-2-c355a2a22b47-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwAwCdASoYAAwAPu1kqU4ppaOiMAgBMB2JZQAAW+fcYxWtdIAA/ssyeZydoXNs7uGIU7Y+290ydiLjrZbPzT5EWB+QwB3OX83K50pPcuqukz+WHnigyfx/+eywPhw0ZjHOj+Y3qi1coHPiOm7dgAAA",
    "thumb": "/media/studio/models/villa-pareja/pareja-2-c355a2a22b47-400.avif"
   },
   {
    "file": "pareja (3).webp",
    "src": "/media/studio/models/villa-pareja/pareja-3-3d6e42e86d91-1600.avif",
    "srcset": "/media/studio/models/villa-pareja/pareja-3-3d6e42e86d91-800.avif 800w, /media/studio/models/villa-pareja/pareja-3-3d6e42e86d91-1600.avif 1600w, /media/studio/models/villa-pareja/pareja-3-3d6e42e86d91-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoYAAwAPu1kqk4ppaQiMAgBMB2JYwAAW8/KUANNm5RiCgAA/tkrvqN2CImIE7uYTSOCKmT5EIbGKkZKOZf0lzeZuk4RvUslDNkd//HrsHs3jRAkxR52Tcjtt3p453jZ+Xv6ihf3crdYetyG2BF0k+4aUw7OhAAA",
    "thumb": "/media/studio/models/villa-pareja/pareja-3-3d6e42e86d91-400.avif"
   },
   {
    "file": "pareja (4).webp",
    "src": "/media/studio/models/villa-pareja/pareja-4-0035503dfa0d-1600.avif",
    "srcset": "/media/studio/models/villa-pareja/pareja-4-0035503dfa0d-800.avif 800w, /media/studio/models/villa-pareja/pareja-4-0035503dfa0d-1600.avif 1600w, /media/studio/models/villa-pareja/pareja-4-0035503dfa0d-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAQBQCdASoYAAwAPu1iqU2ppaOiMAgBMB2JZgC7FQA5/8Wwm7a3SMAYGNldk0LVOzgAAP6jFE5WbtcB2WzzQ6FIgIrysRSsntrJ565biVvW9+XlN7kHkI8mbZCajDCPDPVSWraOPrEkeIx4S+FqZtqLR19+9o7xUgxP/HkeJhCapMoSK3eA3b4Syv3lGJXN4Ax9Jebg0QTGJkoweRL+J1IbK3Clj3VKnlm1Qar7EAA=",
    "thumb": "/media/studio/models/villa-pareja/pareja-4-0035503dfa0d-400.avif"
   },
   {
    "file": "pareja (6).webp",
    "src": "/media/studio/models/villa-pareja/pareja-6-b0cc8aee69e2-1600.avif",
    "srcset": "/media/studio/models/villa-pareja/pareja-6-b0cc8aee69e2-800.avif 800w, /media/studio/models/villa-pareja/pareja-6-b0cc8aee69e2-1600.avif 1600w, /media/studio/models/villa-pareja/pareja-6-b0cc8aee69e2-2554.avif 2554w",
    "width": 2554,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAADwBQCdASoYABIAPu1qr1CppaQiqAqpMB2JYgC/8AgR7Fu6GG8du7sqdWrjsbGeUfNuQIgT4f3cAAD+F6AayCR0gOKRgD56hMv/vX0RjO1/srxBMHrHcqxHAoyCfGRKoNZJhSIEGfs+b1Fq5CU51Ro6JFRcTQiZasykGN4eeZ+fXx47XwPIvnlqtllsl4dHM6hlx62QFpfpSxZBjMHIK+otIvG09hjKiPr907HV+GuvgeauyvxKQ/An/rfMusd3e0wHjqjlR27EAZOAqjNP3zeX8OZPjvIWJCazIFATIBYAAA==",
    "thumb": "/media/studio/models/villa-pareja/pareja-6-b0cc8aee69e2-400.avif"
   }
  ]
 },
 {
  "id": "la-resina",
  "images": [
   {
    "file": "resina (2).webp",
    "src": "/media/studio/models/la-resina/resina-2-db3025e82d6b-1600.avif",
    "srcset": "/media/studio/models/la-resina/resina-2-db3025e82d6b-800.avif 800w, /media/studio/models/la-resina/resina-2-db3025e82d6b-1600.avif 1600w, /media/studio/models/la-resina/resina-2-db3025e82d6b-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JaAC2ydwA70Alkn2d/9vlE7XAAAD+nYquSSl8SuXmKCVit26mqcxlVmoAFO8rvpDYy4Bg0o7Rq38KkqlkCSiVPPV4HuDSgYH4pYs664YfvI6x2mbDRf8l0uHKqV2dMuy+JjBlmkS1Jd1meAMy5AAA",
    "thumb": "/media/studio/models/la-resina/resina-2-db3025e82d6b-400.avif"
   },
   {
    "file": "resina (1).webp",
    "src": "/media/studio/models/la-resina/resina-1-540e3b5f7b1a-1600.avif",
    "srcset": "/media/studio/models/la-resina/resina-1-540e3b5f7b1a-800.avif 800w, /media/studio/models/la-resina/resina-1-540e3b5f7b1a-1600.avif 1600w, /media/studio/models/la-resina/resina-1-540e3b5f7b1a-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JbACdAB34gN4uowipfLJSAAD+cqd+URdKOklvsieHBxjBZ8WCBf3kZ5wcyT47X/EkOzEGtbBvJroKu0JmKHHynwYoW45uhg6yvS6B4/BaVbGMj31Xv3RgE6Q80KdrKlXqys4HnA+nKckpe8DVvYdrZoXaj8SjdT8nuAAA",
    "thumb": "/media/studio/models/la-resina/resina-1-540e3b5f7b1a-400.avif"
   },
   {
    "file": "resina (3).webp",
    "src": "/media/studio/models/la-resina/resina-3-0bf51e524dd9-1600.avif",
    "srcset": "/media/studio/models/la-resina/resina-3-0bf51e524dd9-800.avif 800w, /media/studio/models/la-resina/resina-3-0bf51e524dd9-1600.avif 1600w, /media/studio/models/la-resina/resina-3-0bf51e524dd9-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoYAAwAPu1iqU2ppaQiMAgBMB2JZgCw7CFNjKScFm/Q3tTpAAD+uQUuLKc/rk6e6x/1xydPqT+XeOCpCgR5nSXtCMYo5EGFEJaOjvzXcHz6NZ8DCsG12OWtjttmHlUKj42n5L34txVo/0JPr/Ht6ggC+/z3mPMXdFOCaIIPJVruAkMDEemY4SPNBRkx3YWUBCsY8MAA",
    "thumb": "/media/studio/models/la-resina/resina-3-0bf51e524dd9-400.avif"
   },
   {
    "file": "resina (4).webp",
    "src": "/media/studio/models/la-resina/resina-4-0a61904e0024-1600.avif",
    "srcset": "/media/studio/models/la-resina/resina-4-0a61904e0024-800.avif 800w, /media/studio/models/la-resina/resina-4-0a61904e0024-1600.avif 1600w, /media/studio/models/la-resina/resina-4-0a61904e0024-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBACdASoYAAwAPu1kqk4ppaQiMAgBMB2JagCw7CF5hqsj+nbggFVVte9wAP65JPz5wMhyv68kcssyvSooVw/t3OcWfl+PRJmmJ2XzcFVcpkIWM4QDrieH4qcp2GhjqyQQio28wRmeg9MfQ/T2PpMty+fp2AQ15QxpOl9YnGrYP47VVI0CwbKl7w9ZXlilAoAAAA==",
    "thumb": "/media/studio/models/la-resina/resina-4-0a61904e0024-400.avif"
   },
   {
    "file": "resina (5).webp",
    "src": "/media/studio/models/la-resina/resina-5-c40449d7f1cc-1600.avif",
    "srcset": "/media/studio/models/la-resina/resina-5-c40449d7f1cc-800.avif 800w, /media/studio/models/la-resina/resina-5-c40449d7f1cc-1600.avif 1600w, /media/studio/models/la-resina/resina-5-c40449d7f1cc-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JagC7IEyDgbU9Dkky9iK8h64q4wAA/oWKqfEr1VTi9vjvX/pE+kZvj9yEbQkJMtUE3vNGh2yj8HEXjDK7savRzLDu2FvqIbYAPSdh47Gn0SaWXw19V0A/+tthFRtrvs5uMBcir9TcrQMaYCFEiQU6wGJlFCInXjGCpgNW4dL11bK3cAAAAA==",
    "thumb": "/media/studio/models/la-resina/resina-5-c40449d7f1cc-400.avif"
   },
   {
    "file": "resina (6).webp",
    "src": "/media/studio/models/la-resina/resina-6-bc7e543a585a-1600.avif",
    "srcset": "/media/studio/models/la-resina/resina-6-bc7e543a585a-800.avif 800w, /media/studio/models/la-resina/resina-6-bc7e543a585a-1600.avif 1600w, /media/studio/models/la-resina/resina-6-bc7e543a585a-2560.avif 2560w",
    "width": 4032,
    "height": 1960,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABQBACdASoYAAwAPu1iqU2ppaQiMAgBMB2JbAC/OYvW31Xwh5Cj+P3nVTQAAP4NmaZL6HeQxCu+/g285/TAe7hF2pDUSxlcMIlxWdsWGRFs6WrUozha2DxyfDt+aPBa+edLdcLJ3tscS/OwMBORAuqujnbHD3GSmN4Qb+pqUZRTqpgAAAA=",
    "thumb": "/media/studio/models/la-resina/resina-6-bc7e543a585a-400.avif"
   }
  ]
 }
]
