// Generated by scripts/media/build_projects.py from scripts/media/projects.json. Do not edit.
import type { ProjectMedia } from './types'
export const projectMedia: Record<string, ProjectMedia> = {
 "the-house": {
  "hero": {
   "file": "the_house_06.jpg",
   "src": "/media/projects/the-house/the-house-06-1600.avif",
   "srcset": "/media/projects/the-house/the-house-06-800.avif 800w, /media/projects/the-house/the-house-06-1600.avif 1600w, /media/projects/the-house/the-house-06-2560.avif 2560w",
   "width": 8368,
   "height": 5584,
   "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADwAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JbACdACHGy55Z0HT3dfBAAPHDNWEj6nC9T07MNKsjb/pW43jHEuEOV248NnVTyzs6GY3x0EwIdvmdkCGbn7yBdI+y+oRsegj9uKRzkUN9KTxrRNuLaTovOtsFjE4bwhTQC7HlUk9ukQTwOR5m8Ie+hRQjAuxf8iLeL3gb0Q1AysrI8qXN9GNYVu++B6WMTs6wCANQAAA=",
   "jpg": "/media/projects/the-house/the-house-06-og.jpg"
  },
  "pause": {
   "file": "the_house_01.jpg",
   "src": "/media/projects/the-house/the-house-01-1600.avif",
   "srcset": "/media/projects/the-house/the-house-01-800.avif 800w, /media/projects/the-house/the-house-01-1600.avif 1600w, /media/projects/the-house/the-house-01-2560.avif 2560w",
   "width": 5272,
   "height": 2962,
   "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoYAA0APu1iqU2ppaQiMAgBMB2JQBWABFVcAUN25haiymgA/tCOQyWiOaSPV7TafdAQxGxOS/Urqo2Cdp6qysjym2paVGLbxxZulN8cwHTFH2OSl2X06MlAbOl7vtXlkXciYd0ciuWI0MJ1JGYhlzxvOrD4tGosiu7//dKKaOjjRHq0AAA="
  },
  "gallery": [
   {
    "file": "the_house_02.jpg",
    "src": "/media/projects/the-house/the-house-02-1600.avif",
    "srcset": "/media/projects/the-house/the-house-02-800.avif 800w, /media/projects/the-house/the-house-02-1600.avif 1600w",
    "width": 5272,
    "height": 2962,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoYAA0APu1kqk4ppaQiMAgBMB2JYwC7B3gAgT421d68G++KxkAA/qX+qH8/YAd+1geOTmi7zspKx+5CnYOleRBFjYwFvCu1T4MhcIpJfIKWuW9a6nkT9RX2aCg7oBbtJ0nGdXM5h2vuKc8RnmnmBb3wfoR/TJul3kzODMbx+4EptfIZ8BtO4wAA"
   },
   {
    "file": "the_house_03.jpg",
    "src": "/media/projects/the-house/the-house-03-1600.avif",
    "srcset": "/media/projects/the-house/the-house-03-800.avif 800w, /media/projects/the-house/the-house-03-1600.avif 1600w",
    "width": 8368,
    "height": 5584,
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdACK1L6+E8+Am0niZXXTAAP3QHWCiW+7Zh8YD+h1rmZV4PL/u7943N3GXfWIu48trMuuOJYHYp5xqt2t9AfjbRa4gweIwNOM+/tAfuyxrm4cMs2BCQAybD+WV/NYTVD9lPE0soME+nWs51IGr23cv+V7+4+ZO6NVdlJf0oVmDsYnxwsaY1m70ZQn2uB/SFOAA"
   },
   {
    "file": "the_house_04.jpg",
    "src": "/media/projects/the-house/the-house-04-1600.avif",
    "srcset": "/media/projects/the-house/the-house-04-800.avif 800w, /media/projects/the-house/the-house-04-1600.avif 1600w",
    "width": 8368,
    "height": 5584,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdAYyelq+jWODHfbH+MgAA99NXZpWNM72vxWNlLmaEmiynmD6fqUqxHtJCyGuB53e8BUNGvLPoTmUV3akUmjh0UMyycHaDo0jJ+xAgkAoRliif4TxnjTJi1U4R/n/k96jN6RWzdjMsgX10NwXIMyswk6f44Q9fLl9umNnYRscdtXGsoWL8v92GSPbPwFWbdR4fNeo4POp+vY7WqAAA"
   },
   {
    "file": "the_house_05.jpg",
    "src": "/media/projects/the-house/the-house-05-1600.avif",
    "srcset": "/media/projects/the-house/the-house-05-800.avif 800w, /media/projects/the-house/the-house-05-1600.avif 1600w",
    "width": 8368,
    "height": 5584,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdL46BEBcGdYyZTEENYAD94c+oIJI/oMAoSw1MmWv1zBXSDqqEbg7tU1ZlVp4j65TPH30mQQulNmpbYLlnrADZoDiE+gxiZzIVUOzeZfqay1I6aFhp5HZxK9SvX/IYyOyhlGSvjqF9HScIZYnivVUEV10t2ZV7awyYrbA/xAAA"
   }
  ]
 },
 "villa-silver": {
  "hero": {
   "file": "silver 1.jpg",
   "src": "/media/projects/villa-silver/silver-1-1600.avif",
   "srcset": "/media/projects/villa-silver/silver-1-800.avif 800w, /media/projects/villa-silver/silver-1-1600.avif 1600w, /media/projects/villa-silver/silver-1-2558.avif 2558w",
   "width": 2558,
   "height": 1430,
   "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYAA0APu1iqU2ppaQiMAgBMB2JaACdMoACTwA6UHztuKmD+4AA/b8QNzbsTeCfXoUJ6HliBK6nRV1YLCdruwNuEOdv5Jacp02pgfYCL187fFlHjKxMyt4M/8SKNcO9IjUEFqr88cCIuJGgC4Z06EP0ZguPBnaed/UGtqepoW2IpZX60HLNTAa5YxoZojN9Hyeb6RthCAA=",
   "jpg": "/media/projects/villa-silver/silver-1-og.jpg"
  },
  "pause": {
   "file": "terraza-atardecer.jpg",
   "src": "/media/projects/villa-silver/terraza-atardecer-1600.avif",
   "srcset": "/media/projects/villa-silver/terraza-atardecer-800.avif 800w, /media/projects/villa-silver/terraza-atardecer-1600.avif 1600w, /media/projects/villa-silver/terraza-atardecer-2000.avif 2000w",
   "width": 2000,
   "height": 1335,
   "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdL1AViAytn2v2oAcwnteAAP6iOCX8nEdkzQLOuCJzYz8L/k9TzQ1QpJ7+huRGKY8jLsS724x8KsErjeSGbmYG043dzxYbisyV5eIj+j1NTH29pm1DtN3WPx3+HLLdBDIAOXPPbUnOg0TaQ0bAy3Yj6DJcu1yHDOgO28AaDBKJlCKdz1inQ/XJ4MPCGzDQAA=="
  },
  "gallery": [
   {
    "file": "VillaSilver_03-scaled.jpg",
    "src": "/media/projects/villa-silver/villasilver-03-scaled-1600.avif",
    "srcset": "/media/projects/villa-silver/villasilver-03-scaled-800.avif 800w, /media/projects/villa-silver/villasilver-03-scaled-1600.avif 1600w",
    "width": 2560,
    "height": 1709,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCdIExgvQ5TZwAY/ZQ5RIAA4kc3qwoDREix1z33O/iF93hkMewpy/oWPcQWX1x04hACphI+pjy6hJDDEuOn0JSdjho+DwWpWI3FW7h0znFh4vgcYingmguKtUu4ELjwl0poWzebdWj9uSVc5Io6B12u/p6uY7v8wO9+XEO6jnKtNIAAAA=="
   },
   {
    "file": "VillaSilver_04-scaled.jpg",
    "src": "/media/projects/villa-silver/villasilver-04-scaled-1600.avif",
    "srcset": "/media/projects/villa-silver/villasilver-04-scaled-800.avif 800w, /media/projects/villa-silver/villasilver-04-scaled-1600.avif 1600w",
    "width": 2560,
    "height": 1559,
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYAA8APu1iqU2ppaOiMAgBMB2JbACdL11s/wHjdP9eDZCFNw2sAAD+dlZoPqMcf/AnMaoflmEAbuG3wm/VEVir3Zam2Zz/4TRoSf/j6WBCjEVX+W7rvFqMUL9ll8tB5KTfYosv307YN26bqwrWHgR7V6FjIxjorxNHyfNDZw9Dd3YxJu8SSz1ybPI75gslNMFNh+Mk8byr1WmS/kx/GAsMKAA="
   },
   {
    "file": "silver 2.jpg",
    "src": "/media/projects/villa-silver/silver-2-1600.avif",
    "srcset": "/media/projects/villa-silver/silver-2-800.avif 800w, /media/projects/villa-silver/silver-2-1600.avif 1600w",
    "width": 2558,
    "height": 1432,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdMoMYOHcAsq4pgi3r1hTMZgAA/oISq6mAE1GCJ0+s3KpSO0bKiCPeFGNMqepirQ4EDmZYbdjihIKanrCe9Y6HEBsCnJRC0J+RFP2hUBN8gfLyXxeucnbNDDl/QA031tMsNOZ16ZXXRajbxY1GZd8PTwX61UAAAA=="
   }
  ]
 },
 "la-resina": {
  "hero": {
   "file": "la_resina_02.jpg",
   "src": "/media/projects/la-resina/la-resina-02-1600.avif",
   "srcset": "/media/projects/la-resina/la-resina-02-800.avif 800w, /media/projects/la-resina/la-resina-02-1600.avif 1600w, /media/projects/la-resina/la-resina-02-2560.avif 2560w",
   "width": 4096,
   "height": 2731,
   "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoR4GCxWv4jPfUxSDsoaAAD+gfLwTIhoioxtCgbwqS48x2MONaAQzULfXxE18CTZLbp1KF/QdHMugSdRY+HepQgreyYS7MqehFtno/7hiter31hhekn8Bi/VTlpEfbvrpIWaYhHJLRrg1m91JqRfbMKaAAAAAA==",
   "jpg": "/media/projects/la-resina/la-resina-02-og.jpg"
  },
  "pause": {
   "file": "la_resina_07.jpg",
   "src": "/media/projects/la-resina/la-resina-07-1600.avif",
   "srcset": "/media/projects/la-resina/la-resina-07-800.avif 800w, /media/projects/la-resina/la-resina-07-1600.avif 1600w, /media/projects/la-resina/la-resina-07-2560.avif 2560w",
   "width": 4096,
   "height": 3072,
   "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACwBQCdASoYABIAPu1gq1AppKOisBgIATAdiWIAuzNlr/4BeRg8bsRlj5qqBFLgpU33lw6bqKAA8mdq9P3VeO0TwNXeXb5zQ8Bd0jbJorDkLmQrh4qsCu3HwaCH2KDqrffAGHdkH3jNh4vrAH3WqMxHhUmVpfWS3fb3AhOySgEJEXu0fvWh9EFj2220FZ7OkXj9Rj5uNQ3xnJtoUdROAxy8BuIAAA=="
  },
  "gallery": [
   {
    "file": "la_resina_01.jpg",
    "src": "/media/projects/la-resina/la-resina-01-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-01-800.avif 800w, /media/projects/la-resina/la-resina-01-1600.avif 1600w",
    "width": 4096,
    "height": 2731,
    "lqip": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoAlsxexpR1tQU5aeXam4lRIAAD+dwX9onmKpvFwB2mcywlmQL+1mv0dSODejVXu5nrg6eVYAHqp3OoENNLo9D6uSVYfikMM1XuzjZsVdLxgS0E51miGRBj08vsmfd6K/C3LV2bt4mvunannocaBoYIxV90xJol85El92SndyIpB0rArksOjP/hRmNwGqYbtWWyne9CNAp1Nsmwdqx7OxFxo1+AAAA=="
   },
   {
    "file": "la_resina_03.jpg",
    "src": "/media/projects/la-resina/la-resina-03-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-03-800.avif 800w, /media/projects/la-resina/la-resina-03-1600.avif 1600w",
    "width": 4096,
    "height": 2731,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMjb0fVOGsHWHpAT7ycwAD3sJsFjht2dUYvgY/H9n40eIAa+dugh+Vgw5nCV79mpLXR/VT+J/2ygjMmHMjacePXckXJRUN3PuXcBhK6CGQzpFtQQF7mjnmuK+i13APjf1k2Y96YVaAFAgVa1dfZplYiRpUSVpMphmHkJ+uhHH7pnG4Mficbfd7D82lUs/mAAAA="
   },
   {
    "file": "la_resina_04.jpg",
    "src": "/media/projects/la-resina/la-resina-04-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-04-800.avif 800w, /media/projects/la-resina/la-resina-04-1600.avif 1600w",
    "width": 4096,
    "height": 2731,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoYABAAPu1iqk4ppaQiMAgBMB2JbACdMoADUE1bFLLdwt0/AADKZPuskqfTWIwzVhCl1tJRzpOMejUPnqdrzfYl3iFp6ruMsy5hJm9g8mTnVnis7Eeg/0JYvMrKUUzMsmAwzqcZ7SOQcIu3PqFLI6p74BhSqX9ut1GWFxQPZlDB4ZcTCiqC+hQQNekj1X38AAA="
   },
   {
    "file": "la_resina_05.jpg",
    "src": "/media/projects/la-resina/la-resina-05-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-05-800.avif 800w, /media/projects/la-resina/la-resina-05-1600.avif 1600w",
    "width": 4096,
    "height": 3072,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAADwBQCdASoYABIAPu1sqlGppaOiqAqpMB2JQBOmbLX/wDcaoj28v2CkN9Z2tlUiD/ls/Lvz+g3wAAD+QEvh8Y1P5ca1VqcWVFVjTdzqb2MhVOVM1UHuwzvyd3CD4sXco3MCXIj26Hq3Lyre/gmSbJH89z4xSII/nM2VbDNXANXCCG96ZKewDLbjDijBDAFagqvRJjjJc+eLq/ncQR2a7tbd6Iphbu648qO0DE12ZZYFHl3GozMTeAAA"
   },
   {
    "file": "la_resina_06.jpg",
    "src": "/media/projects/la-resina/la-resina-06-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-06-800.avif 800w, /media/projects/la-resina/la-resina-06-1600.avif 1600w",
    "width": 4096,
    "height": 3072,
    "lqip": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAABwBQCdASoYABIAPu1qrFEppaQiqAqpMB2JQBOgO4Fw2mf7QR9hFGIFyCjm6Kx0rIcjo60YAP6NzlnB9RmRkQDrN/3MsJRe2NV0svew/R87qirrOCBdeAShYFEKB6+/M3Baq13kbDpplZ2PxMJCtn3E6LFMin5HDPuMxefbZrVgEfmwx0WBVEfHjehD5N/V462+bKEbdsIFTw6KE2J2drkQFk3KvgycgzgNhynlgxECImGrHs4ghN1CU9k3dcCJ8SHpTmLxWYGSwTWqkCWA4AAA"
   }
  ]
 },
 "cutar": {
  "hero": {
   "file": "cutar_01_retoq.png",
   "src": "/media/projects/cutar/cutar-01-retoq-1600.avif",
   "srcset": "/media/projects/cutar/cutar-01-retoq-800.avif 800w, /media/projects/cutar/cutar-01-retoq-1600.avif 1600w, /media/projects/cutar/cutar-01-retoq-1920.avif 1920w",
   "width": 1920,
   "height": 1072,
   "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUAS2onNOkJ5QVI4wIr5Q6AAAzJdfw+ARoTvZs2SHc6LQLSlsjVz/Izw+YYrJmpEmgL1kSzYje2PvFPQCHrHyhHzsJSN+kNTOdumdF+yn5MEqK4TJQ8KBkpFICfdjC5MozM+TB/PryjaB8JSnEGuyP67+xQIBOp7LKYXZosAA",
   "jpg": "/media/projects/cutar/cutar-01-retoq-og.jpg"
  },
  "pause": {
   "file": "cutar_05.jpg",
   "src": "/media/projects/cutar/cutar-05-1600.avif",
   "srcset": "/media/projects/cutar/cutar-05-800.avif 800w, /media/projects/cutar/cutar-05-1600.avif 1600w, /media/projects/cutar/cutar-05-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgBEDLIonNkxcBP4AA/pqjgFMhbWGfJ9uHlYI58q5kWZdYiywVUSTrGlaXZPF5NyuzQcy8xQSL8vZ/WyeZamMxjv2ocJQldyxc8f7Vyf9FF8u9PF5701mNu5P6lfOEBYGUe1HpnmRMnWhZV3y+8Tb3/i3JMrJBjJ2+AAA="
  },
  "gallery": [
   {
    "file": "cutar_02.jpg",
    "src": "/media/projects/cutar/cutar-02-1600.avif",
    "srcset": "/media/projects/cutar/cutar-02-800.avif 800w, /media/projects/cutar/cutar-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoYAA4APu1kqU2ppaQiMAgBMB2JYwCsACKKby2rjcML24F8a0dIAPKW3jBS+f4S7jeAWQwNrrxKq6BNE0Aptb0WDAnw8HDL/VS2+bJ3uJ4XoswYpiEODIXoQc8oVxzkfT6Wwbm5QyOs2kIm7rjHvMhIOLHGCsiiuDhy+p4nTi5rY9sORsz4YEciYiYwCgAA"
   },
   {
    "file": "cutar_03.jpg",
    "src": "/media/projects/cutar/cutar-03-1600.avif",
    "srcset": "/media/projects/cutar/cutar-03-800.avif 800w, /media/projects/cutar/cutar-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdMoApCfu8IIa/uUr1KuJ0Vvks4AD81bKfJm3fT0zjA/e87w18UAQKFzNhEp/ElQqUKU9zDQnwfdbEi4sIEEbfAEa9HriSPf2yaLdKTlrSrxNcI1rNuD1Jn7+ms088tttnqdgypSzF/DLZWNHjGkI9bvbdw0nsHInAu+dflNmWmyUqLRnmH8vkfwAA"
   },
   {
    "file": "cutar_04.jpg",
    "src": "/media/projects/cutar/cutar-04-1600.avif",
    "srcset": "/media/projects/cutar/cutar-04-800.avif 800w, /media/projects/cutar/cutar-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgA8840bjcCUmZRREAAP7U0vrQlic5jyMVPNVlyq3ZSjChCzcLj/JVhSIzj5af/PQQI+RJT3zYKQNzk3iVOYMWGSMxRZQiF/OV+x/Jqd3wvPcTXt4mwdd/LabCDwbPV+iqsdlnpVdvI5UoAOFwuSUXmhWLD8L7pMjQgAA="
   }
  ]
 },
 "villa-paris": {
  "hero": {
   "file": "villa_paris_02.jpg",
   "src": "/media/projects/villa-paris/villa-paris-02-9e2e03851e2e-1600.avif",
   "srcset": "/media/projects/villa-paris/villa-paris-02-9e2e03851e2e-800.avif 800w, /media/projects/villa-paris/villa-paris-02-9e2e03851e2e-1600.avif 1600w, /media/projects/villa-paris/villa-paris-02-9e2e03851e2e-2560.avif 2560w",
   "width": 6144,
   "height": 4096,
   "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMYD8ANlWPHE+8AY3qwWBqAAP1RsTf6RhKtNpPvHsv0TEDH3qbb8VukctvjU4toDVFNaNIFh1mxzErkD/qEoX3uotiZsa7ipBlTF6AwZvRopMe1LvoQqL+lm/uJP8tuda/X7SsXCQQgxXi0bXfuNqhCk4bX1KII/RhF0nAh6UJzna3m8zIyvvuCYAA=",
   "jpg": "/media/projects/villa-paris/villa-paris-02-9e2e03851e2e-og.jpg"
  },
  "pause": {
   "file": "villa_paris_03.jpg",
   "src": "/media/projects/villa-paris/villa-paris-03-58f73b617453-1600.avif",
   "srcset": "/media/projects/villa-paris/villa-paris-03-58f73b617453-800.avif 800w, /media/projects/villa-paris/villa-paris-03-58f73b617453-1600.avif 1600w, /media/projects/villa-paris/villa-paris-03-58f73b617453-2560.avif 2560w",
   "width": 4948,
   "height": 3006,
   "lqip": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBQCdASoYAA8APu1iqU2ppaOiMAgBMB2JZgCdMoGv/i2O2rZim84D9NkkYCW5Cz7QAP4efEbsjCg3uVwSL27srIuFfZUx6F0dpa8j5FQALKp9yhw3fWj0ZUqhx+WiRKE8QEx1mJyVafzE3DIG4yEfjPKjouptmfQ+s7T9Ygp9c4TiO0QBceSTkJ/ax8mq0KcIDtjKDJMn9gqGcHtw33fQguAjbHzMesqHlCrYwkv5GZvinQ9MaI8JFopogAAA"
  },
  "gallery": [
   {
    "file": "villa_paris_01.jpg",
    "src": "/media/projects/villa-paris/villa-paris-01-2a878ad32890-1600.avif",
    "srcset": "/media/projects/villa-paris/villa-paris-01-2a878ad32890-800.avif 800w, /media/projects/villa-paris/villa-paris-01-2a878ad32890-1600.avif 1600w",
    "width": 6144,
    "height": 4096,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBfnO4AfOoHMQ7Uq3XC6IWa8AAD+aikVqC12afCPRCZgg2mFoJf6mR3Sd/qPLBeXRXSav8Co9UMFwotNJD8pWC2tHE3CAGFGIeROZ4vpQskOo8QFQcB8NEf2L1tjSu833oKvTnomEnCWl4y7cXt4hP9JnXPdJD/sGuXZpmINZm/PTcoltOWjLJxCoLZwPIrHVM1l+NOyLa4UEWAKOAAA"
   },
   {
    "file": "villa_paris_04.jpg",
    "src": "/media/projects/villa-paris/villa-paris-04-1f4ecc61143f-1600.avif",
    "srcset": "/media/projects/villa-paris/villa-paris-04-1f4ecc61143f-800.avif 800w, /media/projects/villa-paris/villa-paris-04-1f4ecc61143f-1600.avif 1600w",
    "width": 4048,
    "height": 3032,
    "lqip": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAAAQBgCdASoYABIAPu1qrlCppaQiqAqpMB2JaAC24aaIYDahiVfZgUrKmtz3NCtguaq2mdxJr8kgE8AA/tmw3CJxI1sUh2rbfA7JCfe9tF3T0fySvYTZOP3SDBAw4C5YDx+61H/8EzaRv0Dvt+Edl8hgBxYtr/UlbhgSchE2XTnRm+gkTLH55psk/Yqjnxe1CETuPhLV1QNLnCXVIqeLxX3blZhFMYU8Me8iNqwExYGYY7Ez6ONu7Bxyw6KK/Xa5lZIgmik8LsnsNju0vM3NyVkr8Qi9gPpAuonKMQWfSqwAAA=="
   },
   {
    "file": "villa_paris_05.jpg",
    "src": "/media/projects/villa-paris/villa-paris-05-c32189ec87e9-1600.avif",
    "srcset": "/media/projects/villa-paris/villa-paris-05-c32189ec87e9-800.avif 800w, /media/projects/villa-paris/villa-paris-05-c32189ec87e9-1600.avif 1600w",
    "width": 8688,
    "height": 5792,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCdIJPgqRZQTHMV9N3e2zgmAP6Z7Tbmk5HulyflbyND4lBIdqII8g8LtqFmTddeMcwYnFyiKKKPLUFKvVqrtHWnMT7ZM3WYacberY9povcJhs3SZRX4rJIxLRKznvszoLo+Fq5PkTaBaPxlta6WmRws6TYu4tomRNllJh3Zv+qPv+LUSjNk6KPvB8eJeA9YBcYCqd9PzoJ7dZkUAAAA"
   },
   {
    "file": "villa_paris_06.jpg",
    "src": "/media/projects/villa-paris/villa-paris-06-eb282d8d789e-1600.avif",
    "srcset": "/media/projects/villa-paris/villa-paris-06-eb282d8d789e-800.avif 800w, /media/projects/villa-paris/villa-paris-06-eb282d8d789e-1600.avif 1600w",
    "width": 4048,
    "height": 3032,
    "lqip": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAACQBQCdASoYABIAPu1or1AppaSiqAqpMB2JZACxH2bUCi/wDhPjk8HHMsa3kInS9g09ofwIAAD9Iw2zDIRC3q2b3C16lVLUxcyf0lsN+OVZM29aeqTDSEieYSs95F9wE+1z7IjJpbE74dUnXZfZRImhF6sPCe16CxiWVenA/W6T2RbXnFHTiV+AycCvcUlpezWpyK/1SoKT/A+oRYayXZTRVpDDDECbgM3AmMwDDpTnFYYKwRanqV4qcSEXlAAA"
   }
  ]
 },
 "villa-soal": {
  "hero": {
   "file": "villa_soal_01.jpg",
   "src": "/media/projects/villa-soal/villa-soal-01-1600.avif",
   "srcset": "/media/projects/villa-soal/villa-soal-01-800.avif 800w, /media/projects/villa-soal/villa-soal-01-1600.avif 1600w, /media/projects/villa-soal/villa-soal-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdH8GJ/gMsconXft35O6OiUsy4APoNnnEOsahCU2X0MwK6fjna8IstWNhL2EAwisE8Y15msypW0zOjv52QmQkq9Qagn7MVebaVlunBGeb4TWgnPyZb1BZtadege97mbqecCH2RRiUqSxV7OLSiQb3zyTt0Jq1KgJ0w8O1t2Z3xXO0K+KrbgAA=",
   "jpg": "/media/projects/villa-soal/villa-soal-01-og.jpg"
  },
  "pause": {
   "file": "villa_soal_07.jpg",
   "src": "/media/projects/villa-soal/villa-soal-07-1600.avif",
   "srcset": "/media/projects/villa-soal/villa-soal-07-800.avif 800w, /media/projects/villa-soal/villa-soal-07-1600.avif 1600w, /media/projects/villa-soal/villa-soal-07-2560.avif 2560w",
   "width": 4096,
   "height": 2304,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgBCXDvCM0JbPKSl+wAM3gGbdMwbI2ZHIFo5K4J03yzjqLU8Pl5LgdVyBZDlphE1Q4Arw/+NhAzNfyakiAyoPQ29l+HpyvnMoiUDDV/1rm6lcBfM0Yo3ZgBH0AAH+8yy/cybeDlNUioOv86U8XXk9VBr0TCCmH9ByBAAA="
  },
  "gallery": [
   {
    "file": "villa_soal_02.jpg",
    "src": "/media/projects/villa-soal/villa-soal-02-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-02-800.avif 800w, /media/projects/villa-soal/villa-soal-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdIMgCxxWMLYwqIVGkNCoCpAAA99U9BeLQqU89K0tYaWIiRVr+SpkjjlSbhoJLO+gLCJFTDNPS+anikFOLOnPOEzssoBqnf14huN/aUk2A37R0I2Uz2ok3VAh+AvI4SVBfYGdl7qds3/h1Gt3AhoZJ9utRjhHNqeMG/fgeDOWAAAA="
   },
   {
    "file": "villa_soal_03.jpg",
    "src": "/media/projects/villa-soal/villa-soal-03-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-03-800.avif 800w, /media/projects/villa-soal/villa-soal-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdAB4FAg3w3Xts0H3IsHAA/ueTSyIehDlwbHi49X8cVSEo2Ap68qozj8+Hd8z15cT/24GreCw0oWgSwOkXMAaLDd61HtXaJ53V/DnTx7TY4RLFHdPWVLwT0XtdrOTE8kN8u/hlI9nL3xYWoDXPlf0oKmwf3F3SNOhlrZyfpqsAAAA="
   },
   {
    "file": "villa_soal_04.jpg",
    "src": "/media/projects/villa-soal/villa-soal-04-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-04-800.avif 800w, /media/projects/villa-soal/villa-soal-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdIHGJ/gN84WFXU/9yTxt4HwXAAP3hBRkhaMgzzFNZrDEYKkIyhSMSRJR/YSfZWhO7vhwwXmGq2+1sEz5iwuh0P/QwANbIhEnyMHlZytWgQMC5ynlNR/5dexo9z+Syu20PFwVFlqqRPW5348eC7fVsbdCi2A6A+cMpl4MHyywdTbgzHSe011TkAAAA"
   },
   {
    "file": "villa_soal_05.jpg",
    "src": "/media/projects/villa-soal/villa-soal-05-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-05-800.avif 800w, /media/projects/villa-soal/villa-soal-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgZYJzIWV/uR7CTIl/Rsdem2MAAP7p2EdUCPpXb5mzwGwIffrtIHx/Rk/qxSHHPWbf5ixKR1e5gApL/NSQx/4TD7baBKb2Wr0+h2TZFhrvducgnOmMenBdjNYZKrQwVJYs3/TcKXde8hWUlRLPp6OpZrq1KEoeqzMJHi+WnhgA"
   },
   {
    "file": "villa_soal_06.jpg",
    "src": "/media/projects/villa-soal/villa-soal-06-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-06-800.avif 800w, /media/projects/villa-soal/villa-soal-06-1600.avif 1600w",
    "width": 4096,
    "height": 2304,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQAqoMPYpObFgfI6ARnlXBSgA/vQwZbvmCxtqQ5QDqP44Z/QD4+E/baeqk7LkYkjaGPifTiiP02nBSzZwnzqjBjKmFh/ppMYLwoKLJtu+30j9TzYwCEgE4+B1r7sZioRgAAAA"
   },
   {
    "file": "villa_soal_08.jpg",
    "src": "/media/projects/villa-soal/villa-soal-08-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-08-800.avif 800w, /media/projects/villa-soal/villa-soal-08-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZAAAPvA28IyVCY1rX7WAAP7c9I24O87g4OzBbEuvAk2pvGHwHa5QIF9b+ex9Ly2M9CFHAGn+Hfa+M/xNwyB8TiPNktf3FYQUroKTTs6LgAquyN59B18edQy7fLkG6pip746yqNXoFKJl8CW4fbo/JNBT3tf7I8lx15GdB0TOgz/AAAA="
   }
  ]
 },
 "orion": {
  "hero": {
   "file": "orion_03.jpg",
   "src": "/media/projects/orion/orion-03-6c331b8cb1c7-1600.avif",
   "srcset": "/media/projects/orion/orion-03-6c331b8cb1c7-800.avif 800w, /media/projects/orion/orion-03-6c331b8cb1c7-1600.avif 1600w, /media/projects/orion/orion-03-6c331b8cb1c7-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdEftgG76SLSaZhD1V6AD+wFEKJAwGSOIV0C0HQ+nD8migo7oMprz4ghBILWFIqXV/eP29Q8XHnprfVV617jkNq3WSBh82BwsNKpWKRfVu0L3z0aWG4NdOPL6a5pqG7B62D8WaatZS3Xs6yzv8QkhvjL76dRCq2D9+oOIAAA==",
   "jpg": "/media/projects/orion/orion-03-6c331b8cb1c7-og.jpg"
  },
  "pause": {
   "file": "orion_04.jpg",
   "src": "/media/projects/orion/orion-04-5b5275115ed4-1600.avif",
   "srcset": "/media/projects/orion/orion-04-5b5275115ed4-800.avif 800w, /media/projects/orion/orion-04-5b5275115ed4-1600.avif 1600w, /media/projects/orion/orion-04-5b5275115ed4-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOj+ABZgjw1DZoMOQYYwAD+pZAr11Jq/viDgYWUuGkv7wXaMAyUl4xOrKKCgyyv5g4xwE8RKu1McPvsNXxmIYuAwaAL8YRuRgswmU/5EB31DljsE862nOdVFPYG0C+FeLR6EKYAAA=="
  },
  "gallery": [
   {
    "file": "orion_01.jpg",
    "src": "/media/projects/orion/orion-01-ba64ef0d6021-1600.avif",
    "srcset": "/media/projects/orion/orion-01-ba64ef0d6021-800.avif 800w, /media/projects/orion/orion-01-ba64ef0d6021-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZAC7MoBOAbUMkMuBJHhGY8R0APk7sD+m07ujACs0Z7fXKUXHhK9o7lw1Q7GlKHtI80oqlaRA4rDHa3KP117AG7wX52rpLqMkKyJbfAzG2uLtuXOHeWb7L2AnI8bi7EylsbbV4qPAImDwlrUEp6Ir7jG8xP2yteEp3Nt9BnWReucXPAo+YbzFSB8LWdtN778m8T95iEH0kgAA"
   },
   {
    "file": "orion_02.jpg",
    "src": "/media/projects/orion/orion-02-dd4d721c6ab4-1600.avif",
    "srcset": "/media/projects/orion/orion-02-dd4d721c6ab4-800.avif 800w, /media/projects/orion/orion-02-dd4d721c6ab4-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZgCsICXgvhAg+eYO5ufZlpgAAP68dCTgGYl1kl1fLzZhWaEU3Ekwb1LAGA6+zFEgszryfxnHvw9vX0Ld0DaF/Z7prT7u2uEf9JREBZ8vVVGEWdtZ4DfPsAHnySqiLhJ+O2gAAv85UCJVcQumG9GwQV+3LHyJDkOdd40d8Nh7YXTDcGwe/DVFFFse52VUuLVKHo8jlGY3fS3drRAAAA=="
   },
   {
    "file": "orion_05.jpg",
    "src": "/media/projects/orion/orion-05-2923b9c131c2-1600.avif",
    "srcset": "/media/projects/orion/orion-05-2923b9c131c2-800.avif 800w, /media/projects/orion/orion-05-2923b9c131c2-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JZgCdAAyfTvxTFZtNMAD+zgHWDayWUVuSmcB1nuwNXNZFK3aWt4/trwEY3mOVxN2HjIakJjuk0OvZqeMp9pMRl3YSJVnX82LLDwC2u1BohFudNXOz21xLJB51BLjAXklrBBzjr7SuTEGMKfN3nfzvoZIqUMgCh6QIq4ZfHFCN2vC5eAAAAA=="
   }
  ],
  "card": {
   "file": "orion_01.jpg",
   "src": "/media/projects/orion/orion-01-ba64ef0d6021-1600.avif",
   "srcset": "/media/projects/orion/orion-01-ba64ef0d6021-800.avif 800w, /media/projects/orion/orion-01-ba64ef0d6021-1600.avif 1600w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZAC7MoBOAbUMkMuBJHhGY8R0APk7sD+m07ujACs0Z7fXKUXHhK9o7lw1Q7GlKHtI80oqlaRA4rDHa3KP117AG7wX52rpLqMkKyJbfAzG2uLtuXOHeWb7L2AnI8bi7EylsbbV4qPAImDwlrUEp6Ir7jG8xP2yteEp3Nt9BnWReucXPAo+YbzFSB8LWdtN778m8T95iEH0kgAA"
  }
 },
 "la-montua": {
  "hero": {
   "file": "la_montua_02.jpg",
   "src": "/media/projects/la-montua/la-montua-02-1600.avif",
   "srcset": "/media/projects/la-montua/la-montua-02-800.avif 800w, /media/projects/la-montua/la-montua-02-1600.avif 1600w, /media/projects/la-montua/la-montua-02-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoYAA0APu1kqU4ppaOiMAgBMB2JQBOgBB0vz8LkB3enG9QAAP66Zi4cyMfitHy8mEHE3Ev5vMTWZ7vf+O0eTM8vwyLdhOrpcDZlXcTdTKpo5sf9ld2JwAvHZSbsPDVukhoAcOySGPYoagvlxrnRK+Lll7ZCn1jMI1IRs5Eough0j+AA",
   "jpg": "/media/projects/la-montua/la-montua-02-og.jpg"
  },
  "pause": {
   "file": "la_montua_01.jpg",
   "src": "/media/projects/la-montua/la-montua-01-1600.avif",
   "srcset": "/media/projects/la-montua/la-montua-01-800.avif 800w, /media/projects/la-montua/la-montua-01-1600.avif 1600w, /media/projects/la-montua/la-montua-01-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUABbKfbbtMhQ90L2DwAA/tYNIAXQVJstr/zh8sfvL0VtQhiV8HjflUUhsu81irF0Bf/w8QZF4lRdv7ijXGHsuPey+39qsDTvxdiWVsQnmz0j+fsgM8OpM74gVKAxEXISAveq5CAA"
  },
  "gallery": [
   {
    "file": "la_montua_03.jpg",
    "src": "/media/projects/la-montua/la-montua-03-1600.avif",
    "srcset": "/media/projects/la-montua/la-montua-03-800.avif 800w, /media/projects/la-montua/la-montua-03-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMoACfdMsyRVb8L+PjoAA/tPktqY/HOubm7nERlDl+NMMIu0u33TrahPOE36o2S1+ZJLlUOPsaiBK/DH7Qqs4yJkwKz71+wA8q7xyUt3MXi4FMbB3oPg+rz5xZGwl23dyMoJFEOeOP2+xeGudUQwbZLsHcCx2yiI1IGZ+SfgAAAA="
   },
   {
    "file": "la_montua_04.jpg",
    "src": "/media/projects/la-montua/la-montua-04-1600.avif",
    "srcset": "/media/projects/la-montua/la-montua-04-800.avif 800w, /media/projects/la-montua/la-montua-04-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMipgf4D6K9dctA6aKJevAAD8iPh67Lp9Rq2i4VjHxsvFGFrh0AafLKByKlzkwxEwvGhdy2SK7hQzm2tZZdj45qnBGEt8bAOn1BtCFXPFyc9nJopTdnt86MR/Us9lSSwg+tOLAUlcTy0+YYCORHlPZRIYRwHwvxnmYtHAAA=="
   }
  ]
 },
 "villa-alcala": {
  "hero": {
   "file": "calle_alcala_4_02.jpg",
   "src": "/media/projects/villa-alcala/calle-alcala-4-02-1600.avif",
   "srcset": "/media/projects/villa-alcala/calle-alcala-4-02-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-02-1600.avif 1600w, /media/projects/villa-alcala/calle-alcala-4-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCxAkAbn+AozSZUJoZKC4UwAP7Q/1hn7XjjHO286zZOKHNdegdsPQg9zMLQ+Pe0HTYYSaaBpbWwO0CAIZpCeHLz6QfBPm4C7kNuQFiJZiMkLxJAMBai4Epm9LbohRAPGEiY/upEA3bpa8evntXAj7mAw25epxKHj9HQAQ9lsQAA",
   "jpg": "/media/projects/villa-alcala/calle-alcala-4-02-og.jpg"
  },
  "pause": {
   "file": "calle_alcala_4_01.jpg",
   "src": "/media/projects/villa-alcala/calle-alcala-4-01-1600.avif",
   "srcset": "/media/projects/villa-alcala/calle-alcala-4-01-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-01-1600.avif 1600w, /media/projects/villa-alcala/calle-alcala-4-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdMoMxgBKmke467bFGAAD+6f/8u7PqEDZRfChNygMy4wntH1L/pzvI7VjQyO3t3erNeMZ1O8l6+s9ueupT2ipEx+2HlqzZpPfNsIoVfO19VOHW5hWIekgE4/KQT+XFvGdwTcM6UlpTeB7pZwpcRyxsAAAA"
  },
  "gallery": [
   {
    "file": "calle_alcala_4_03.jpg",
    "src": "/media/projects/villa-alcala/calle-alcala-4-03-1600.avif",
    "srcset": "/media/projects/villa-alcala/calle-alcala-4-03-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgMY2WZaKf9L8p6kYQAP6hRkDg2ljtMJDiDn2vRB7vVNfAaorAODHY86klXTIogeqToCaYHmwqRpgsOOqejXtVGERvMYsgO3mISa1HL8y7VIQ4sC5GUH9/aIL0Ycvz/qHNCjo3RhCKUpN1NI0vn/kMO4zd8xN9lYzofemn5Av18VLiAAAA"
   },
   {
    "file": "calle_alcala_4_04.jpg",
    "src": "/media/projects/villa-alcala/calle-alcala-4-04-1600.avif",
    "srcset": "/media/projects/villa-alcala/calle-alcala-4-04-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOkBLhgcavJiGB+o1PIcAD+sUWbLW8eEu1T7uMfi3a8+geG8AW27XnB5bwFJpnQYwOCVqDoGSkKvcZQgBv/zZOaMd2obIS7iEQrnEgKFMMtC9N5eYL3J2wQwHw6CHM22onah4zfjt79lZNvmJpIU5J9vtVqgMysAA=="
   }
  ]
 },
 "villas-in-the-landscape": {
  "hero": {
   "file": "parcelas_p8_14.png",
   "src": "/media/projects/villas-in-the-landscape/parcelas-p8-14-1600.avif",
   "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-14-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-14-1600.avif 1600w, /media/projects/villas-in-the-landscape/parcelas-p8-14-1874.avif 1874w",
   "width": 1874,
   "height": 839,
   "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JYgCdAYv+7Ut5lRzkHfeQgGcoAP5oTyJMd3eXdhTtMMtHcmYe4y5pSu/ykUvpnQjrPWSXiL5r6OPJebDe8gAbmzJWdagEHbPeXuDsGNLyKDQiLGet0GVD6Sh/T4zXGZCuE/OA8oWI56Z+3aF9PSK753pCPRj7OaFXLzKZ5TIz+QgS6bjKpAAA",
   "jpg": "/media/projects/villas-in-the-landscape/parcelas-p8-14-og.jpg"
  },
  "pause": {
   "file": "parcelas_p8_01.jpg",
   "src": "/media/projects/villas-in-the-landscape/parcelas-p8-01-1600.avif",
   "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-01-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-01-1600.avif 1600w, /media/projects/villas-in-the-landscape/parcelas-p8-01-2560.avif 2560w",
   "width": 5332,
   "height": 2771,
   "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JZACdIF5J/gPGSKtshYUy1x8JEAD+W9SWq0FYjrsysPB745czDMh+XFrtSg89lOg7vjdMRprTwjPkG7CeJ6dxfA2aUwgw30Bo77FxGy+UFWyDD8sYhdixbGYfsbrs3oTHkNIAAAA="
  },
  "gallery": [
   {
    "file": "parcelas_p8_02.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-02-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-02-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-02-1600.avif 1600w",
    "width": 5464,
    "height": 2860,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoYAA0APu1iqk2ppaQiMAgBMB2JZgCdEf/gPJPO+a8kel9oqAD331AeEJhhNRa4BPMfIdj/NMpjwOCxEO9BG2qeeDoJ/I3raaC3v7guKkP0yEEmvZ+1TSMwEwsEYMgAAamABtEW8lu9md8Oig0PfUub07u6UGBQIDo1ZtDyYQm4Oa7QTJAAAA=="
   },
   {
    "file": "parcelas_p8_03.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-03-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-03-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-03-1600.avif 1600w",
    "width": 5464,
    "height": 2920,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMoCGeCAUDFDh238Kelr/AADr74HlbcYQSAVLcc57G3aUeXHKxX/UHAj6Z4JxjcyBgeLkCYxGYjW0+Gz7qj+tYQXppnOppeOL2WaJ/LWe/ke8qUQSKKILCXNCAAA="
   },
   {
    "file": "parcelas_p8_04.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-04-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-04-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-04-1600.avif 1600w",
    "width": 7796,
    "height": 3228,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYAAoAPu1iqk2ppaQiMAgBMB2JYgCdMoACJJHwcFLXs2V6YAD+feChmNSwEQHL3uITHz5Y7hxa8kZYlfLZMrscx04Ev/zGw3ZI5umGI1OkYkq/E/f+TnrBIrn7tGwm9IwRiQNE938AN36J9FQKeCUq9tNPkAx6AesKBcOiA21Z10firLlhYAAA"
   },
   {
    "file": "parcelas_p8_05.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-05-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-05-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-05-1600.avif 1600w",
    "width": 7932,
    "height": 3172,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoYAAoAPu1iqk2ppaQiMAgBMB2JQBOmUABWu3+JUjTbBeQcvUgA4nZPi4pAhbT8QTwDL7TW6del/MS1p6Ikxq27XDoy7dLVoUFsZT/5i0z9Jmva3X27d/lzTLHSlUsfApUDVobRDsIVOSJoFhITiuj+fZUqPs8kcCtT+jWox8oDhOMBBAAAAA=="
   },
   {
    "file": "parcelas_p8_06.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-06-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-06-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-06-1600.avif 1600w",
    "width": 7096,
    "height": 3548,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JYgCw7B6t9/0LLNjHPzNTAADeU5sI7qHKRfUIVonfNjuZVE/hsIz9AtdgRkxvf9ux57d9kpSB/BhAzaLS3GpzXFYQSVFg06T9HleBvtpXU7e1Nj+AmOIIqNKkl0l5XjizW98/dNsTbmnGhqPLJZwZwJChTAQqMSf3BtKITAafJcjQAAA="
   },
   {
    "file": "parcelas_p8_07.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-07-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-07-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-07-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUAS4ow+W/Kz+hwAhNF9gAP6F32kVzuJ5YFC5axC0WcmYaGN5c9DAOl32WZth4iD9CzHhpXGVEkjPKJjHCgvlE/JeERs4uqb3GBs8gspiidlxH29A32vOJFIQK9DfoLUuT+ERCoVaHwIAaJqn51Ja6P1oqVZ03KB8QJ7+7n4wIuAAAA=="
   },
   {
    "file": "parcelas_p8_08.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-08-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-08-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-08-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMoACsgdqn67lOnS9OpwA+orejjfXbMmGqprk08orDgBFxl7xfiviW6CEfle5ScZPYAUxuidW4yU3ULJldulB4Hv6/kC67h6Xq+SkHUD4oNq5/aWq/LOvmnMuW0UjydQTaQ+hvbbIyk4KQ0Arg4uLuKXOHr6ueOHTjgwwxnQLtvRPAAAA"
   },
   {
    "file": "parcelas_p8_09.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-09-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-09-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-09-1600.avif 1600w",
    "width": 7436,
    "height": 3384,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JQBOgMYdWhkCnRLr1v8fpZleAAP13m57BPZ0nHXRfjQdQgpk2lshy4RMPkjSCXb1+0dLuH40qZr/awUt2nDYGVk3I2uQW8yud0Sbsit6eh+BrE6YvdNewyxsP88Rjm3Se5/dgPtWQQCyeGzwEV1o7omN4eYQ5H2HPGxG7PAAAAA=="
   },
   {
    "file": "parcelas_p8_10.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-10-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-10-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-10-1600.avif 1600w",
    "width": 6948,
    "height": 3624,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUAS3wwNZ1Akze3jHp6igAAD9UEQRe6Y6BqoL4WGLTXJKzbM/cd3ysLzCTpS7P3y9p6FuwJk/DKY1++MzY1lv5DwL4fTY8CtA4tUiCOZ0kViad1+ZH7Hh4ESFt1MvVcNQ1/zvLx8NG6q50kfbOVj19Khsa7WHnyWEZU3vLvEAHRGyBc9hC9lzbgAA"
   },
   {
    "file": "parcelas_p8_11.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-11-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-11-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-11-1600.avif 1600w",
    "width": 7376,
    "height": 3412,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JQBOmUAA6C+lAWyao0AUtAAD+v6Mj4KKSoueocFfZMAqHJW1B2fPsvnrAfr8hPHHmnVJa6R/E0xkJrLrOG+/3vHQyj8S1MhX59Kz3feDK9EhGDmKMX2Qb1MsFuVPch+735qIVU1deVt3jwqPDNTw77vzvC+cZL6XoyiXtBcAAAA=="
   },
   {
    "file": "parcelas_p8_12.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-12-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-12-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-12-1600.avif 1600w",
    "width": 6756,
    "height": 3724,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoYAA0APu1iqU2ppaQiMAgBMB2JZACdMoMzGDudDyfp/JTf1UAA9Au+8kjurrq4Vy90u5akPOnfrRrMsQKsFMHqJDUGjUxAnlXAOSn0AtGeK8aiX0S+A3aTrSVXCX6q7YdgsBeeEsz0wna02JZjBlifKu50Vb7RvqHgE/1IXWBwX/Fs/+tM/DDo5SAAAA=="
   },
   {
    "file": "parcelas_p8_13.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-13-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-13-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-13-1600.avif 1600w",
    "width": 7504,
    "height": 3352,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBACdASoYAAsAPu1iqU2ppaOiMAgBMB2JZgCdIDZC49Mm8N8DcivNzgAA97HH8sG4b6bayFwqYVx+LKtjqdADeAXTaHHaY8+ah7bDiPgiXFx59ll0g2PAsdTg4FweVStRaEi0U7ZV/jdTvl/9wh5lhlOZ2bEgPhyoofGfavwRb4Wxn9NhGADtSduhSyNAAAA="
   },
   {
    "file": "parcelas_p8_15.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-15-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-15-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-15-1600.avif 1600w",
    "width": 7500,
    "height": 3356,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYAAsAPu1iqk4ppaQiMAgBMB2JZACdMoADERPd2xs76Kv4am4AAP6FnrnFzSuSbn18C37Fl3GKufFjqW4fArLgm+13lVevVMzW4TiLElFDCQeWYhmz5ojw7zXYJ856qfUIAKF/vM1FwYYUIXQJOqXp9mxkxbOdQvdmFtKBPfutx5gLZei6/7AYMUD21jQIQAA="
   },
   {
    "file": "parcelas_p8_16.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-16-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-16-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-16-1600.avif 1600w",
    "width": 7520,
    "height": 3348,
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAACQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JaACdEf/i1+m9I2MgbCnopfYXMAAA+OTvYuwOgvyuM2/JtRCdLePN++YWRacwOKZTrldahCSnn2HHYXL6nQuxyLtB5RsdT3UIVSGcG6Uc6e6wlaMkeo5V+26IY5Ks8CcE8OzIfDzCbH3Td47+xWrl1C4W2U7bfAitQy61nNY8gYD1updlxL9yfuVrUGM0v26TVAAA"
   },
   {
    "file": "parcelas_p8_17.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-17-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-17-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-17-1600.avif 1600w",
    "width": 7492,
    "height": 3360,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoYAAsAPu1iqU2ppaOiMAgBMB2JZAC7Ef/gPppTh3rKU63hAJbqWAD+fnNeC/IHZ0R7o2cbAv9UE7xS9miVfQtIy3q7mQSnkQmMB26K5m+sk4N22PvGrVu0e1iDyZWtk4+8BpvBfzgHyV6E/f44T6zxqZY5NpQaaHSt9cseb/8KQQe5O06exfxcMMGdof5LmrFK/IPFYAA="
   }
  ]
 },
 "the-villas": {
  "hero": {
   "file": "the_villas_01.jpg",
   "src": "/media/projects/the-villas/the-villas-01-1600.avif",
   "srcset": "/media/projects/the-villas/the-villas-01-800.avif 800w, /media/projects/the-villas/the-villas-01-1600.avif 1600w, /media/projects/the-villas/the-villas-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgMX/Wsd8BfCRGG4Vv45nYAP5m3aaipMNIxz+KwznClq8tSuEooldnJmGpeOocaXJ2ZD7zherITTeSHxcCSB6dogCZhFkVb+78LjJiXwPVOozc0t+91SnTvuP2T168cAGxS7Vbq7zTulz6tSRptfKP3qeVT1uRLkt8Jt+YH3whFhKVOFXIkEGBMQAA",
   "jpg": "/media/projects/the-villas/the-villas-01-og.jpg"
  },
  "pause": {
   "file": "the_villas_06.jpg",
   "src": "/media/projects/the-villas/the-villas-06-1600.avif",
   "srcset": "/media/projects/the-villas/the-villas-06-800.avif 800w, /media/projects/the-villas/the-villas-06-1600.avif 1600w, /media/projects/the-villas/the-villas-06-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoYAA4APu1kqU4ppaOiMAgBMB2JQBOgBD0TmgOKq4t6xZHl+AAA/rIHqqq5I4PA6tt+sV79jqCTs8eBkoVVLcOVmVDYvuZUvqfq9w7lBPqy/kbkaDg4Cr7QGg6GQWWjFjSkBQj1O2fpszDAWEMFCuuoMkcZ5l1y9Xm742qUoIQZpjd1dY4AAA=="
  },
  "gallery": [
   {
    "file": "the_villas_02.jpg",
    "src": "/media/projects/the-villas/the-villas-02-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-02-800.avif 800w, /media/projects/the-villas/the-villas-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgMY7cC0XKjsFoDrNEVs/HOUAA/lv87e1JqRHFwKGQKIkJMQUv/pIL9yVPGWTKfMUiqxuPOMFq13iXKVEM7elxPRIDuxB69fzvLwNQEjos/J6Hy102c8jfzSvvEkPbI30th3xbOozFDqwDzwn8Lf9QtSx1fOCK5+dd2f1NSYqtQYLdqDBeIWkZBAAA"
   },
   {
    "file": "the_villas_03.jpg",
    "src": "/media/projects/the-villas/the-villas-03-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-03-800.avif 800w, /media/projects/the-villas/the-villas-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdMoAlwxfNQ5c8OjVO3VezsQAA/u2dj/kOVW8scu2or4bZ1NTFytey5IF/UqkGmtL6iYBjm9OtY7hGVnu0z503rOojaLhbDCsCQt+1T3+8L19Zw/IVGG6q28IXbjuUdmtLhinP/v9ugPV9DsbkAJhhx9t6wj7KLBGNt9HtBztmmazmsZsTEat1zzNL6cAAAA=="
   },
   {
    "file": "the_villas_04.jpg",
    "src": "/media/projects/the-villas/the-villas-04-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-04-800.avif 800w, /media/projects/the-villas/the-villas-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdABdL6+pRASeyU2xdywAA/urbikPr1G9Se5kcmtuThs2NuKqftFZ9a/aaKXTAjXgHyzS6CTlX4bWhGfNMsvNXi5mtuDqJhsfZdLByHDFek2qbO+gBPLchBmQdV8tJXtx/S4gOL2CGQ+4glMukLHUeQOSACATWz8HWLgSAAA=="
   },
   {
    "file": "the_villas_05.jpg",
    "src": "/media/projects/the-villas/the-villas-05-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-05-800.avif 800w, /media/projects/the-villas/the-villas-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQBdgA3AjXmXR4U/Y7UEeAAD+79eLWfLdcSxuH/XK1jiubfmsT6I+bqaOQ9spgiRq61TzdIh7f+HAQc7TfHkhtxGSrTIX1se91ilunz8epmXMpvxFwq2oAbhTcHAdugFlw+fPzHCJl1Bgt2oMGC8LEl8JydQmgAA="
   }
  ]
 },
 "altos-de-los-monteros": {
  "hero": {
   "file": "altos_de_los_monteros_04.jpg",
   "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-04-a53388764f62-1600.avif",
   "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-04-a53388764f62-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-04-a53388764f62-1600.avif 1600w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-04-a53388764f62-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdMoMYBsADEdpnAwi+e7x5dAgHAAD2tTCxK+/prOocUbT1l6NH59LthI0xDrb6cvPgrh+8oVLyD1lE/+6XoT9sfbebYfGOgRpwUDVUN1Y2/0NLjKhTi2BSoLgkdsYxagYCcKg5bGkE6JMaTr1ddkq/kR29c1S/Jxg92OoAAA==",
   "jpg": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-04-a53388764f62-og.jpg"
  },
  "pause": {
   "file": "altos_de_los_monteros_02.jpg",
   "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-02-399703149232-1600.avif",
   "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-02-399703149232-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-02-399703149232-1600.avif 1600w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-02-399703149232-2560.avif 2560w",
   "width": 5472,
   "height": 2918,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoYAA0APu1iqU2ppaQiMAgBMB2JYwC06CHhQhsVJbFHx+IRkbQAAP6B80s39nPSzkLTTNnE0lRIv2DVW8sLkF6qsZcRooe7WaThA7wjUx9vGjXJwCBHuEVq9Xow9Wvm9lgdrmb3ubMZkW40GfPufj9ngIkYl7LcDdUIj7WywO0gI5XxQRJBzgAA"
  },
  "gallery": [
   {
    "file": "altos_de_los_monteros_01.jpg",
    "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-01-6fb1160e8e05-1600.avif",
    "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-01-6fb1160e8e05-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-01-6fb1160e8e05-1600.avif 1600w",
    "width": 5083,
    "height": 2523,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JYwCdAB7HfrC+1CK+W4Cg39AAy01y/kqn85c8n29KOC6iCNFvbav5Fwzx9r/a7MKsRT3cMv7nAPQHj/8UCRmyBfVzQ0SL7+pvDB2+NmuKhW/+8GGF/D/dby1j0ybEtcyyQRVnVJblOB8L+wAAAA=="
   },
   {
    "file": "altos_de_los_monteros_03.jpg",
    "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-03-31d998be0d05-1600.avif",
    "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-03-31d998be0d05-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-03-31d998be0d05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JaACdFkAbn+LX6aqO8zkxcD1pN/9s4AD+5/h4N82v+/Ect4SdAwfHssSSmfQwY0dFCCB5FvmAqlwBX6r2g4sqRdm7BaH+CVZ5FKx6rI8Jwqh2jMvTBJn1dv8khlVih5oWSk8d2apxjKtruycofQHUcwem5KpDLVlV4RVswQyYwDidkHVtGiUayUAAAA=="
   }
  ]
 },
 "villa-feliz": {
  "hero": {
   "file": "villa_feliz_05.jpg",
   "src": "/media/projects/villa-feliz/villa-feliz-05-cdd5692be632-1600.avif",
   "srcset": "/media/projects/villa-feliz/villa-feliz-05-cdd5692be632-800.avif 800w, /media/projects/villa-feliz/villa-feliz-05-cdd5692be632-1600.avif 1600w, /media/projects/villa-feliz/villa-feliz-05-cdd5692be632-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADQAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JQBOiP/wEox2L90iH71AA/Pj64SaamHgUU+mgj6/crmxubWKYtIJLOi3HEi89fjp86uF7terckyAPk/NlcFom3AxNh2ppdWypuB7v37m0JDkFLXqZdR1L+bWc2L9VoLsFtG4jukNwasvQKO5C16ucKmSv42Ga0ERquZXEgAA=",
   "jpg": "/media/projects/villa-feliz/villa-feliz-05-cdd5692be632-og.jpg"
  },
  "pause": {
   "file": "villa_feliz_03.jpg",
   "src": "/media/projects/villa-feliz/villa-feliz-03-0744b928816a-1600.avif",
   "srcset": "/media/projects/villa-feliz/villa-feliz-03-0744b928816a-800.avif 800w, /media/projects/villa-feliz/villa-feliz-03-0744b928816a-1600.avif 1600w, /media/projects/villa-feliz/villa-feliz-03-0744b928816a-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdMoMljEwMIWYhdS3Oq+DzvPAA/l8rjEQCkW/Kb9PNpcUvDDOrMGA8E4F+XcEpAAmChBZn9wprOz1F0l7naS7hV2dDgJRh3MP67GQdbjv5pNo4VVULwM3xKCaZMzjs5Ui7ARqDqmvvxgEM6aey5SRjM7tuhvkof4E6ZNv4HPb43l75VXylhXmXIOl23tsoDTf045AAAA=="
  },
  "gallery": [
   {
    "file": "villa_feliz_01.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-01-eb25e20ffb54-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-01-eb25e20ffb54-800.avif 800w, /media/projects/villa-feliz/villa-feliz-01-eb25e20ffb54-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoYAA0APu1iqU2ppaQiMAgBMB2JYgCdMoMljERXyO5+8pgn1dXnqAD+5RV46xkml0eRFEVYJFfQAissMln+0JONd76v6SL6Vf9sUdFYiLDmF6q2Pwt3T3bxaq9z3ixdfdpBNWb/I3v6Ny4C7VzAKxEfIyVusQqP60Pg3xbei4H/EHLaAxIu6qda0Qxz6wAA"
   },
   {
    "file": "villa_feliz_02.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-02-107932ef6143-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-02-107932ef6143-800.avif 800w, /media/projects/villa-feliz/villa-feliz-02-107932ef6143-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZAC7H8ACNjewxMXq4a2tgAD+wDmdJegLxd+EefKG7sN2z0xkyTBM0J7TtuOrYDkyquCKX0Ko+pV+k6ETWiDlp+co8H43cevGjfgEOGYiSkNHF5VJGnDc70filbjGRml+cJjq5aOmvmNhSDWlU2oqYmfo8dTRYPbFrWAA"
   },
   {
    "file": "villa_feliz_04.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-04-604a973c908f-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-04-604a973c908f-800.avif 800w, /media/projects/villa-feliz/villa-feliz-04-604a973c908f-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JZgC7AB4/FojSrXpAAP7pRL5N5BOpmDu/td+IplSW0bSqOkI3su2Eqg7ooRbvZEYoOsshVTOOMMa2RM8wZ8c1DulNOdtMD8PFc12kC9KjTy+dAPNPi7uelFQr+TRTpLXWQUeJom78q62v2XwYAAAA"
   },
   {
    "file": "villa_feliz_06.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-06-08dd33a86934-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-06-08dd33a86934-800.avif 800w, /media/projects/villa-feliz/villa-feliz-06-08dd33a86934-1600.avif 1600w",
    "width": 6688,
    "height": 3760,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOgBFZ0cwmFIaUKuwD13UQAAPuk9mHPw1zDTuriuxQp6pNHO/saZ/fbKcFEK+yBLHmhpuOr64mHagybT44EgTG3frUIbyUT/H7vwRqrz2e92AJI+61ppegw9bLbmXva2l0bWPfVlsM182fv7yhpJ64OIGM0lkBRHJ4dY65p9hjqJ3FAAA=="
   },
   {
    "file": "villa_feliz_07.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-07-f0e455adf010-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-07-f0e455adf010-800.avif 800w, /media/projects/villa-feliz/villa-feliz-07-f0e455adf010-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUABp0cC+oWAms8Uf/6+AAP7l9TLVD97jc9evn7KbCC2q9+NmmCg7KkMa+Qy/KBh77+ZdhV6s/+aP+Londcs4gG5aOnp+ndQx6Z/cwWasgAv+zbAcA1+YbcUyjwYALLeYorMVI/wN/iwaYAGICwAUswwkgAeNkERMuy/gLuKAAAA="
   }
  ],
  "card": {
   "file": "villa_feliz_03.jpg",
   "src": "/media/projects/villa-feliz/villa-feliz-03-0744b928816a-1600.avif",
   "srcset": "/media/projects/villa-feliz/villa-feliz-03-0744b928816a-800.avif 800w, /media/projects/villa-feliz/villa-feliz-03-0744b928816a-1600.avif 1600w, /media/projects/villa-feliz/villa-feliz-03-0744b928816a-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdMoMljEwMIWYhdS3Oq+DzvPAA/l8rjEQCkW/Kb9PNpcUvDDOrMGA8E4F+XcEpAAmChBZn9wprOz1F0l7naS7hV2dDgJRh3MP67GQdbjv5pNo4VVULwM3xKCaZMzjs5Ui7ARqDqmvvxgEM6aey5SRjM7tuhvkof4E6ZNv4HPb43l75VXylhXmXIOl23tsoDTf045AAAA=="
  }
 },
 "bleu-royal": {
  "hero": {
   "file": "bleu_royal_04.jpg",
   "src": "/media/projects/bleu-royal/bleu-royal-04-1600.avif",
   "srcset": "/media/projects/bleu-royal/bleu-royal-04-800.avif 800w, /media/projects/bleu-royal/bleu-royal-04-1600.avif 1600w, /media/projects/bleu-royal/bleu-royal-04-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOkCYhgY9M4aqoiqOqkB4AA/rI9wB7e33i2GLfhKHpEmGQoE0E6DDoGQNKgJ/Hvpf3fCMIM72DTOhc4Se/vSfEBqpxFyB1vQIE1EcczFo6PY6usjeEbDNAbJENCLovAPlYECzlfR/jp9e/bNocbPeWneAAA",
   "jpg": "/media/projects/bleu-royal/bleu-royal-04-og.jpg"
  },
  "pause": {
   "file": "bleu_royal_03.jpg",
   "src": "/media/projects/bleu-royal/bleu-royal-03-1600.avif",
   "srcset": "/media/projects/bleu-royal/bleu-royal-03-800.avif 800w, /media/projects/bleu-royal/bleu-royal-03-1600.avif 1600w, /media/projects/bleu-royal/bleu-royal-03-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgC7AdwLg7Tk+mDb8JJFFtul3TAAy0xe7wLfnJytCmROnUvOjuyVxcxPzIj+86nXyoRbSd1SNIHd29pF3XqoRUw2cRdYkG6SVDl/RLO6rYDepszFO1Zh4G5v+wBvwI9fxENSh+6ATzdNtHJz2HXOIKkNjOXiNw/qKD5ybexGM2aV2Sf9tKFOwAA="
  },
  "gallery": [
   {
    "file": "bleu_royal_01.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-01-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-01-800.avif 800w, /media/projects/bleu-royal/bleu-royal-01-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCdAywYYA0GeS+3bUPJ7wjcAAD+s5IVvuUd3iP2AVd0182xVERopJODewuJ6oNQ/CWrUYRfxYAgKRVsNmIfLhNEQHLKo1td+X+8XbuXYKKFEA/WagKK5McNISqghNHWssMtOMkH87w8onjOzpAQ9qMvAAAA"
   },
   {
    "file": "bleu_royal_02.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-02-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-02-800.avif 800w, /media/projects/bleu-royal/bleu-royal-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQBOmUGQ/T/i1+hFd+Bc8OfAAAP6zTyRdCYpo49XcahZF2xyPQvqrEl0f8YD1vZeCs0PGZtb3x80VQTXFDUQNNKIOG8onV4aWKZkdX0kuPDXuw2bLHfoWcMYFi7/3dGcdw6dlgEX/qGdW4570lcshcKPPf9dMiETCpapWkBHR06hkekp7rAAA"
   },
   {
    "file": "bleu_royal_05.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-05-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-05-800.avif 800w, /media/projects/bleu-royal/bleu-royal-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgAt7bN/d3HbuIy2fAAM2hYVJWDC/2N2bN8WbLhp4b2A8sRHkjjj9mH2hSxHUIZvhV9+28qgJV/lfzWaVDG05H/snsgnjBirOZJntwpe+epdGOnwWWaAb8j5Kyg42Bitm3FQIaDT5nkSf8UQz061QwCUMDWDdP720jPb762VuSHIyTx6zWKAAAAA=="
   },
   {
    "file": "bleu_royal_06.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-06-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-06-800.avif 800w, /media/projects/bleu-royal/bleu-royal-06-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdACD/OK/v+2jq/LkgAP0rSbla2ex8zfE6ta2DqaO2/M6fKHeh4/X3ftW58qH9h2Nwvt8AKC35nedEAfpv5Fm96WpKqsS4o/GE6uesS2a1aGsPSo2C31Ftp6LP7DVyoWT9H/N6XvKhjwnJm443xk0tGfic6B1AAA=="
   }
  ]
 },
 "alcala-solvilla": {
  "hero": {
   "file": "alcala_solvilla_02.jpg",
   "src": "/media/projects/alcala-solvilla/alcala-solvilla-02-c6bea87d883d-1600.avif",
   "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-02-c6bea87d883d-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-02-c6bea87d883d-1600.avif 1600w, /media/projects/alcala-solvilla/alcala-solvilla-02-c6bea87d883d-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQAwCdASoYAA0APu1kqU2ppaQiMAgBMB2JQBOkERhmGXKqBm5+KrgA99mIG2WNqcqobIEr1r1Zj+7qIe/gDFhXvVHO23MPbVPUQfAQAbXj1jzRifmXi9kjBiyrNs1E3K27qK3bblyZaoOlDPeroOl9bBc7aQWcfWcIU0AYXq7wTZt8If5QvMAA",
   "jpg": "/media/projects/alcala-solvilla/alcala-solvilla-02-c6bea87d883d-og.jpg"
  },
  "pause": {
   "file": "alcala_solvilla_06.jpg",
   "src": "/media/projects/alcala-solvilla/alcala-solvilla-06-ea7917776ebb-1600.avif",
   "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-06-ea7917776ebb-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-06-ea7917776ebb-1600.avif 1600w, /media/projects/alcala-solvilla/alcala-solvilla-06-ea7917776ebb-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUGYW6Qw5U7U/mJBjnS+z0XPAAP3idn+GHdqW+H3TZ34yu8TyovgU11TP+tkpqxU+8IhC+1CS/AoXNuurtvMlokLVOZd+n1B1g2x3wEn8/lEvDVbgaxcKkBka245fQpxzJ10dfhS/aQnLsM3yCymfQ/9x6HDBcuuqAAA="
  },
  "gallery": [
   {
    "file": "alcala_solvilla_01.jpg",
    "src": "/media/projects/alcala-solvilla/alcala-solvilla-01-d045cd4cb294-1600.avif",
    "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-01-d045cd4cb294-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-01-d045cd4cb294-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JYwCdABVYGEaz42X0pIYYAPR3H1XGeKpYc+g27JisHSy+TGVZFCofLgRE2PWyETkDZOrdWEJCKoOmeGnfXxcwAVnWoBv7TcBnqJrOwKh9HHIMKyk+IJvQFOyj/+MmAL1PhDCrLGEKQwJWxw9FUZT4DUsf5IoFSmWC1+L0qsCNI0bXQAA="
   },
   {
    "file": "alcala_solvilla_03.jpg",
    "src": "/media/projects/alcala-solvilla/alcala-solvilla-03-a4458dd00190-1600.avif",
    "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-03-a4458dd00190-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-03-a4458dd00190-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwAwCdASoYAA0APu1kqU2ppaQiMAgBMB2JQBOgAnh7xHoj1JGMeADeQ27itqmotOVRnyb90NkD8GHMsa7Z1SoYIr6hQA7OtMZKBVCK83MzZ28GmmsbV2mXSLYRI6VWzjxnduW9YJJNQk6o7Ynh37afba47Fy71TADpJOYoYas0AcxRgivxAAAA"
   },
   {
    "file": "alcala_solvilla_05.jpg",
    "src": "/media/projects/alcala-solvilla/alcala-solvilla-05-f6edc40d2e26-1600.avif",
    "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-05-f6edc40d2e26-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-05-f6edc40d2e26-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOkBshDQfOqMDVKcToQfAAA+N6WDVykFzSAgzd9xZeTuxriRCgE4pJKnc7/oaEynpGoNEkVssBOGnXRSAq0VUksxuDMp0Q5xzWUGrXm8rViSJgWkVcx3dqL7mnipitkT+Gx1ok+6wabS6NzrGFKtA1MUIRQCf3xO8EZlE0AAA=="
   }
  ]
 },
 "elviria": {
  "hero": {
   "file": "elviria_02.jpg",
   "src": "/media/projects/elviria/elviria-02-4b79b1575977-1600.avif",
   "srcset": "/media/projects/elviria/elviria-02-4b79b1575977-800.avif 800w, /media/projects/elviria/elviria-02-4b79b1575977-1600.avif 1600w, /media/projects/elviria/elviria-02-4b79b1575977-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADwAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOgApSdGF8DFqgeLoIAAP2uyUfwgw0C04i8CcsvsPPin3qn9RWVHmRC6jepgpt5PhPBpPnikYmr1gvVSbFJ8JUprjA8fMXNzw86Cb0eRTIA2OBt2fiyQ4ixZqxWZ+n0pM4bIX6+cZW5/AAwgjjIIWyFwAAA",
   "jpg": "/media/projects/elviria/elviria-02-4b79b1575977-og.jpg"
  },
  "pause": {
   "file": "elviria_01.jpg",
   "src": "/media/projects/elviria/elviria-01-848699a9fdd5-1600.avif",
   "srcset": "/media/projects/elviria/elviria-01-848699a9fdd5-800.avif 800w, /media/projects/elviria/elviria-01-848699a9fdd5-1600.avif 1600w, /media/projects/elviria/elviria-01-848699a9fdd5-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JagCdABUOyuOPViK2tcHNgp0AAPyPlGS/CCKtxfCeRncfTzqbQLpeqyExg8yJCSdxlpZIhXG4tWo2q9h2KZOCamzNjvsDgqYaoXltvGpx/P3s9FrgXlC/25QCvEk2XoOV28Gb1PWaNVdp43wG8Wt/yEL7koecgJ3dyu7Lj3BogE3wxAkEawAA"
  },
  "gallery": [
   {
    "file": "elviria_03.jpg",
    "src": "/media/projects/elviria/elviria-03-cd106a082fb2-1600.avif",
    "srcset": "/media/projects/elviria/elviria-03-cd106a082fb2-800.avif 800w, /media/projects/elviria/elviria-03-cd106a082fb2-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAQBACdASoYAA0APu1iqU2ppaQiMAgBMB2JZACdMoBOAB1SjioPOCWgAAD+x20TOMGkCdCdufbhpNhc7Kew6n54qyL9ztTdCWf7DF3B/Y2uOmclxVreMRaEeT1hEOdaeBwK8xClajhQ3vAEe9eYz72GDdY9MzdvnciutcfHgE07YYZJfZdy5sjWK5VqoQl0NVlb9sLvsx0sTiFKy5duLEDGjZ8JUAAA"
   },
   {
    "file": "elviria_04.jpg",
    "src": "/media/projects/elviria/elviria-04-51153408d4af-1600.avif",
    "srcset": "/media/projects/elviria/elviria-04-51153408d4af-800.avif 800w, /media/projects/elviria/elviria-04-51153408d4af-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdMoACn5jnkflYknlsyQAA/jqOytwYDT1Q0KJYw7DSsPP+sgaxbgzDDIBXsKHqSw9fOXhPXcOIkKu8kKbUl4rNHXJExyAsiZqS+tY34Q3pVnQDrq7HUbjiHDIMW9dwxu03NYhV/avv/8O2lVm8GsKyfdnwk85tIEAz8bPJWOQGtWkoGVTm5AAAAA=="
   },
   {
    "file": "elviria_05.jpg",
    "src": "/media/projects/elviria/elviria-05-7065d3f68040-1600.avif",
    "srcset": "/media/projects/elviria/elviria-05-7065d3f68040-800.avif 800w, /media/projects/elviria/elviria-05-7065d3f68040-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADQAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdACFZ07gewJ6mDAAA/gh//GEOJqsJhl7UWxOkGZBdEfluu0kHvlgEQu+wu1FYdO/HXXk5bAqqQR1XCpUAJTCho2mlntzgVLYoTz7ZCuJmW+7a0jDigWrrAq5KBnj/L1RhiIyJZ3XUe6/8HD6HXWjUDuh67eMPvqBqC/N06VSRCdrAAA=="
   },
   {
    "file": "elviria_06.jpg",
    "src": "/media/projects/elviria/elviria-06-a1064251063c-1600.avif",
    "srcset": "/media/projects/elviria/elviria-06-a1064251063c-800.avif 800w, /media/projects/elviria/elviria-06-a1064251063c-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOgMY2VQNrhC7d37OsAagAA/sdtb+91xMls6EwuKIxeLzwAyQa2gioqxk86rwkXO8AVFSN0JJxDLt5d+fBg3Yw7lwwz3F207Fn9+eybPHWULN6L/1FGIMQKdKugljdYuqGK6JX509zuxcRzf1cayrzBeLqPXRsVC4boAAA="
   }
  ],
  "card": {
   "file": "elviria_05.jpg",
   "src": "/media/projects/elviria/elviria-05-7065d3f68040-1600.avif",
   "srcset": "/media/projects/elviria/elviria-05-7065d3f68040-800.avif 800w, /media/projects/elviria/elviria-05-7065d3f68040-1600.avif 1600w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADQAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdACFZ07gewJ6mDAAA/gh//GEOJqsJhl7UWxOkGZBdEfluu0kHvlgEQu+wu1FYdO/HXXk5bAqqQR1XCpUAJTCho2mlntzgVLYoTz7ZCuJmW+7a0jDigWrrAq5KBnj/L1RhiIyJZ3XUe6/8HD6HXWjUDuh67eMPvqBqC/N06VSRCdrAAA=="
  }
 },
 "cortijo-nagueles": {
  "hero": {
   "file": "cortijo_nagueles_44_03.jpg",
   "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-03-4cd06be0f606-1600.avif",
   "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-03-4cd06be0f606-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-03-4cd06be0f606-1600.avif 1600w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-03-4cd06be0f606-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoYAA0APu1iqU2ppaQiMAgBMB2JagCdMoMpACudHQfRjS9u6DawAP5V4+AKkk7IEQb9b4+PGZu+yOAZSBZABkvKtA03sV+p2CIas8/GtHEGiAfwiMjkpS3cMrAgOppZvx3AM0oq9TM1s1mTQNw0Xt1ZRcYFdIhtNZlHPnGx0OM52NwzBOKiuAAA",
   "jpg": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-03-4cd06be0f606-og.jpg"
  },
  "pause": {
   "file": "cortijo_nagueles_44_04.jpg",
   "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-04-ec8c3d4cc166-1600.avif",
   "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-04-ec8c3d4cc166-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-04-ec8c3d4cc166-1600.avif 1600w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-04-ec8c3d4cc166-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADQAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOg7wARDw3ruP6JPQAA/iaT5A28T3ZA6zrSUkuJ0keOemDb++xioHo5uvR/587Gw6hKlNWBawAMegNyaGd5H0SXB7Y1/e3HSyA4LVRSmHgxdjAIRhuV3cZSMe2JTrsNxQScpaGcF5cB0WjoAA=="
  },
  "gallery": [
   {
    "file": "cortijo_nagueles_44_01.jpg",
    "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-01-546b148a2dd2-1600.avif",
    "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-01-546b148a2dd2-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-01-546b148a2dd2-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdMoADQiU73aplj7IhG4AA/eHqxQEofSkM7QcQiUrc+EpWXShk5w63DV4AU/ElowUhbRgTEwqvlTZIMm0spy7cY45I3tW1YtojmJqGcoND9OrWkv1An0O2QE0l5MgZ2A4duP5G1/duFCBgS1h2NO32egzK5G9ww3vdZ6sSEzFSozGdiXsjHFo6gWIDT+ogTiACSAA="
   },
   {
    "file": "cortijo_nagueles_44_02.jpg",
    "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-02-4740bbbde129-1600.avif",
    "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-02-4740bbbde129-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-02-4740bbbde129-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoYAA0APu1kqU2ppaQiMAgBMB2JQBYhhLgpUyUUQJ3swBjgAOt33luY/Z9MrC8oGP70s+xZsE44Qciu376EZit9LuWsrUzxtuXmLgXI+WBSpiipJ4OXGKs2YQPgQL1qylpUcP1eti7XmFG+XJnMZUhXWZx3jjy5yfOY8hYB5Xc1KaUxgPUx6GtDNAYAAA=="
   }
  ]
 },
 "villa-pareja": {
  "hero": {
   "file": "villa_pareja_01.jpg",
   "src": "/media/projects/villa-pareja/villa-pareja-01-97bf555c76f5-1600.avif",
   "srcset": "/media/projects/villa-pareja/villa-pareja-01-97bf555c76f5-800.avif 800w, /media/projects/villa-pareja/villa-pareja-01-97bf555c76f5-1600.avif 1600w, /media/projects/villa-pareja/villa-pareja-01-97bf555c76f5-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoYAA0APu1iqk4ppaQiMAgBMB2JQBOgAlaguX4uXP6jAAD+7ESlMiCXevpDdOe2lWG7NRTt+o3ERG7/xOl2KZu+XYeel/db16WVEwthAogHzGC1yGcNAuUZA078xjg+tLHtQQCjNPO3hThZvs3Jcj41s+RhJ9DwlAAAAA==",
   "jpg": "/media/projects/villa-pareja/villa-pareja-01-97bf555c76f5-og.jpg"
  },
  "pause": {
   "file": "villa_pareja_04.jpg",
   "src": "/media/projects/villa-pareja/villa-pareja-04-7c9072c671ad-1600.avif",
   "srcset": "/media/projects/villa-pareja/villa-pareja-04-7c9072c671ad-800.avif 800w, /media/projects/villa-pareja/villa-pareja-04-7c9072c671ad-1600.avif 1600w, /media/projects/villa-pareja/villa-pareja-04-7c9072c671ad-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JagCdMoMh+n/AbPUyBaIfW0A0APjjRjBvrzJ4nh8DWT8uB1U6SnK4Apa7vyDKR1uS7tavPUxoc+HFO2NQPtZJSpIuHhHNjotZVvqcU0R1k1S7XsqssoFqk3MRofWlSeuch0c/cP72KlpcVoxbu07u7YqKPQ3Ox1B2YuoaMAAAAA=="
  },
  "gallery": [
   {
    "file": "villa_pareja_02.jpg",
    "src": "/media/projects/villa-pareja/villa-pareja-02-b59198cf7327-1600.avif",
    "srcset": "/media/projects/villa-pareja/villa-pareja-02-b59198cf7327-800.avif 800w, /media/projects/villa-pareja/villa-pareja-02-b59198cf7327-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUABfG/FnzNfAmTrVAAD+VeVUT3ujLKCYE9bpzaEMho5F+XycsLThNkmvJpJGdlIJ30B6PPG6C+ZrpzlOZ+h0nTbZZwEp8nIb/jPmodPeRhHhF+oXdrjShjAuar37dEHNDtqGQBR2U75IzIUIwRpVpSjEpoAAAA=="
   },
   {
    "file": "villa_pareja_03.jpg",
    "src": "/media/projects/villa-pareja/villa-pareja-03-84bc6985431b-1600.avif",
    "srcset": "/media/projects/villa-pareja/villa-pareja-03-84bc6985431b-800.avif 800w, /media/projects/villa-pareja/villa-pareja-03-84bc6985431b-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBACdASoYAA0APu1iqk2ppaQiMAgBMB2JQBOmUABn9Ipf2i727maUJQrgAM4mHfxYnYnwnrKdyGP/u//yZeau1kIJ0c4/+Qh4v/MpduTN1g1UJnGiQqh/zjz78AYDxx6uZxhwA+tou5JXcf6qGQtSAKJfn8xi9sdqC4W6GZ4QjwRBI/kW5goeiZENpRrD55MEAA=="
   }
  ]
 },
 "sirio": {
  "hero": {
   "file": "sirio_01.jpg",
   "src": "/media/projects/sirio/sirio-01-1600.avif",
   "srcset": "/media/projects/sirio/sirio-01-800.avif 800w, /media/projects/sirio/sirio-01-1600.avif 1600w, /media/projects/sirio/sirio-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoR4LyAAMyiSD3B5eSOgAP6Q3sjrGbRw5jVLqmeIQ0QLk9PrTRzNPpNyrbq4hEUkx1IOr6lRbE8B93YlAVRFPbgKfPjdCm7FIu/KbmiSGgSrCTQvneGGLhP+VeE12L/fE5mF9wubATa1od8ZUDzvQFRRHK4sRC+Rkz0cmfwbYicP+8jYVAIZiRbLxpYAAA==",
   "jpg": "/media/projects/sirio/sirio-01-og.jpg"
  },
  "pause": {
   "file": "sirio_05.jpg",
   "src": "/media/projects/sirio/sirio-05-1600.avif",
   "srcset": "/media/projects/sirio/sirio-05-800.avif 800w, /media/projects/sirio/sirio-05-1600.avif 1600w, /media/projects/sirio/sirio-05-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdAYyypgaV4SGn2MyAAPHRPrJRMNfEtQlzm71FCmB6RzFXdDbISYnW2kOSevn3aLpi7ZzlSF++6bRdREAvwNQSf+V4Bqk7jXPIwS0OYfGPZey5WWXix6Qq09zt+YO/cCtO1+TZM7aBaAO6S5XxwKJBkLIIXwRU4WUebPdrSuaLMhIKELzWroTjsmJpqnQwgAAA"
  },
  "gallery": [
   {
    "file": "sirio_02.jpg",
    "src": "/media/projects/sirio/sirio-02-1600.avif",
    "srcset": "/media/projects/sirio/sirio-02-800.avif 800w, /media/projects/sirio/sirio-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdMoABcNYJsEpnwswAAP4nixHysmEHjjMl65O8HvfvsLJzlc7U3Hf+T+4pL9nnB9VzFXoqs4fDXt4+6tAzGIAbRHbOuwh672lFTErqor/ayEkWAE7nOUeWvoK1uUmsRLf5NgHwDCv98rwk8p0Y9iBswpEoEmr7X91SOfGxMu+nG4tZ6yAAAAA="
   },
   {
    "file": "sirio_03.jpg",
    "src": "/media/projects/sirio/sirio-03-1600.avif",
    "srcset": "/media/projects/sirio/sirio-03-800.avif 800w, /media/projects/sirio/sirio-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUGbaCTcXC+qw7wS/rp1xTpw4AP7k0q6S9YHW0be4A4TbkNFhsL02NWxnmw0HWkvewD0iWmTuKH2OylGX4zbPy1uKnp1jjbSeAr9XsaRb3uZaZH3ovzxgbVw7XFyjwZTCumaOSIW4X0jkAAAA"
   },
   {
    "file": "sirio_04.jpg",
    "src": "/media/projects/sirio/sirio-04-1600.avif",
    "srcset": "/media/projects/sirio/sirio-04-800.avif 800w, /media/projects/sirio/sirio-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBABBgTgAM8rsrMpNSlUoHmhwQAA/u/ERBMJmApj3TbwvrsOMfPJ0Cs4thaQrhkZXDSfPzb6ERxNnqMf5OhA0Oic8eUKk/Xb8CCoOYblZoK1g3Va6WfeXEXDV4o2NgeAwOUS/O91wiEAmzA5feXT+EcqwgsBkDaw81B31GPC4AAA"
   },
   {
    "file": "sirio_06.jpg",
    "src": "/media/projects/sirio/sirio-06-1600.avif",
    "srcset": "/media/projects/sirio/sirio-06-800.avif 800w, /media/projects/sirio/sirio-06-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQBACdASoYAA4APu1kqU4ppaOiMAgBMB2JYgC7ACILmYkCXHHN+n0Y/3gbfeAA/vKkOfHRb5FLSP1ONc9FzmxLVH7A0F+JUt5NW1h7uSnvgAHSWbABiClvOlI8F+0rZ+oRLztvEp4Ugze2ycB8LOq+Fc7DpRTzdGtfGiURw3P1o3BCQZCp2AR/x3hS9MJOqSMp8gAA"
   }
  ]
 },
 "villa-relojero": {
  "hero": {
   "file": "carril_del_relojero_03.jpg",
   "src": "/media/projects/villa-relojero/carril-del-relojero-03-1600.avif",
   "srcset": "/media/projects/villa-relojero/carril-del-relojero-03-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-03-1600.avif 1600w, /media/projects/villa-relojero/carril-del-relojero-03-1920.avif 1920w",
   "width": 1920,
   "height": 1080,
   "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACxC8ADMpTFV0SyZJWtr8VZAAD+7H5BNdUMUAjjOCH0ZWE8S/kLKHvL5crDF8NI+NbeygAO6RjgbJ0IWEiSLQY3yWEBx2F8la9yvvjnWgLzWwYD53i2WMMyEYoQjEYVt2VTUpM3AXlSxITF0pctM+zhkCxI64oR393gPR3i6Fb6PVDH2hb6/DzTjCtCuAA=",
   "jpg": "/media/projects/villa-relojero/carril-del-relojero-03-og.jpg"
  },
  "pause": {
   "file": "carril_del_relojero_05.jpg",
   "src": "/media/projects/villa-relojero/carril-del-relojero-05-1600.avif",
   "srcset": "/media/projects/villa-relojero/carril-del-relojero-05-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-05-1600.avif 1600w, /media/projects/villa-relojero/carril-del-relojero-05-2560.avif 2560w",
   "width": 2821,
   "height": 1080,
   "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBACdASoYAAkAPu1mqk4ppaOiMAgBMB2JQBdmUABoYySzOuVpvKmpVIAA/ujQ6Lc5Frz5q1nJXD5M+jEwPbuWnplT+UICTOPhXg288+KbxkLPHQfKLBspeE29+RUR8yS/mVWwogo+XYXqmO+LAny18ilAAA=="
  },
  "gallery": [
   {
    "file": "carril_del_relojero_01.jpg",
    "src": "/media/projects/villa-relojero/carril-del-relojero-01-1497.avif",
    "srcset": "/media/projects/villa-relojero/carril-del-relojero-01-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-01-1497.avif 1497w",
    "width": 1497,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBQCdASoYABEAPu1kq0+ppSOiMBgIATAdiWQAnTKAAcWSvtid+xlJ8ynSlVQq7Q8jAADN3PSzdCn4MyPatH/ox1rpK2wBHy4MwLv8D9Ju09UeKLsK9eiUWJLiBi4tnJ72EIk1IVo9Vo+y3JxkVhbER0kaVwYsUz3zezKIFH2fHecApfUMeUgiSFyV2Zaz2RlUhIgNswml2rvAAAA="
   },
   {
    "file": "carril_del_relojero_02.jpg",
    "src": "/media/projects/villa-relojero/carril-del-relojero-02-1600.avif",
    "srcset": "/media/projects/villa-relojero/carril-del-relojero-02-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-02-1600.avif 1600w",
    "width": 1920,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUABsCWGYHB66dEwReWH/AAD+WV0U5z5MPQKs0Kcc5U4zhccP29RNctuuZfanPnJqSwtKrRqBWzeKi2AW8CcA5YVDookmpCgwNlSikZj/V2OYvfVtn43dmrR9p0O4y+tR7P+AxWPiEm4/OVn0TWpWSDe9Ca+h5Pu0oHv3YK+lQ/TXogQyjmHEAA=="
   },
   {
    "file": "carril_del_relojero_04.jpg",
    "src": "/media/projects/villa-relojero/carril-del-relojero-04-1600.avif",
    "srcset": "/media/projects/villa-relojero/carril-del-relojero-04-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-04-1600.avif 1600w",
    "width": 1920,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JagCdIMgCdpD5HZwCB978RQC+qAD+6QPpE03xBQZWT95zbfogWipCLh6BuyN7sNgMS9ucBc70Zdp7BkIkoMUKFCjvt+wsdCg4WeyCkqBEcewdgOe/NzY+6q0wZ3fJ42aqdbmD1Et6/4TpEAAAAA=="
   }
  ]
 },
 "villa-ambar": {
  "hero": {
   "file": "villa_ambar_04.jpg",
   "src": "/media/projects/villa-ambar/villa-ambar-04-1600.avif",
   "srcset": "/media/projects/villa-ambar/villa-ambar-04-800.avif 800w, /media/projects/villa-ambar/villa-ambar-04-1600.avif 1600w, /media/projects/villa-ambar/villa-ambar-04-2560.avif 2560w",
   "width": 4256,
   "height": 2832,
   "lqip": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAAAwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JaAC7ACHALJ7cB5/lXU9qg4AA/urWoJfZr3vIpbguanC4/ZT4gmklmcMbdZxBK/wdhYqNO9/WMzZLwc6dfo6iR9jGJ4iJc9j5Bh+eMhat5vLV5pflvM0xD1s7X1I/IEJofsapFKuhPSmvlzzuE4y/7g9cLnnHKx37zo6HUI6CPeHe0yynDeCBeGMaH80liKr0JSWrFNuYmT4AAAA=",
   "jpg": "/media/projects/villa-ambar/villa-ambar-04-og.jpg"
  },
  "pause": {
   "file": "villa_ambar_03.jpg",
   "src": "/media/projects/villa-ambar/villa-ambar-03-1600.avif",
   "srcset": "/media/projects/villa-ambar/villa-ambar-03-800.avif 800w, /media/projects/villa-ambar/villa-ambar-03-1600.avif 1600w, /media/projects/villa-ambar/villa-ambar-03-2560.avif 2560w",
   "width": 4256,
   "height": 2322,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABwBACdASoYAA0APu1kqU2ppaOiMAgBMB2JZgCdIMggvhI9VxBV7Njsll/jwAD8j6Orp0j+E76EURnnt1NVAH01LqbWPE6NIx13t9nP0PdeK3pUGrXcEXg8FmvfWUUH3Fz1MiOl0NoIIRxjM2PsgWs2ob1RXx3HlIv4q5EQVDTewBdhGlHVtjLKSAZmG6ljQqvdHti6/oo3TT2eVALy1kFaAAA="
  },
  "gallery": [
   {
    "file": "villa_ambar_01.jpg",
    "src": "/media/projects/villa-ambar/villa-ambar-01-1600.avif",
    "srcset": "/media/projects/villa-ambar/villa-ambar-01-800.avif 800w, /media/projects/villa-ambar/villa-ambar-01-1600.avif 1600w",
    "width": 4256,
    "height": 2832,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZgC7ACP7FvOkrUE3XLoUAM3qspr58QsZnY/CvyaeHgNvcfJlJkQXJfGfFpJG8eawynCyv6a/TkLasU9+Ig5FLv8NRN06Qa+rl4tc5Gu/nLK3FjF5vcTIgrdDZkktiHuUjHnWXZNOes2jfEWo0N35Bu1eo4PUgNZa9dVXp/MsAAAA"
   },
   {
    "file": "villa_ambar_02.jpg",
    "src": "/media/projects/villa-ambar/villa-ambar-02-1600.avif",
    "srcset": "/media/projects/villa-ambar/villa-ambar-02-800.avif 800w, /media/projects/villa-ambar/villa-ambar-02-1600.avif 1600w",
    "width": 4256,
    "height": 2832,
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOkERhdqafxhYmPpNifXv9AAP7qeF0QBg7N4BRoVGXJy/tcaOI+9zoDeHeLG1bKP7I7O7RSa6Oide/L3dkrwJJwSOmPp1zxCFRWiyvrh9Fsh+FqreHvQhNTzUIK97eavmqrWdn9burGmiYuK4Fy4ehYjTdc0YnqQnj7N6cAMAArQDs/uL5cV5+4fvzHnW3W/6EU44AAAA=="
   },
   {
    "file": "villa_ambar_05.jpg",
    "src": "/media/projects/villa-ambar/villa-ambar-05-1600.avif",
    "srcset": "/media/projects/villa-ambar/villa-ambar-05-800.avif 800w, /media/projects/villa-ambar/villa-ambar-05-1600.avif 1600w",
    "width": 3978,
    "height": 2705,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMrnGqJ0AEVw7EpQAD+q37cuPSan8zKLFCPgk8TzGLTEfrbGXufQ4HBcziGi/T30qr1DmV+brcs0mk0CQ8rnhY7kHlUsJJ2EwkNHfVIDs5vlmkrZ5ek4Iy83iJCSc6VN5IHc9rv3Sk7PBf2NFkArRlo2hxAAA=="
   }
  ]
 },
 "villa-pino": {
  "hero": {
   "file": "calle_pino_01.jpg",
   "src": "/media/projects/villa-pino/calle-pino-01-1600.avif",
   "srcset": "/media/projects/villa-pino/calle-pino-01-800.avif 800w, /media/projects/villa-pino/calle-pino-01-1600.avif 1600w, /media/projects/villa-pino/calle-pino-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoMpJn/Ad2RXnr38jdeCKcgA/onIfElDKLSlNR+aQHD5hHijM8soX9p221zbo2n3vpEVbGlS8IyKKsrbp8BFf8qlIzkVa8AoxHpCuv5LAZdV81Sggivmrs0eyNykjv6aHQpz/lAn0wXj7v1AUpqYSDbWUYnhbSXSRLrIYkUIcs3CSYnSDQAAAA==",
   "jpg": "/media/projects/villa-pino/calle-pino-01-og.jpg"
  },
  "pause": {
   "file": "calle_pino_02.jpg",
   "src": "/media/projects/villa-pino/calle-pino-02-1600.avif",
   "srcset": "/media/projects/villa-pino/calle-pino-02-800.avif 800w, /media/projects/villa-pino/calle-pino-02-1600.avif 1600w, /media/projects/villa-pino/calle-pino-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JZACdAYwSuW4g/wcH9KcMxE7okADeXyUHCD/UW7v4l4D1zoQyaIMhvThtiACE9H6y19k4oxUq7od0gjVYqiMN2Q3cCqgToaHc552akconS1fc/ODlPDUP3XntoyD74kVHdnXAmNc5FSLm6fctERdX/mVV9JcXVB740fH1Og24mO4BH8WUkAAA"
  },
  "gallery": [
   {
    "file": "calle_pino_03.jpg",
    "src": "/media/projects/villa-pino/calle-pino-03-1600.avif",
    "srcset": "/media/projects/villa-pino/calle-pino-03-800.avif 800w, /media/projects/villa-pino/calle-pino-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCsH8AgqQ2dpK5yj3h/+C0IAAD+hBw85DYQxFO5Y8MCgW7AWNgVP8iVn4PMEfIrLY/fprragNJGr9ldWYXObVpfw5fWXJVtyggRlSkOuc05buT4848Fu/fmidy9EE0v51P/l9jEkI98jYsAg8JFvqWzkCaGB5LilSUPQ3bWHx89Abqeql+Z0BVMnHO9+bUUDsfyCfGgSt+vVrPcBrfIa5IFcAAA"
   },
   {
    "file": "calle_pino_04.jpg",
    "src": "/media/projects/villa-pino/calle-pino-04-1600.avif",
    "srcset": "/media/projects/villa-pino/calle-pino-04-800.avif 800w, /media/projects/villa-pino/calle-pino-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdMoGv/gNaXgHxqGs9F5AA/maqDRzmptMn0kwTpsQoIup1fCrd6O055/VVFHgu0aQ9XoFkKFVPD6rYZJlMNn/SvE2BD7+NXpSsD6YvwOJdBpMpFD0rxQBevssivIL/Nk9cGTOiGwL4QMfc5w3r+zQTRzXtfHy8pOegZv+kfXD9bdv8Kh8uv6vQvmLYaawHWyVwAAA="
   }
  ]
 },
 "atalaya": {
  "hero": {
   "file": "atalaya_01.jpg",
   "src": "/media/projects/atalaya/atalaya-01-1600.avif",
   "srcset": "/media/projects/atalaya/atalaya-01-800.avif 800w, /media/projects/atalaya/atalaya-01-1600.avif 1600w, /media/projects/atalaya/atalaya-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdMoMljEFAelf8OZ4XbnFlu4KAAP7VxDF8mx/N27+/u7Qs5iJakCbpFhh6OMqks5gX0te4EmPXEfvSFW6307BmH5CLBw1AO9MGFLkY6rvg8HCxTxmnBjn6BVP0JPjc2nvlZ/+PovPXZ5NIEwX+POv3tD3DTAZNc5qujL8NkZ1ZNQWiXpgqf79Bh/9Gjdsg9uZ6NQsXTzNuvX5gAA==",
   "jpg": "/media/projects/atalaya/atalaya-01-og.jpg"
  },
  "pause": {
   "file": "atalaya_03.jpg",
   "src": "/media/projects/atalaya/atalaya-03-1600.avif",
   "srcset": "/media/projects/atalaya/atalaya-03-800.avif 800w, /media/projects/atalaya/atalaya-03-1600.avif 1600w, /media/projects/atalaya/atalaya-03-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBACdASoYAA4APu1iqk2ppaQiMAgBMB2JYgCo9YyA31KKWVdckqjZioGAAP7nYQ/gsErAw7Se3QudN55H+aWh7rsM9xNGSEyCg96+lOsyZmmiLeoky+9/o5jVO7BMz1asSnW8K7GcvXNzJwa6s18XpeT+eTL9Xqos0NH47OwvtUEru/6F2XriZKlumVP2v2Oqi3Y48xR6TwaEgGb2NwECAAA="
  },
  "gallery": [
   {
    "file": "atalaya_02.jpg",
    "src": "/media/projects/atalaya/atalaya-02-1600.avif",
    "srcset": "/media/projects/atalaya/atalaya-02-800.avif 800w, /media/projects/atalaya/atalaya-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgC+SYx24PkNtBxSpeb1ZLQIMAD+52ETEss+Cr/DH4SaZ2eMP+0nyGWdQEG9qgv6mYj2sb4OYqH+nMpxf8OCHIWObswvzJmK1t0SjDhuwHLOOVpCyH9x4JikkvP+o95JjHXmHjmWkdlRoEbmkA8GYtz41Cph7fwJ05ViQZwOiVIAAAA="
   },
   {
    "file": "atalaya_04.jpg",
    "src": "/media/projects/atalaya/atalaya-04-1600.avif",
    "srcset": "/media/projects/atalaya/atalaya-04-800.avif 800w, /media/projects/atalaya/atalaya-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwDCgdwLfrVJxFdVnI3pEdLIr/BAAP7CQL4W4ZQyzlekfZo9fRuleMXNr78zX6V4pbl6r5gyPe1XL+pNIw1IhTsRe3iTpfn1qCxLWglVFweUDaJRbZLKVoonBithWr596yqJwfAfUfqjt4ou6BjNrSyA/eTi3kQ0+dviLe15khxH2ylscbdeodT+z45NHidivaAOv0QAAA=="
   }
  ]
 },
 "hotel-boutique": {
  "hero": {
   "file": "hotel_boutique_02.jpg",
   "src": "/media/projects/hotel-boutique/hotel-boutique-02-1600.avif",
   "srcset": "/media/projects/hotel-boutique/hotel-boutique-02-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-02-1600.avif 1600w, /media/projects/hotel-boutique/hotel-boutique-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JQBOgAagbLO3KDM07AAD+np9rq2PKHrrPpmMlyxOrutoxM2mQCGlwsyGNq0EYY+Kt1P+1hbYDMuSmr0XGBs6PyrEcyfmHEZgKKqbxIjEXGGo0waD6zgcLF/XCX9kJ0qAwfqpf6S5HVaYA",
   "jpg": "/media/projects/hotel-boutique/hotel-boutique-02-og.jpg"
  },
  "pause": {
   "file": "hotel_boutique_01.jpg",
   "src": "/media/projects/hotel-boutique/hotel-boutique-01-1600.avif",
   "srcset": "/media/projects/hotel-boutique/hotel-boutique-01-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-01-1600.avif 1600w, /media/projects/hotel-boutique/hotel-boutique-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOkDgBeksLahavPLS4jgAD8reZUK5C3kZ+NWGyo7Qt7n3k89m7Kpff7r7YkEQZHomAAFpO48MQ09JXP4Te6urO9vC1qOmxZtM9rKrerF+xqmQ6N5nGjlwqY8Ug3iB9JhhjA8wAAAA=="
  },
  "gallery": [
   {
    "file": "hotel_boutique_03.jpg",
    "src": "/media/projects/hotel-boutique/hotel-boutique-03-1600.avif",
    "srcset": "/media/projects/hotel-boutique/hotel-boutique-03-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCsAB7DiuE5J2LPS+P1gAD45QYfe4XXZXlozcUbxZM5Sz4oZzEt9RvgAUMzAle0Zb4/UKV7wWcjfLcyzOZVqIymWL1BmPHSMwvxu2GpTJzUBITThHeDlZcXjxoYwwFcAl6akQv3K0SY7vaXjPqgPKEMrwu9fwrHAAAA"
   },
   {
    "file": "hotel_boutique_04.jpg",
    "src": "/media/projects/hotel-boutique/hotel-boutique-04-1600.avif",
    "srcset": "/media/projects/hotel-boutique/hotel-boutique-04-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCw7B5eDwq4xy5woAD+ZspXNwNkfREhNuhiFQXW+OuAfOck2MxfuLiqR4uaAJBZ19Sr9zMM8bzlfv9puAi/TWeo+wtVCIy6zLYk9hXtS+Ut4bUDRZcYM3m8DAbDZxVI6KG33ZNQGBdMiFE9p/YGcFrexpeYAAA="
   }
  ]
 },
 "huerta-belon": {
  "hero": {
   "file": "huerta_belon_34_01.jpg",
   "src": "/media/projects/huerta-belon/huerta-belon-34-01-698a2185d331-1600.avif",
   "srcset": "/media/projects/huerta-belon/huerta-belon-34-01-698a2185d331-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-01-698a2185d331-1600.avif 1600w, /media/projects/huerta-belon/huerta-belon-34-01-698a2185d331-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoYAA0APu1iqU2ppaQiMAgBMB2JZgCdEf/gLtI7QSKSt7ol9V0AAP7F5SlXV6hTIiJFUa9/EAXtXWSczGriHi6Z3zvXJjfIBFz/a6socBptQHNjWRKwfAZ4IJflnu481CQZN/fjeMN9FFeB7v4nWx4AZOAyR6o+sS/vyM3hSrU9hx+AIsfrhD86fNuLWGVO1TRD7Id++ZRAAA==",
   "jpg": "/media/projects/huerta-belon/huerta-belon-34-01-698a2185d331-og.jpg"
  },
  "pause": {
   "file": "huerta_belon_34_03.jpg",
   "src": "/media/projects/huerta-belon/huerta-belon-34-03-594dac38cfac-1600.avif",
   "srcset": "/media/projects/huerta-belon/huerta-belon-34-03-594dac38cfac-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-03-594dac38cfac-1600.avif 1600w, /media/projects/huerta-belon/huerta-belon-34-03-594dac38cfac-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAwBACdASoYAA0APu1kqU4ppaOiMAgBMB2JbACdMoGv/i2RWq9s1HjEmlgA/t/T5G7TqZTNsHDE8tIgFE8ZMH2xui7GeFffiZ2xHZZAU9LroUfRYcdtUDv2t9U2qfU34UoPrajiGr7v8pXIt2kdrY6gLAIYDeaSIrTyhLMaYRUjxq3lff35S4fI0oopBGuMOJt9nHsO/ItdqbE6qkx1AAAA"
  },
  "gallery": [
   {
    "file": "huerta_belon_34_02.jpg",
    "src": "/media/projects/huerta-belon/huerta-belon-34-02-dd8f5f6ab603-1600.avif",
    "srcset": "/media/projects/huerta-belon/huerta-belon-34-02-dd8f5f6ab603-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-02-dd8f5f6ab603-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdEf/gMmmY2AK2zufI4AD+lJ98qQox26XQZmlj+XHbJ7iiLw6KJO8KwZ3NelQcLsuRILI0YxM1E5jEWbiJbHypcTV2dzk900v3UGlnTsksWgM1Zyyn2djJKQwG4OsRnX3pN75hKQ0AbRN5/r+5gm454NaLrvq3kHP6VIXeoifvKskk1h/cZQqGH57oBpG65kZVgAA="
   },
   {
    "file": "huerta_belon_34_04.jpg",
    "src": "/media/projects/huerta-belon/huerta-belon-34-04-a8331071b7df-1600.avif",
    "srcset": "/media/projects/huerta-belon/huerta-belon-34-04-a8331071b7df-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-04-a8331071b7df-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoYAA0APu1iqU2ppaQiMAgBMB2JQBZwZYJ0IWVU1v2pBOhcO9D0AAD9PTI2NVgOVeyeIwCG6aAE4806kCNTImZQkhsyq7UsnRK3ohROexYSeAP42f7X57cHA3jHMXBm8YU3q6Qxf0JDsaiwxCs9q0W0C/ag/aiI4plyJkK/YKNyDiu7RF9PMrC3GUU80wbuPVJ8GIdQAAA="
   }
  ]
 },
 "castilla": {
  "hero": {
   "file": "castilla_01.jpg",
   "src": "/media/projects/castilla/castilla-01-1600.avif",
   "srcset": "/media/projects/castilla/castilla-01-800.avif 800w, /media/projects/castilla/castilla-01-1600.avif 1600w, /media/projects/castilla/castilla-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdAYy8wPypE1CkGrdlGAD878NkSAqG4sv2jIzJK92YU4N2/+ICo/KYrFknL+L0Dt3u4RpTDUlKC0byYTUYMc+30dNs0jJjRHW2SXnz1jMhufIve8suU1yBEf9eDJcq07rf/HJSTZyayf2VToFxVyeSlvRwC+VeHKYYma5MjT9sgsAAAA==",
   "jpg": "/media/projects/castilla/castilla-01-og.jpg"
  },
  "pause": {
   "file": "castilla_04.jpg",
   "src": "/media/projects/castilla/castilla-04-1600.avif",
   "srcset": "/media/projects/castilla/castilla-04-800.avif 800w, /media/projects/castilla/castilla-04-1600.avif 1600w, /media/projects/castilla/castilla-04-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAwBACdASoYAA4APu1iqk2ppaQiMAgBMB2JZQDE2Yx2xN1np7sUGEME64AA4n66mEy7KuDrpqBauIloaf3nqEWyWoKQ+3f8/yWXECk2wF2OysZIw2QPnyWwbI6TSXYSDbXx+QcKveBrQNwzW5lHJjyeYZE5NKXc/6Z4UJ2gR//2s7/vNchCRB7xKPvMYNyXJ+lQKZyAAAA="
  },
  "gallery": [
   {
    "file": "castilla_02.jpg",
    "src": "/media/projects/castilla/castilla-02-1600.avif",
    "srcset": "/media/projects/castilla/castilla-02-800.avif 800w, /media/projects/castilla/castilla-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JaAC7AYvWuxFcecdPNKbjst7+EAD8+6HALky+EbSANQGLRizYmd9q+4Qpi9l9DxEiyYEp5a7P3nHvNK5Wa3zZlVhARhee8lvhBzrJG/vhJDblCFOFukFJxR9p6KCM7B3Ai3s/4zet54qY3LMFnbRM/WCadYw4QKDIQXjILELcdDDOJOIZpM86Ety/7ESg1pEqPbwMJyF1KPaVbS5UOwAA"
   },
   {
    "file": "castilla_03.jpg",
    "src": "/media/projects/castilla/castilla-03-1600.avif",
    "srcset": "/media/projects/castilla/castilla-03-800.avif 800w, /media/projects/castilla/castilla-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUDX/xbIq7mOhPYgFBqHyMGV7oAD9d+vkXLm7wcs4ELhGEyPhV46G0UdECVAPCR/ZQrlCtvmXveWiiMLz2Vvt6AnQ8dZzCJTdaRhpzfK+00xCJIt85piDjwrh9rbseddZ0EtlcyzXp/gr291fOsaZ2MjnfvHu39qCWQ9MZ5xx382hQNGxQPiidtttIV5M4jS75yBdkrgA"
   }
  ]
 },
 "villa-del-golf": {
  "hero": {
   "file": "parcelas_del_golf_02.jpg",
   "src": "/media/projects/villa-del-golf/parcelas-del-golf-02-33e8aa1ac433-1600.avif",
   "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-02-33e8aa1ac433-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-02-33e8aa1ac433-1600.avif 1600w, /media/projects/villa-del-golf/parcelas-del-golf-02-33e8aa1ac433-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwAwCdASoYAA0APu1kqU4ppaOiMAgBMB2JQBOgBH2O3M+sAOaOb+gAAP5bgqhtNk28zNtLs1hGAdBj7riRwdfV8oOVQZ7O7ucC6vTPtpTxdYLVamD6g0LQFtZEAnivO+QIW2CU4Pe9cBYfaCJ+biWv+6LwPdfF0WArGAffdGB2vxB3dAAAAA==",
   "jpg": "/media/projects/villa-del-golf/parcelas-del-golf-02-33e8aa1ac433-og.jpg"
  },
  "pause": {
   "file": "parcelas_del_golf_01.jpg",
   "src": "/media/projects/villa-del-golf/parcelas-del-golf-01-37c7db1b073a-1600.avif",
   "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-01-37c7db1b073a-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-01-37c7db1b073a-1600.avif 1600w, /media/projects/villa-del-golf/parcelas-del-golf-01-37c7db1b073a-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoYAA0APu1kqk4ppaQiMAgBMB2JaACdAB4mw7OPJuR6RGaAAP7WG5R3CqkpgNFH2dfizM/oA38DZORxo09odTtDefhjzDsfTzBNJPgRBQ2KoI2bSqNBVGX7AbLe+LwNwDgdVMJkl370Px0Hv2QZlJMwv10u6vnXyIVzv84maL7AA4gA"
  },
  "gallery": [
   {
    "file": "parcelas_del_golf_03.jpg",
    "src": "/media/projects/villa-del-golf/parcelas-del-golf-03-d0b3b06019b1-1600.avif",
    "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-03-d0b3b06019b1-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-03-d0b3b06019b1-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZACdIHAgvRBzrTkP5bId16BAAP7WDtfKpZ7GLDCwvodQaaLzyIs9M+e9hUPn8Sh8M5fvzCzsMbDlJZGHWkQSttKkjOzGnTWeYbVww4t0QowR7reNQSAVvAXrFtlg5ZRc0YoLvJ29K40RI4ZPxyOB4V4dOre3rUJwh4AA"
   },
   {
    "file": "parcelas_del_golf_04.jpg",
    "src": "/media/projects/villa-del-golf/parcelas-del-golf-04-ebd7d78ba3f3-1600.avif",
    "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-04-ebd7d78ba3f3-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-04-ebd7d78ba3f3-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JZAC7ABK3BWfLOCiPLysAAP5m3E3zGur+WwGsOp118TshjAmJYO/4Tvs8mU0vto3YOmiVdg0/89ar5NrpkIsz61RGp53VC4QnLq+VkkZpGmeH32jVILM/RUCkqf/UjGOmZhR8VOwVa8GT2ZbN+aCJapzxbtuei5ETLfWAAAA="
   }
  ],
  "card": {
   "file": "parcelas_del_golf_04.jpg",
   "src": "/media/projects/villa-del-golf/parcelas-del-golf-04-ebd7d78ba3f3-1600.avif",
   "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-04-ebd7d78ba3f3-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-04-ebd7d78ba3f3-1600.avif 1600w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JZAC7ABK3BWfLOCiPLysAAP5m3E3zGur+WwGsOp118TshjAmJYO/4Tvs8mU0vto3YOmiVdg0/89ar5NrpkIsz61RGp53VC4QnLq+VkkZpGmeH32jVILM/RUCkqf/UjGOmZhR8VOwVa8GT2ZbN+aCJapzxbtuei5ETLfWAAAA="
  }
 }
}
