// Generated by scripts/media/build_projects.py from scripts/media/projects.json. Do not edit.
import type { ProjectMedia } from './types'
export const projectMedia: Record<string, ProjectMedia> = {
 "the-house": {
  "hero": {
   "file": "the_house_06.jpg",
   "src": "/media/projects/the-house/the-house-06-1600.avif",
   "srcset": "/media/projects/the-house/the-house-06-800.avif 800w, /media/projects/the-house/the-house-06-1600.avif 1600w, /media/projects/the-house/the-house-06-2560.avif 2560w",
   "width": 8368,
   "height": 5584,
   "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADwAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JbACdACHGy55Z0HT3dfBAAPHDNWEj6nC9T07MNKsjb/pW43jHEuEOV248NnVTyzs6GY3x0EwIdvmdkCGbn7yBdI+y+oRsegj9uKRzkUN9KTxrRNuLaTovOtsFjE4bwhTQC7HlUk9ukQTwOR5m8Ie+hRQjAuxf8iLeL3gb0Q1AysrI8qXN9GNYVu++B6WMTs6wCANQAAA=",
   "jpg": "/media/projects/the-house/the-house-06-og.jpg"
  },
  "pause": {
   "file": "the_house_01.jpg",
   "src": "/media/projects/the-house/the-house-01-1600.avif",
   "srcset": "/media/projects/the-house/the-house-01-800.avif 800w, /media/projects/the-house/the-house-01-1600.avif 1600w, /media/projects/the-house/the-house-01-2560.avif 2560w",
   "width": 5272,
   "height": 2962,
   "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoYAA0APu1iqU2ppaQiMAgBMB2JQBWABFVcAUN25haiymgA/tCOQyWiOaSPV7TafdAQxGxOS/Urqo2Cdp6qysjym2paVGLbxxZulN8cwHTFH2OSl2X06MlAbOl7vtXlkXciYd0ciuWI0MJ1JGYhlzxvOrD4tGosiu7//dKKaOjjRHq0AAA="
  },
  "gallery": [
   {
    "file": "the_house_02.jpg",
    "src": "/media/projects/the-house/the-house-02-1600.avif",
    "srcset": "/media/projects/the-house/the-house-02-800.avif 800w, /media/projects/the-house/the-house-02-1600.avif 1600w",
    "width": 5272,
    "height": 2962,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoYAA0APu1kqk4ppaQiMAgBMB2JYwC7B3gAgT421d68G++KxkAA/qX+qH8/YAd+1geOTmi7zspKx+5CnYOleRBFjYwFvCu1T4MhcIpJfIKWuW9a6nkT9RX2aCg7oBbtJ0nGdXM5h2vuKc8RnmnmBb3wfoR/TJul3kzODMbx+4EptfIZ8BtO4wAA"
   },
   {
    "file": "the_house_03.jpg",
    "src": "/media/projects/the-house/the-house-03-1600.avif",
    "srcset": "/media/projects/the-house/the-house-03-800.avif 800w, /media/projects/the-house/the-house-03-1600.avif 1600w",
    "width": 8368,
    "height": 5584,
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdACK1L6+E8+Am0niZXXTAAP3QHWCiW+7Zh8YD+h1rmZV4PL/u7943N3GXfWIu48trMuuOJYHYp5xqt2t9AfjbRa4gweIwNOM+/tAfuyxrm4cMs2BCQAybD+WV/NYTVD9lPE0soME+nWs51IGr23cv+V7+4+ZO6NVdlJf0oVmDsYnxwsaY1m70ZQn2uB/SFOAA"
   },
   {
    "file": "the_house_04.jpg",
    "src": "/media/projects/the-house/the-house-04-1600.avif",
    "srcset": "/media/projects/the-house/the-house-04-800.avif 800w, /media/projects/the-house/the-house-04-1600.avif 1600w",
    "width": 8368,
    "height": 5584,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdAYyelq+jWODHfbH+MgAA99NXZpWNM72vxWNlLmaEmiynmD6fqUqxHtJCyGuB53e8BUNGvLPoTmUV3akUmjh0UMyycHaDo0jJ+xAgkAoRliif4TxnjTJi1U4R/n/k96jN6RWzdjMsgX10NwXIMyswk6f44Q9fLl9umNnYRscdtXGsoWL8v92GSPbPwFWbdR4fNeo4POp+vY7WqAAA"
   },
   {
    "file": "the_house_05.jpg",
    "src": "/media/projects/the-house/the-house-05-1600.avif",
    "srcset": "/media/projects/the-house/the-house-05-800.avif 800w, /media/projects/the-house/the-house-05-1600.avif 1600w",
    "width": 8368,
    "height": 5584,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdL46BEBcGdYyZTEENYAD94c+oIJI/oMAoSw1MmWv1zBXSDqqEbg7tU1ZlVp4j65TPH30mQQulNmpbYLlnrADZoDiE+gxiZzIVUOzeZfqay1I6aFhp5HZxK9SvX/IYyOyhlGSvjqF9HScIZYnivVUEV10t2ZV7awyYrbA/xAAA"
   }
  ]
 },
 "villa-silver": {
  "hero": {
   "file": "silver 1.jpg",
   "src": "/media/projects/villa-silver/silver-1-1600.avif",
   "srcset": "/media/projects/villa-silver/silver-1-800.avif 800w, /media/projects/villa-silver/silver-1-1600.avif 1600w, /media/projects/villa-silver/silver-1-2558.avif 2558w",
   "width": 2558,
   "height": 1430,
   "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYAA0APu1iqU2ppaQiMAgBMB2JaACdMoACTwA6UHztuKmD+4AA/b8QNzbsTeCfXoUJ6HliBK6nRV1YLCdruwNuEOdv5Jacp02pgfYCL187fFlHjKxMyt4M/8SKNcO9IjUEFqr88cCIuJGgC4Z06EP0ZguPBnaed/UGtqepoW2IpZX60HLNTAa5YxoZojN9Hyeb6RthCAA=",
   "jpg": "/media/projects/villa-silver/silver-1-og.jpg"
  },
  "pause": {
   "file": "terraza-atardecer.jpg",
   "src": "/media/projects/villa-silver/terraza-atardecer-1600.avif",
   "srcset": "/media/projects/villa-silver/terraza-atardecer-800.avif 800w, /media/projects/villa-silver/terraza-atardecer-1600.avif 1600w, /media/projects/villa-silver/terraza-atardecer-2000.avif 2000w",
   "width": 2000,
   "height": 1335,
   "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdL1AViAytn2v2oAcwnteAAP6iOCX8nEdkzQLOuCJzYz8L/k9TzQ1QpJ7+huRGKY8jLsS724x8KsErjeSGbmYG043dzxYbisyV5eIj+j1NTH29pm1DtN3WPx3+HLLdBDIAOXPPbUnOg0TaQ0bAy3Yj6DJcu1yHDOgO28AaDBKJlCKdz1inQ/XJ4MPCGzDQAA=="
  },
  "gallery": [
   {
    "file": "VillaSilver_03-scaled.jpg",
    "src": "/media/projects/villa-silver/villasilver-03-scaled-1600.avif",
    "srcset": "/media/projects/villa-silver/villasilver-03-scaled-800.avif 800w, /media/projects/villa-silver/villasilver-03-scaled-1600.avif 1600w",
    "width": 2560,
    "height": 1709,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCdIExgvQ5TZwAY/ZQ5RIAA4kc3qwoDREix1z33O/iF93hkMewpy/oWPcQWX1x04hACphI+pjy6hJDDEuOn0JSdjho+DwWpWI3FW7h0znFh4vgcYingmguKtUu4ELjwl0poWzebdWj9uSVc5Io6B12u/p6uY7v8wO9+XEO6jnKtNIAAAA=="
   },
   {
    "file": "VillaSilver_04-scaled.jpg",
    "src": "/media/projects/villa-silver/villasilver-04-scaled-1600.avif",
    "srcset": "/media/projects/villa-silver/villasilver-04-scaled-800.avif 800w, /media/projects/villa-silver/villasilver-04-scaled-1600.avif 1600w",
    "width": 2560,
    "height": 1559,
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYAA8APu1iqU2ppaOiMAgBMB2JbACdL11s/wHjdP9eDZCFNw2sAAD+dlZoPqMcf/AnMaoflmEAbuG3wm/VEVir3Zam2Zz/4TRoSf/j6WBCjEVX+W7rvFqMUL9ll8tB5KTfYosv307YN26bqwrWHgR7V6FjIxjorxNHyfNDZw9Dd3YxJu8SSz1ybPI75gslNMFNh+Mk8byr1WmS/kx/GAsMKAA="
   },
   {
    "file": "silver 2.jpg",
    "src": "/media/projects/villa-silver/silver-2-1600.avif",
    "srcset": "/media/projects/villa-silver/silver-2-800.avif 800w, /media/projects/villa-silver/silver-2-1600.avif 1600w",
    "width": 2558,
    "height": 1432,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdMoMYOHcAsq4pgi3r1hTMZgAA/oISq6mAE1GCJ0+s3KpSO0bKiCPeFGNMqepirQ4EDmZYbdjihIKanrCe9Y6HEBsCnJRC0J+RFP2hUBN8gfLyXxeucnbNDDl/QA031tMsNOZ16ZXXRajbxY1GZd8PTwX61UAAAA=="
   }
  ]
 },
 "la-resina": {
  "hero": {
   "file": "la_resina_02.jpg",
   "src": "/media/projects/la-resina/la-resina-02-1600.avif",
   "srcset": "/media/projects/la-resina/la-resina-02-800.avif 800w, /media/projects/la-resina/la-resina-02-1600.avif 1600w, /media/projects/la-resina/la-resina-02-2560.avif 2560w",
   "width": 4096,
   "height": 2731,
   "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoR4GCxWv4jPfUxSDsoaAAD+gfLwTIhoioxtCgbwqS48x2MONaAQzULfXxE18CTZLbp1KF/QdHMugSdRY+HepQgreyYS7MqehFtno/7hiter31hhekn8Bi/VTlpEfbvrpIWaYhHJLRrg1m91JqRfbMKaAAAAAA==",
   "jpg": "/media/projects/la-resina/la-resina-02-og.jpg"
  },
  "pause": {
   "file": "la_resina_07.jpg",
   "src": "/media/projects/la-resina/la-resina-07-1600.avif",
   "srcset": "/media/projects/la-resina/la-resina-07-800.avif 800w, /media/projects/la-resina/la-resina-07-1600.avif 1600w, /media/projects/la-resina/la-resina-07-2560.avif 2560w",
   "width": 4096,
   "height": 3072,
   "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACwBQCdASoYABIAPu1gq1AppKOisBgIATAdiWIAuzNlr/4BeRg8bsRlj5qqBFLgpU33lw6bqKAA8mdq9P3VeO0TwNXeXb5zQ8Bd0jbJorDkLmQrh4qsCu3HwaCH2KDqrffAGHdkH3jNh4vrAH3WqMxHhUmVpfWS3fb3AhOySgEJEXu0fvWh9EFj2220FZ7OkXj9Rj5uNQ3xnJtoUdROAxy8BuIAAA=="
  },
  "gallery": [
   {
    "file": "la_resina_01.jpg",
    "src": "/media/projects/la-resina/la-resina-01-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-01-800.avif 800w, /media/projects/la-resina/la-resina-01-1600.avif 1600w",
    "width": 4096,
    "height": 2731,
    "lqip": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoAlsxexpR1tQU5aeXam4lRIAAD+dwX9onmKpvFwB2mcywlmQL+1mv0dSODejVXu5nrg6eVYAHqp3OoENNLo9D6uSVYfikMM1XuzjZsVdLxgS0E51miGRBj08vsmfd6K/C3LV2bt4mvunannocaBoYIxV90xJol85El92SndyIpB0rArksOjP/hRmNwGqYbtWWyne9CNAp1Nsmwdqx7OxFxo1+AAAA=="
   },
   {
    "file": "la_resina_03.jpg",
    "src": "/media/projects/la-resina/la-resina-03-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-03-800.avif 800w, /media/projects/la-resina/la-resina-03-1600.avif 1600w",
    "width": 4096,
    "height": 2731,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMjb0fVOGsHWHpAT7ycwAD3sJsFjht2dUYvgY/H9n40eIAa+dugh+Vgw5nCV79mpLXR/VT+J/2ygjMmHMjacePXckXJRUN3PuXcBhK6CGQzpFtQQF7mjnmuK+i13APjf1k2Y96YVaAFAgVa1dfZplYiRpUSVpMphmHkJ+uhHH7pnG4Mficbfd7D82lUs/mAAAA="
   },
   {
    "file": "la_resina_04.jpg",
    "src": "/media/projects/la-resina/la-resina-04-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-04-800.avif 800w, /media/projects/la-resina/la-resina-04-1600.avif 1600w",
    "width": 4096,
    "height": 2731,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoYABAAPu1iqk4ppaQiMAgBMB2JbACdMoADUE1bFLLdwt0/AADKZPuskqfTWIwzVhCl1tJRzpOMejUPnqdrzfYl3iFp6ruMsy5hJm9g8mTnVnis7Eeg/0JYvMrKUUzMsmAwzqcZ7SOQcIu3PqFLI6p74BhSqX9ut1GWFxQPZlDB4ZcTCiqC+hQQNekj1X38AAA="
   },
   {
    "file": "la_resina_05.jpg",
    "src": "/media/projects/la-resina/la-resina-05-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-05-800.avif 800w, /media/projects/la-resina/la-resina-05-1600.avif 1600w",
    "width": 4096,
    "height": 3072,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAADwBQCdASoYABIAPu1sqlGppaOiqAqpMB2JQBOmbLX/wDcaoj28v2CkN9Z2tlUiD/ls/Lvz+g3wAAD+QEvh8Y1P5ca1VqcWVFVjTdzqb2MhVOVM1UHuwzvyd3CD4sXco3MCXIj26Hq3Lyre/gmSbJH89z4xSII/nM2VbDNXANXCCG96ZKewDLbjDijBDAFagqvRJjjJc+eLq/ncQR2a7tbd6Iphbu648qO0DE12ZZYFHl3GozMTeAAA"
   },
   {
    "file": "la_resina_06.jpg",
    "src": "/media/projects/la-resina/la-resina-06-1600.avif",
    "srcset": "/media/projects/la-resina/la-resina-06-800.avif 800w, /media/projects/la-resina/la-resina-06-1600.avif 1600w",
    "width": 4096,
    "height": 3072,
    "lqip": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAABwBQCdASoYABIAPu1qrFEppaQiqAqpMB2JQBOgO4Fw2mf7QR9hFGIFyCjm6Kx0rIcjo60YAP6NzlnB9RmRkQDrN/3MsJRe2NV0svew/R87qirrOCBdeAShYFEKB6+/M3Baq13kbDpplZ2PxMJCtn3E6LFMin5HDPuMxefbZrVgEfmwx0WBVEfHjehD5N/V462+bKEbdsIFTw6KE2J2drkQFk3KvgycgzgNhynlgxECImGrHs4ghN1CU9k3dcCJ8SHpTmLxWYGSwTWqkCWA4AAA"
   }
  ]
 },
 "cutar": {
  "hero": {
   "file": "cutar_01_retoq.png",
   "src": "/media/projects/cutar/cutar-01-retoq-1600.avif",
   "srcset": "/media/projects/cutar/cutar-01-retoq-800.avif 800w, /media/projects/cutar/cutar-01-retoq-1600.avif 1600w, /media/projects/cutar/cutar-01-retoq-1920.avif 1920w",
   "width": 1920,
   "height": 1072,
   "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUAS2onNOkJ5QVI4wIr5Q6AAAzJdfw+ARoTvZs2SHc6LQLSlsjVz/Izw+YYrJmpEmgL1kSzYje2PvFPQCHrHyhHzsJSN+kNTOdumdF+yn5MEqK4TJQ8KBkpFICfdjC5MozM+TB/PryjaB8JSnEGuyP67+xQIBOp7LKYXZosAA",
   "jpg": "/media/projects/cutar/cutar-01-retoq-og.jpg"
  },
  "pause": {
   "file": "cutar_05.jpg",
   "src": "/media/projects/cutar/cutar-05-1600.avif",
   "srcset": "/media/projects/cutar/cutar-05-800.avif 800w, /media/projects/cutar/cutar-05-1600.avif 1600w, /media/projects/cutar/cutar-05-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgBEDLIonNkxcBP4AA/pqjgFMhbWGfJ9uHlYI58q5kWZdYiywVUSTrGlaXZPF5NyuzQcy8xQSL8vZ/WyeZamMxjv2ocJQldyxc8f7Vyf9FF8u9PF5701mNu5P6lfOEBYGUe1HpnmRMnWhZV3y+8Tb3/i3JMrJBjJ2+AAA="
  },
  "gallery": [
   {
    "file": "cutar_02.jpg",
    "src": "/media/projects/cutar/cutar-02-1600.avif",
    "srcset": "/media/projects/cutar/cutar-02-800.avif 800w, /media/projects/cutar/cutar-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoYAA4APu1kqU2ppaQiMAgBMB2JYwCsACKKby2rjcML24F8a0dIAPKW3jBS+f4S7jeAWQwNrrxKq6BNE0Aptb0WDAnw8HDL/VS2+bJ3uJ4XoswYpiEODIXoQc8oVxzkfT6Wwbm5QyOs2kIm7rjHvMhIOLHGCsiiuDhy+p4nTi5rY9sORsz4YEciYiYwCgAA"
   },
   {
    "file": "cutar_03.jpg",
    "src": "/media/projects/cutar/cutar-03-1600.avif",
    "srcset": "/media/projects/cutar/cutar-03-800.avif 800w, /media/projects/cutar/cutar-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdMoApCfu8IIa/uUr1KuJ0Vvks4AD81bKfJm3fT0zjA/e87w18UAQKFzNhEp/ElQqUKU9zDQnwfdbEi4sIEEbfAEa9HriSPf2yaLdKTlrSrxNcI1rNuD1Jn7+ms088tttnqdgypSzF/DLZWNHjGkI9bvbdw0nsHInAu+dflNmWmyUqLRnmH8vkfwAA"
   },
   {
    "file": "cutar_04.jpg",
    "src": "/media/projects/cutar/cutar-04-1600.avif",
    "srcset": "/media/projects/cutar/cutar-04-800.avif 800w, /media/projects/cutar/cutar-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgA8840bjcCUmZRREAAP7U0vrQlic5jyMVPNVlyq3ZSjChCzcLj/JVhSIzj5af/PQQI+RJT3zYKQNzk3iVOYMWGSMxRZQiF/OV+x/Jqd3wvPcTXt4mwdd/LabCDwbPV+iqsdlnpVdvI5UoAOFwuSUXmhWLD8L7pMjQgAA="
   }
  ]
 },
 "villa-paris": {
  "hero": {
   "file": "villa_paris_02.jpg",
   "src": "/media/projects/villa-paris/villa-paris-02-1600.avif",
   "srcset": "/media/projects/villa-paris/villa-paris-02-800.avif 800w, /media/projects/villa-paris/villa-paris-02-1600.avif 1600w, /media/projects/villa-paris/villa-paris-02-2560.avif 2560w",
   "width": 8688,
   "height": 5792,
   "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbAC06YwwnCA/SquPOjUNqfOgAMq7Oyr9rOqQwkEtVgZa1KvfPfUMbqvZ9eTGl4ItoklI8DkKAXsFtw4PAxGLmHzuKcb8q9X2/Brop9KxqQGfuvTuZPjZgpjPWEZTYdMqjyyU4A3iQ/k3F+A/kbN5TNreTJe/ls7D7rLLsc3MD3D2mDQ3u88tRFVzIkkvOLtYO0SlgAA=",
   "jpg": "/media/projects/villa-paris/villa-paris-02-og.jpg"
  },
  "pause": {
   "file": "villa_paris_03.jpg",
   "src": "/media/projects/villa-paris/villa-paris-03-1600.avif",
   "srcset": "/media/projects/villa-paris/villa-paris-03-800.avif 800w, /media/projects/villa-paris/villa-paris-03-1600.avif 1600w, /media/projects/villa-paris/villa-paris-03-2560.avif 2560w",
   "width": 4948,
   "height": 3006,
   "lqip": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBQCdASoYAA8APu1iqU2ppaOiMAgBMB2JZgCdMoGv/i2O2rZim84D9NkkYCW5Cz7QAP4efEbsjCg3uVwSL27srIuFfZUx6F0dpa8j5FQALKp9yhw3fWj0ZUqhx+WiRKE8QEx1mJyVafzE3DIG4yEfjPKjouptmfQ+s7T9Ygp9c4TiO0QBceSTkJ/ax8mq0KcIDtjKDJMn9gqGcHtw33fQguAjbHzMesqHlCrYwkv5GZvinQ9MaI8JFopogAAA"
  },
  "gallery": [
   {
    "file": "villa_paris_01.jpg",
    "src": "/media/projects/villa-paris/villa-paris-01-1600.avif",
    "srcset": "/media/projects/villa-paris/villa-paris-01-800.avif 800w, /media/projects/villa-paris/villa-paris-01-1600.avif 1600w",
    "width": 8688,
    "height": 5792,
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYwC2ydwLhFXQEbNY/swjsnqDRmHQAP7J5dIiaXVRry3YXy57ZTN43k9K/ShMATbl1vlVZlqN0yTHWO4XV5QsArlpKjkQbKAZsTXjK9nGQl/hIQH67sWxZRKuBTRmzkFtNFhgE3rASYTXBXG65/b9GUn3PlCoV/yrGZuGV2cXNLvJeY6JpGwypHebLIjj9RjoAA=="
   },
   {
    "file": "villa_paris_04.jpg",
    "src": "/media/projects/villa-paris/villa-paris-04-1600.avif",
    "srcset": "/media/projects/villa-paris/villa-paris-04-800.avif 800w, /media/projects/villa-paris/villa-paris-04-1600.avif 1600w",
    "width": 4048,
    "height": 3032,
    "lqip": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAAAQBgCdASoYABIAPu1qrlCppaQiqAqpMB2JaAC24aaIYDahiVfZgUrKmtz3NCtguaq2mdxJr8kgE8AA/tmw3CJxI1sUh2rbfA7JCfe9tF3T0fySvYTZOP3SDBAw4C5YDx+61H/8EzaRv0Dvt+Edl8hgBxYtr/UlbhgSchE2XTnRm+gkTLH55psk/Yqjnxe1CETuPhLV1QNLnCXVIqeLxX3blZhFMYU8Me8iNqwExYGYY7Ez6ONu7Bxyw6KK/Xa5lZIgmik8LsnsNju0vM3NyVkr8Qi9gPpAuonKMQWfSqwAAA=="
   }
  ]
 },
 "villa-soal": {
  "hero": {
   "file": "villa_soal_01.jpg",
   "src": "/media/projects/villa-soal/villa-soal-01-1600.avif",
   "srcset": "/media/projects/villa-soal/villa-soal-01-800.avif 800w, /media/projects/villa-soal/villa-soal-01-1600.avif 1600w, /media/projects/villa-soal/villa-soal-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdH8GJ/gMsconXft35O6OiUsy4APoNnnEOsahCU2X0MwK6fjna8IstWNhL2EAwisE8Y15msypW0zOjv52QmQkq9Qagn7MVebaVlunBGeb4TWgnPyZb1BZtadege97mbqecCH2RRiUqSxV7OLSiQb3zyTt0Jq1KgJ0w8O1t2Z3xXO0K+KrbgAA=",
   "jpg": "/media/projects/villa-soal/villa-soal-01-og.jpg"
  },
  "pause": {
   "file": "villa_soal_07.jpg",
   "src": "/media/projects/villa-soal/villa-soal-07-1600.avif",
   "srcset": "/media/projects/villa-soal/villa-soal-07-800.avif 800w, /media/projects/villa-soal/villa-soal-07-1600.avif 1600w, /media/projects/villa-soal/villa-soal-07-2560.avif 2560w",
   "width": 4096,
   "height": 2304,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgBCXDvCM0JbPKSl+wAM3gGbdMwbI2ZHIFo5K4J03yzjqLU8Pl5LgdVyBZDlphE1Q4Arw/+NhAzNfyakiAyoPQ29l+HpyvnMoiUDDV/1rm6lcBfM0Yo3ZgBH0AAH+8yy/cybeDlNUioOv86U8XXk9VBr0TCCmH9ByBAAA="
  },
  "gallery": [
   {
    "file": "villa_soal_02.jpg",
    "src": "/media/projects/villa-soal/villa-soal-02-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-02-800.avif 800w, /media/projects/villa-soal/villa-soal-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdIMgCxxWMLYwqIVGkNCoCpAAA99U9BeLQqU89K0tYaWIiRVr+SpkjjlSbhoJLO+gLCJFTDNPS+anikFOLOnPOEzssoBqnf14huN/aUk2A37R0I2Uz2ok3VAh+AvI4SVBfYGdl7qds3/h1Gt3AhoZJ9utRjhHNqeMG/fgeDOWAAAA="
   },
   {
    "file": "villa_soal_03.jpg",
    "src": "/media/projects/villa-soal/villa-soal-03-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-03-800.avif 800w, /media/projects/villa-soal/villa-soal-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdAB4FAg3w3Xts0H3IsHAA/ueTSyIehDlwbHi49X8cVSEo2Ap68qozj8+Hd8z15cT/24GreCw0oWgSwOkXMAaLDd61HtXaJ53V/DnTx7TY4RLFHdPWVLwT0XtdrOTE8kN8u/hlI9nL3xYWoDXPlf0oKmwf3F3SNOhlrZyfpqsAAAA="
   },
   {
    "file": "villa_soal_04.jpg",
    "src": "/media/projects/villa-soal/villa-soal-04-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-04-800.avif 800w, /media/projects/villa-soal/villa-soal-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdIHGJ/gN84WFXU/9yTxt4HwXAAP3hBRkhaMgzzFNZrDEYKkIyhSMSRJR/YSfZWhO7vhwwXmGq2+1sEz5iwuh0P/QwANbIhEnyMHlZytWgQMC5ynlNR/5dexo9z+Syu20PFwVFlqqRPW5348eC7fVsbdCi2A6A+cMpl4MHyywdTbgzHSe011TkAAAA"
   },
   {
    "file": "villa_soal_05.jpg",
    "src": "/media/projects/villa-soal/villa-soal-05-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-05-800.avif 800w, /media/projects/villa-soal/villa-soal-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgZYJzIWV/uR7CTIl/Rsdem2MAAP7p2EdUCPpXb5mzwGwIffrtIHx/Rk/qxSHHPWbf5ixKR1e5gApL/NSQx/4TD7baBKb2Wr0+h2TZFhrvducgnOmMenBdjNYZKrQwVJYs3/TcKXde8hWUlRLPp6OpZrq1KEoeqzMJHi+WnhgA"
   },
   {
    "file": "villa_soal_06.jpg",
    "src": "/media/projects/villa-soal/villa-soal-06-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-06-800.avif 800w, /media/projects/villa-soal/villa-soal-06-1600.avif 1600w",
    "width": 4096,
    "height": 2304,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQAqoMPYpObFgfI6ARnlXBSgA/vQwZbvmCxtqQ5QDqP44Z/QD4+E/baeqk7LkYkjaGPifTiiP02nBSzZwnzqjBjKmFh/ppMYLwoKLJtu+30j9TzYwCEgE4+B1r7sZioRgAAAA"
   },
   {
    "file": "villa_soal_08.jpg",
    "src": "/media/projects/villa-soal/villa-soal-08-1600.avif",
    "srcset": "/media/projects/villa-soal/villa-soal-08-800.avif 800w, /media/projects/villa-soal/villa-soal-08-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZAAAPvA28IyVCY1rX7WAAP7c9I24O87g4OzBbEuvAk2pvGHwHa5QIF9b+ex9Ly2M9CFHAGn+Hfa+M/xNwyB8TiPNktf3FYQUroKTTs6LgAquyN59B18edQy7fLkG6pip746yqNXoFKJl8CW4fbo/JNBT3tf7I8lx15GdB0TOgz/AAAA="
   }
  ]
 },
 "orion": {
  "hero": {
   "file": "orion_03.jpg",
   "src": "/media/projects/orion/orion-03-1600.avif",
   "srcset": "/media/projects/orion/orion-03-800.avif 800w, /media/projects/orion/orion-03-1600.avif 1600w, /media/projects/orion/orion-03-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdEftgG76SLSaZhD1V6AD+wFEKJAwGSOIV0C0HQ+nD8migo7oMprz4ghBILWFIqXV/eP29Q8XHnprfVV617jkNq3WSBh82BwsNKpWKRfVu0L3z0aWG4NdOPL6a5pqG7B62D8WaatZS3Xs6yzv8QkhvjL76dRCq2D9+oOIAAA==",
   "jpg": "/media/projects/orion/orion-03-og.jpg"
  },
  "pause": {
   "file": "orion_04.jpg",
   "src": "/media/projects/orion/orion-04-1600.avif",
   "srcset": "/media/projects/orion/orion-04-800.avif 800w, /media/projects/orion/orion-04-1600.avif 1600w, /media/projects/orion/orion-04-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOj+ABZgjw1DZoMOQYYwAD+pZAr11Jq/viDgYWUuGkv7wXaMAyUl4xOrKKCgyyv5g4xwE8RKu1McPvsNXxmIYuAwaAL8YRuRgswmU/5EB31DljsE862nOdVFPYG0C+FeLR6EKYAAA=="
  },
  "gallery": [
   {
    "file": "orion_01.jpg",
    "src": "/media/projects/orion/orion-01-1600.avif",
    "srcset": "/media/projects/orion/orion-01-800.avif 800w, /media/projects/orion/orion-01-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZAC7MoBOAbUMkMuBJHhGY8R0APk7sD+m07ujACs0Z7fXKUXHhK9o7lw1Q7GlKHtI80oqlaRA4rDHa3KP117AG7wX52rpLqMkKyJbfAzG2uLtuXOHeWb7L2AnI8bi7EylsbbV4qPAImDwlrUEp6Ir7jG8xP2yteEp3Nt9BnWReucXPAo+YbzFSB8LWdtN778m8T95iEH0kgAA"
   },
   {
    "file": "orion_02.jpg",
    "src": "/media/projects/orion/orion-02-1600.avif",
    "srcset": "/media/projects/orion/orion-02-800.avif 800w, /media/projects/orion/orion-02-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JZgCsICXgvhAg+eYO5ufZlpgAAP68dCTgGYl1kl1fLzZhWaEU3Ekwb1LAGA6+zFEgszryfxnHvw9vX0Ld0DaF/Z7prT7u2uEf9JREBZ8vVVGEWdtZ4DfPsAHnySqiLhJ+O2gAAv85UCJVcQumG9GwQV+3LHyJDkOdd40d8Nh7YXTDcGwe/DVFFFse52VUuLVKHo8jlGY3fS3drRAAAA=="
   },
   {
    "file": "orion_05.jpg",
    "src": "/media/projects/orion/orion-05-1600.avif",
    "srcset": "/media/projects/orion/orion-05-800.avif 800w, /media/projects/orion/orion-05-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JZgCdAAyfTvxTFZtNMAD+zgHWDayWUVuSmcB1nuwNXNZFK3aWt4/trwEY3mOVxN2HjIakJjuk0OvZqeMp9pMRl3YSJVnX82LLDwC2u1BohFudNXOz21xLJB51BLjAXklrBBzjr7SuTEGMKfN3nfzvoZIqUMgCh6QIq4ZfHFCN2vC5eAAAAA=="
   }
  ]
 },
 "la-montua": {
  "hero": {
   "file": "la_montua_02.jpg",
   "src": "/media/projects/la-montua/la-montua-02-1600.avif",
   "srcset": "/media/projects/la-montua/la-montua-02-800.avif 800w, /media/projects/la-montua/la-montua-02-1600.avif 1600w, /media/projects/la-montua/la-montua-02-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoYAA0APu1kqU4ppaOiMAgBMB2JQBOgBB0vz8LkB3enG9QAAP66Zi4cyMfitHy8mEHE3Ev5vMTWZ7vf+O0eTM8vwyLdhOrpcDZlXcTdTKpo5sf9ld2JwAvHZSbsPDVukhoAcOySGPYoagvlxrnRK+Lll7ZCn1jMI1IRs5Eough0j+AA",
   "jpg": "/media/projects/la-montua/la-montua-02-og.jpg"
  },
  "pause": {
   "file": "la_montua_01.jpg",
   "src": "/media/projects/la-montua/la-montua-01-1600.avif",
   "srcset": "/media/projects/la-montua/la-montua-01-800.avif 800w, /media/projects/la-montua/la-montua-01-1600.avif 1600w, /media/projects/la-montua/la-montua-01-2560.avif 2560w",
   "width": 6688,
   "height": 3764,
   "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUABbKfbbtMhQ90L2DwAA/tYNIAXQVJstr/zh8sfvL0VtQhiV8HjflUUhsu81irF0Bf/w8QZF4lRdv7ijXGHsuPey+39qsDTvxdiWVsQnmz0j+fsgM8OpM74gVKAxEXISAveq5CAA"
  },
  "gallery": [
   {
    "file": "la_montua_03.jpg",
    "src": "/media/projects/la-montua/la-montua-03-1600.avif",
    "srcset": "/media/projects/la-montua/la-montua-03-800.avif 800w, /media/projects/la-montua/la-montua-03-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMoACfdMsyRVb8L+PjoAA/tPktqY/HOubm7nERlDl+NMMIu0u33TrahPOE36o2S1+ZJLlUOPsaiBK/DH7Qqs4yJkwKz71+wA8q7xyUt3MXi4FMbB3oPg+rz5xZGwl23dyMoJFEOeOP2+xeGudUQwbZLsHcCx2yiI1IGZ+SfgAAAA="
   },
   {
    "file": "la_montua_04.jpg",
    "src": "/media/projects/la-montua/la-montua-04-1600.avif",
    "srcset": "/media/projects/la-montua/la-montua-04-800.avif 800w, /media/projects/la-montua/la-montua-04-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMipgf4D6K9dctA6aKJevAAD8iPh67Lp9Rq2i4VjHxsvFGFrh0AafLKByKlzkwxEwvGhdy2SK7hQzm2tZZdj45qnBGEt8bAOn1BtCFXPFyc9nJopTdnt86MR/Us9lSSwg+tOLAUlcTy0+YYCORHlPZRIYRwHwvxnmYtHAAA=="
   }
  ]
 },
 "villa-alcala": {
  "hero": {
   "file": "calle_alcala_4_02.jpg",
   "src": "/media/projects/villa-alcala/calle-alcala-4-02-1600.avif",
   "srcset": "/media/projects/villa-alcala/calle-alcala-4-02-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-02-1600.avif 1600w, /media/projects/villa-alcala/calle-alcala-4-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCxAkAbn+AozSZUJoZKC4UwAP7Q/1hn7XjjHO286zZOKHNdegdsPQg9zMLQ+Pe0HTYYSaaBpbWwO0CAIZpCeHLz6QfBPm4C7kNuQFiJZiMkLxJAMBai4Epm9LbohRAPGEiY/upEA3bpa8evntXAj7mAw25epxKHj9HQAQ9lsQAA",
   "jpg": "/media/projects/villa-alcala/calle-alcala-4-02-og.jpg"
  },
  "pause": {
   "file": "calle_alcala_4_01.jpg",
   "src": "/media/projects/villa-alcala/calle-alcala-4-01-1600.avif",
   "srcset": "/media/projects/villa-alcala/calle-alcala-4-01-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-01-1600.avif 1600w, /media/projects/villa-alcala/calle-alcala-4-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdMoMxgBKmke467bFGAAD+6f/8u7PqEDZRfChNygMy4wntH1L/pzvI7VjQyO3t3erNeMZ1O8l6+s9ueupT2ipEx+2HlqzZpPfNsIoVfO19VOHW5hWIekgE4/KQT+XFvGdwTcM6UlpTeB7pZwpcRyxsAAAA"
  },
  "gallery": [
   {
    "file": "calle_alcala_4_03.jpg",
    "src": "/media/projects/villa-alcala/calle-alcala-4-03-1600.avif",
    "srcset": "/media/projects/villa-alcala/calle-alcala-4-03-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgMY2WZaKf9L8p6kYQAP6hRkDg2ljtMJDiDn2vRB7vVNfAaorAODHY86klXTIogeqToCaYHmwqRpgsOOqejXtVGERvMYsgO3mISa1HL8y7VIQ4sC5GUH9/aIL0Ycvz/qHNCjo3RhCKUpN1NI0vn/kMO4zd8xN9lYzofemn5Av18VLiAAAA"
   },
   {
    "file": "calle_alcala_4_04.jpg",
    "src": "/media/projects/villa-alcala/calle-alcala-4-04-1600.avif",
    "srcset": "/media/projects/villa-alcala/calle-alcala-4-04-800.avif 800w, /media/projects/villa-alcala/calle-alcala-4-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOkBLhgcavJiGB+o1PIcAD+sUWbLW8eEu1T7uMfi3a8+geG8AW27XnB5bwFJpnQYwOCVqDoGSkKvcZQgBv/zZOaMd2obIS7iEQrnEgKFMMtC9N5eYL3J2wQwHw6CHM22onah4zfjt79lZNvmJpIU5J9vtVqgMysAA=="
   }
  ]
 },
 "villas-in-the-landscape": {
  "hero": {
   "file": "parcelas_p8_14.png",
   "src": "/media/projects/villas-in-the-landscape/parcelas-p8-14-1600.avif",
   "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-14-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-14-1600.avif 1600w, /media/projects/villas-in-the-landscape/parcelas-p8-14-1874.avif 1874w",
   "width": 1874,
   "height": 839,
   "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JYgCdAYv+7Ut5lRzkHfeQgGcoAP5oTyJMd3eXdhTtMMtHcmYe4y5pSu/ykUvpnQjrPWSXiL5r6OPJebDe8gAbmzJWdagEHbPeXuDsGNLyKDQiLGet0GVD6Sh/T4zXGZCuE/OA8oWI56Z+3aF9PSK753pCPRj7OaFXLzKZ5TIz+QgS6bjKpAAA",
   "jpg": "/media/projects/villas-in-the-landscape/parcelas-p8-14-og.jpg"
  },
  "pause": {
   "file": "parcelas_p8_01.jpg",
   "src": "/media/projects/villas-in-the-landscape/parcelas-p8-01-1600.avif",
   "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-01-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-01-1600.avif 1600w, /media/projects/villas-in-the-landscape/parcelas-p8-01-2560.avif 2560w",
   "width": 5332,
   "height": 2771,
   "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JZACdIF5J/gPGSKtshYUy1x8JEAD+W9SWq0FYjrsysPB745czDMh+XFrtSg89lOg7vjdMRprTwjPkG7CeJ6dxfA2aUwgw30Bo77FxGy+UFWyDD8sYhdixbGYfsbrs3oTHkNIAAAA="
  },
  "gallery": [
   {
    "file": "parcelas_p8_02.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-02-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-02-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-02-1600.avif 1600w",
    "width": 5464,
    "height": 2860,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoYAA0APu1iqk2ppaQiMAgBMB2JZgCdEf/gPJPO+a8kel9oqAD331AeEJhhNRa4BPMfIdj/NMpjwOCxEO9BG2qeeDoJ/I3raaC3v7guKkP0yEEmvZ+1TSMwEwsEYMgAAamABtEW8lu9md8Oig0PfUub07u6UGBQIDo1ZtDyYQm4Oa7QTJAAAA=="
   },
   {
    "file": "parcelas_p8_03.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-03-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-03-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-03-1600.avif 1600w",
    "width": 5464,
    "height": 2920,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMoCGeCAUDFDh238Kelr/AADr74HlbcYQSAVLcc57G3aUeXHKxX/UHAj6Z4JxjcyBgeLkCYxGYjW0+Gz7qj+tYQXppnOppeOL2WaJ/LWe/ke8qUQSKKILCXNCAAA="
   },
   {
    "file": "parcelas_p8_04.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-04-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-04-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-04-1600.avif 1600w",
    "width": 7796,
    "height": 3228,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYAAoAPu1iqk2ppaQiMAgBMB2JYgCdMoACJJHwcFLXs2V6YAD+feChmNSwEQHL3uITHz5Y7hxa8kZYlfLZMrscx04Ev/zGw3ZI5umGI1OkYkq/E/f+TnrBIrn7tGwm9IwRiQNE938AN36J9FQKeCUq9tNPkAx6AesKBcOiA21Z10firLlhYAAA"
   },
   {
    "file": "parcelas_p8_05.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-05-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-05-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-05-1600.avif 1600w",
    "width": 7932,
    "height": 3172,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoYAAoAPu1iqk2ppaQiMAgBMB2JQBOmUABWu3+JUjTbBeQcvUgA4nZPi4pAhbT8QTwDL7TW6del/MS1p6Ikxq27XDoy7dLVoUFsZT/5i0z9Jmva3X27d/lzTLHSlUsfApUDVobRDsIVOSJoFhITiuj+fZUqPs8kcCtT+jWox8oDhOMBBAAAAA=="
   },
   {
    "file": "parcelas_p8_06.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-06-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-06-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-06-1600.avif 1600w",
    "width": 7096,
    "height": 3548,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JYgCw7B6t9/0LLNjHPzNTAADeU5sI7qHKRfUIVonfNjuZVE/hsIz9AtdgRkxvf9ux57d9kpSB/BhAzaLS3GpzXFYQSVFg06T9HleBvtpXU7e1Nj+AmOIIqNKkl0l5XjizW98/dNsTbmnGhqPLJZwZwJChTAQqMSf3BtKITAafJcjQAAA="
   },
   {
    "file": "parcelas_p8_07.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-07-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-07-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-07-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUAS4ow+W/Kz+hwAhNF9gAP6F32kVzuJ5YFC5axC0WcmYaGN5c9DAOl32WZth4iD9CzHhpXGVEkjPKJjHCgvlE/JeERs4uqb3GBs8gspiidlxH29A32vOJFIQK9DfoLUuT+ERCoVaHwIAaJqn51Ja6P1oqVZ03KB8QJ7+7n4wIuAAAA=="
   },
   {
    "file": "parcelas_p8_08.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-08-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-08-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-08-1600.avif 1600w",
    "width": 6688,
    "height": 3764,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMoACsgdqn67lOnS9OpwA+orejjfXbMmGqprk08orDgBFxl7xfiviW6CEfle5ScZPYAUxuidW4yU3ULJldulB4Hv6/kC67h6Xq+SkHUD4oNq5/aWq/LOvmnMuW0UjydQTaQ+hvbbIyk4KQ0Arg4uLuKXOHr6ueOHTjgwwxnQLtvRPAAAA"
   },
   {
    "file": "parcelas_p8_09.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-09-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-09-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-09-1600.avif 1600w",
    "width": 7436,
    "height": 3384,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JQBOgMYdWhkCnRLr1v8fpZleAAP13m57BPZ0nHXRfjQdQgpk2lshy4RMPkjSCXb1+0dLuH40qZr/awUt2nDYGVk3I2uQW8yud0Sbsit6eh+BrE6YvdNewyxsP88Rjm3Se5/dgPtWQQCyeGzwEV1o7omN4eYQ5H2HPGxG7PAAAAA=="
   },
   {
    "file": "parcelas_p8_10.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-10-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-10-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-10-1600.avif 1600w",
    "width": 6948,
    "height": 3624,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOmUAS3wwNZ1Akze3jHp6igAAD9UEQRe6Y6BqoL4WGLTXJKzbM/cd3ysLzCTpS7P3y9p6FuwJk/DKY1++MzY1lv5DwL4fTY8CtA4tUiCOZ0kViad1+ZH7Hh4ESFt1MvVcNQ1/zvLx8NG6q50kfbOVj19Khsa7WHnyWEZU3vLvEAHRGyBc9hC9lzbgAA"
   },
   {
    "file": "parcelas_p8_11.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-11-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-11-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-11-1600.avif 1600w",
    "width": 7376,
    "height": 3412,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JQBOmUAA6C+lAWyao0AUtAAD+v6Mj4KKSoueocFfZMAqHJW1B2fPsvnrAfr8hPHHmnVJa6R/E0xkJrLrOG+/3vHQyj8S1MhX59Kz3feDK9EhGDmKMX2Qb1MsFuVPch+735qIVU1deVt3jwqPDNTw77vzvC+cZL6XoyiXtBcAAAA=="
   },
   {
    "file": "parcelas_p8_12.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-12-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-12-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-12-1600.avif 1600w",
    "width": 6756,
    "height": 3724,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoYAA0APu1iqU2ppaQiMAgBMB2JZACdMoMzGDudDyfp/JTf1UAA9Au+8kjurrq4Vy90u5akPOnfrRrMsQKsFMHqJDUGjUxAnlXAOSn0AtGeK8aiX0S+A3aTrSVXCX6q7YdgsBeeEsz0wna02JZjBlifKu50Vb7RvqHgE/1IXWBwX/Fs/+tM/DDo5SAAAA=="
   },
   {
    "file": "parcelas_p8_13.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-13-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-13-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-13-1600.avif 1600w",
    "width": 7504,
    "height": 3352,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBACdASoYAAsAPu1iqU2ppaOiMAgBMB2JZgCdIDZC49Mm8N8DcivNzgAA97HH8sG4b6bayFwqYVx+LKtjqdADeAXTaHHaY8+ah7bDiPgiXFx59ll0g2PAsdTg4FweVStRaEi0U7ZV/jdTvl/9wh5lhlOZ2bEgPhyoofGfavwRb4Wxn9NhGADtSduhSyNAAAA="
   },
   {
    "file": "parcelas_p8_15.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-15-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-15-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-15-1600.avif 1600w",
    "width": 7500,
    "height": 3356,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYAAsAPu1iqk4ppaQiMAgBMB2JZACdMoADERPd2xs76Kv4am4AAP6FnrnFzSuSbn18C37Fl3GKufFjqW4fArLgm+13lVevVMzW4TiLElFDCQeWYhmz5ojw7zXYJ856qfUIAKF/vM1FwYYUIXQJOqXp9mxkxbOdQvdmFtKBPfutx5gLZei6/7AYMUD21jQIQAA="
   },
   {
    "file": "parcelas_p8_16.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-16-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-16-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-16-1600.avif 1600w",
    "width": 7520,
    "height": 3348,
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAACQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JaACdEf/i1+m9I2MgbCnopfYXMAAA+OTvYuwOgvyuM2/JtRCdLePN++YWRacwOKZTrldahCSnn2HHYXL6nQuxyLtB5RsdT3UIVSGcG6Uc6e6wlaMkeo5V+26IY5Ks8CcE8OzIfDzCbH3Td47+xWrl1C4W2U7bfAitQy61nNY8gYD1updlxL9yfuVrUGM0v26TVAAA"
   },
   {
    "file": "parcelas_p8_17.jpg",
    "src": "/media/projects/villas-in-the-landscape/parcelas-p8-17-1600.avif",
    "srcset": "/media/projects/villas-in-the-landscape/parcelas-p8-17-800.avif 800w, /media/projects/villas-in-the-landscape/parcelas-p8-17-1600.avif 1600w",
    "width": 7492,
    "height": 3360,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoYAAsAPu1iqU2ppaOiMAgBMB2JZAC7Ef/gPppTh3rKU63hAJbqWAD+fnNeC/IHZ0R7o2cbAv9UE7xS9miVfQtIy3q7mQSnkQmMB26K5m+sk4N22PvGrVu0e1iDyZWtk4+8BpvBfzgHyV6E/f44T6zxqZY5NpQaaHSt9cseb/8KQQe5O06exfxcMMGdof5LmrFK/IPFYAA="
   }
  ]
 },
 "the-villas": {
  "hero": {
   "file": "the_villas_01.jpg",
   "src": "/media/projects/the-villas/the-villas-01-1600.avif",
   "srcset": "/media/projects/the-villas/the-villas-01-800.avif 800w, /media/projects/the-villas/the-villas-01-1600.avif 1600w, /media/projects/the-villas/the-villas-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgMX/Wsd8BfCRGG4Vv45nYAP5m3aaipMNIxz+KwznClq8tSuEooldnJmGpeOocaXJ2ZD7zherITTeSHxcCSB6dogCZhFkVb+78LjJiXwPVOozc0t+91SnTvuP2T168cAGxS7Vbq7zTulz6tSRptfKP3qeVT1uRLkt8Jt+YH3whFhKVOFXIkEGBMQAA",
   "jpg": "/media/projects/the-villas/the-villas-01-og.jpg"
  },
  "pause": {
   "file": "the_villas_06.jpg",
   "src": "/media/projects/the-villas/the-villas-06-1600.avif",
   "srcset": "/media/projects/the-villas/the-villas-06-800.avif 800w, /media/projects/the-villas/the-villas-06-1600.avif 1600w, /media/projects/the-villas/the-villas-06-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoYAA4APu1kqU4ppaOiMAgBMB2JQBOgBD0TmgOKq4t6xZHl+AAA/rIHqqq5I4PA6tt+sV79jqCTs8eBkoVVLcOVmVDYvuZUvqfq9w7lBPqy/kbkaDg4Cr7QGg6GQWWjFjSkBQj1O2fpszDAWEMFCuuoMkcZ5l1y9Xm742qUoIQZpjd1dY4AAA=="
  },
  "gallery": [
   {
    "file": "the_villas_02.jpg",
    "src": "/media/projects/the-villas/the-villas-02-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-02-800.avif 800w, /media/projects/the-villas/the-villas-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgMY7cC0XKjsFoDrNEVs/HOUAA/lv87e1JqRHFwKGQKIkJMQUv/pIL9yVPGWTKfMUiqxuPOMFq13iXKVEM7elxPRIDuxB69fzvLwNQEjos/J6Hy102c8jfzSvvEkPbI30th3xbOozFDqwDzwn8Lf9QtSx1fOCK5+dd2f1NSYqtQYLdqDBeIWkZBAAA"
   },
   {
    "file": "the_villas_03.jpg",
    "src": "/media/projects/the-villas/the-villas-03-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-03-800.avif 800w, /media/projects/the-villas/the-villas-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdMoAlwxfNQ5c8OjVO3VezsQAA/u2dj/kOVW8scu2or4bZ1NTFytey5IF/UqkGmtL6iYBjm9OtY7hGVnu0z503rOojaLhbDCsCQt+1T3+8L19Zw/IVGG6q28IXbjuUdmtLhinP/v9ugPV9DsbkAJhhx9t6wj7KLBGNt9HtBztmmazmsZsTEat1zzNL6cAAAA=="
   },
   {
    "file": "the_villas_04.jpg",
    "src": "/media/projects/the-villas/the-villas-04-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-04-800.avif 800w, /media/projects/the-villas/the-villas-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdABdL6+pRASeyU2xdywAA/urbikPr1G9Se5kcmtuThs2NuKqftFZ9a/aaKXTAjXgHyzS6CTlX4bWhGfNMsvNXi5mtuDqJhsfZdLByHDFek2qbO+gBPLchBmQdV8tJXtx/S4gOL2CGQ+4glMukLHUeQOSACATWz8HWLgSAAA=="
   },
   {
    "file": "the_villas_05.jpg",
    "src": "/media/projects/the-villas/the-villas-05-1600.avif",
    "srcset": "/media/projects/the-villas/the-villas-05-800.avif 800w, /media/projects/the-villas/the-villas-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQBdgA3AjXmXR4U/Y7UEeAAD+79eLWfLdcSxuH/XK1jiubfmsT6I+bqaOQ9spgiRq61TzdIh7f+HAQc7TfHkhtxGSrTIX1se91ilunz8epmXMpvxFwq2oAbhTcHAdugFlw+fPzHCJl1Bgt2oMGC8LEl8JydQmgAA="
   }
  ]
 },
 "altos-de-los-monteros": {
  "hero": {
   "file": "altos_de_los_monteros_04.jpg",
   "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-04-1600.avif",
   "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-04-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-04-1600.avif 1600w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-04-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdMoMYA0jZ2wcZTpFrivRCQR4thAAA4n3fBjfCpL0i8NEq5oc/BynACRBW++naz8I68KdsX8IxRfV6Y6IujhnwfgBEU8vt8hqe6imL4+64dOeLJ8iUEgyD5+cak9n4NpFpqwf5G8XlSfSz/JIXEKxX+XFNv1/FOm1TB/c5i2ruAw6upcu5oAA=",
   "jpg": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-04-og.jpg"
  },
  "pause": {
   "file": "altos_de_los_monteros_02.jpg",
   "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-02-1600.avif",
   "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-02-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-02-1600.avif 1600w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-02-2560.avif 2560w",
   "width": 5472,
   "height": 2918,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoYAA0APu1iqU2ppaQiMAgBMB2JYwC06CHhQhsVJbFHx+IRkbQAAP6B80s39nPSzkLTTNnE0lRIv2DVW8sLkF6qsZcRooe7WaThA7wjUx9vGjXJwCBHuEVq9Xow9Wvm9lgdrmb3ubMZkW40GfPufj9ngIkYl7LcDdUIj7WywO0gI5XxQRJBzgAA"
  },
  "gallery": [
   {
    "file": "altos_de_los_monteros_01.jpg",
    "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-01-1600.avif",
    "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-01-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-01-1600.avif 1600w",
    "width": 5083,
    "height": 2523,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoYAAwAPu1iqU2ppaOiMAgBMB2JYwCdAB7HfrC+1CK+W4Cg39AAy01y/kqn85c8n29KOC6iCNFvbav5Fwzx9r/a7MKsRT3cMv7nAPQHj/8UCRmyBfVzQ0SL7+pvDB2+NmuKhW/+8GGF/D/dby1j0ybEtcyyQRVnVJblOB8L+wAAAA=="
   },
   {
    "file": "altos_de_los_monteros_03.jpg",
    "src": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-03-1600.avif",
    "srcset": "/media/projects/altos-de-los-monteros/altos-de-los-monteros-03-800.avif 800w, /media/projects/altos-de-los-monteros/altos-de-los-monteros-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JZAC7ABPpu6zPUCuwTkugAP7v2MgtWLWX/eqEMgPnlu9OrgqRY90xzIrUaVK9wx0YQk1VmQFTDfKwh5veGkf2SPEmrgVu2AzjhW44765rI7MgmIerCbcL2Bss6XKenduUj5zyIlIkx561WULqjzP/LFUqV7bhQmm8XQZcAdl4amPsQgImj+rrjre9FEfQqQMCgAAA"
   }
  ]
 },
 "villa-feliz": {
  "hero": {
   "file": "villa_feliz_05.jpg",
   "src": "/media/projects/villa-feliz/villa-feliz-05-1600.avif",
   "srcset": "/media/projects/villa-feliz/villa-feliz-05-800.avif 800w, /media/projects/villa-feliz/villa-feliz-05-1600.avif 1600w, /media/projects/villa-feliz/villa-feliz-05-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADQAwCdASoYAA4APu1iqk4ppaQiMAgBMB2JYgCdMoADDECm4V5d6SAA/mm/1SH9GAjaVphHw8cL6JgJJnAkGXT479FfChnPou/LgzMfNXUOEfpUBfElpLFYCuZv35NPtMqjMD1/V3q/MN1VNEn84QrS0XTDs4In1C2CyiaCAQaKk50gBkFp8eqaJWPXkMUAAAA=",
   "jpg": "/media/projects/villa-feliz/villa-feliz-05-og.jpg"
  },
  "pause": {
   "file": "villa_feliz_03.jpg",
   "src": "/media/projects/villa-feliz/villa-feliz-03-1600.avif",
   "srcset": "/media/projects/villa-feliz/villa-feliz-03-800.avif 800w, /media/projects/villa-feliz/villa-feliz-03-1600.avif 1600w, /media/projects/villa-feliz/villa-feliz-03-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoKAAHpDO6/aMfh/mUxLXTdNAAD+4HZg/wKKHXTYurEIifZ6+/GVyUPWLMb+zuYJC/owsyS14JPdmfAhJ+gzKXAOthX8em8vXu/OVdJKJp1uTCPKKwpwhUqymQHHTvvwic23EJYTL48+ylRFja7zdAE/QQikAiU51+ze43KQ1DkXh545Pmjf/ycaYW24H0slOlGxQAAA"
  },
  "gallery": [
   {
    "file": "villa_feliz_01.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-01-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-01-800.avif 800w, /media/projects/villa-feliz/villa-feliz-01-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQAqP24WXLgWFtHhUgklg+8rAAP7prQ4xmSZNNqv7xxwjX0jJ1a19liXalLB60Aubd9Z9hmA62CTpchOU157Kr82hlIzwGhyA+7N2JlPe2ozB2Jt4TvZuBJwcLCN2Nu7EA7nta1gaFxfOLmJyKsPQcXbGQNFZSdSsv5mAGBJdAAAA"
   },
   {
    "file": "villa_feliz_02.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-02-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-02-800.avif 800w, /media/projects/villa-feliz/villa-feliz-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgC7ACbabPxpqSeWLXJycvW8QAD+qIHnaRqbbol4aKdMOufuG2SSdxaMCQ2KYuG1Zvs9wwnVTz4eGhcGxxRUMEvBgINfAQypBpnvGCVvgSMwXsv5wu4q/4wRcFqFz/GZ4c1qvEpgT8pakpKAlQOPlZO3NQG/lfiphU0W/ZIXUnYVwAA="
   },
   {
    "file": "villa_feliz_04.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-04-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-04-800.avif 800w, /media/projects/villa-feliz/villa-feliz-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYAA4APu1iqk2ppaQiMAgBMB2JQBdmUABfhKUmhydV5ICigAD+8YCWmdWzcgEoYj/v0GvsmJa1oy+mS8dLxzd42sMJz5vxR5vTE/KnU6Kw5cJwR7A5NIyGn2ckdw88dYtCdKm7ruFPeDfcSLQ6HAGiZ6W4XZztwWkPG1SLY3Ssr/hI3rI8akTtpelwgAAA"
   },
   {
    "file": "villa_feliz_06.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-06-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-06-800.avif 800w, /media/projects/villa-feliz/villa-feliz-06-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JYwC/OCHrGt9xg89+pmSq79AA9j35oG2AYw2/ZeHmwzqIOZZG2CMWtMa3U5xb+niFlc+yJmrsI6FcqLCB37Rs3Yex+bDY+nBqq9IhNMSEG4hX2ZBXRT1bxGYeuqzgH+dQfSW/5wwx/UhEbUoUeZWstBHkn9eraCo5yQIdHzGwn4tYEJywAdLAAAA="
   },
   {
    "file": "villa_feliz_07.jpg",
    "src": "/media/projects/villa-feliz/villa-feliz-07-1600.avif",
    "srcset": "/media/projects/villa-feliz/villa-feliz-07-800.avif 800w, /media/projects/villa-feliz/villa-feliz-07-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JYwC06Bel0+DxZM+mjECoAP7pTzSplhCprjxnTQof1T3giNQeviZCQObvDS5yAkchyinotB4LqVCOJqu8vwcZMHXOzrSiibTAkO7Gk7k+u8wSTxusB23D+TtptHG5K9uidyxvZW00pXbQkzCbkC7DQX1Yiz4uC174poAA"
   }
  ]
 },
 "bleu-royal": {
  "hero": {
   "file": "bleu_royal_04.jpg",
   "src": "/media/projects/bleu-royal/bleu-royal-04-1600.avif",
   "srcset": "/media/projects/bleu-royal/bleu-royal-04-800.avif 800w, /media/projects/bleu-royal/bleu-royal-04-1600.avif 1600w, /media/projects/bleu-royal/bleu-royal-04-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOkCYhgY9M4aqoiqOqkB4AA/rI9wB7e33i2GLfhKHpEmGQoE0E6DDoGQNKgJ/Hvpf3fCMIM72DTOhc4Se/vSfEBqpxFyB1vQIE1EcczFo6PY6usjeEbDNAbJENCLovAPlYECzlfR/jp9e/bNocbPeWneAAA",
   "jpg": "/media/projects/bleu-royal/bleu-royal-04-og.jpg"
  },
  "pause": {
   "file": "bleu_royal_03.jpg",
   "src": "/media/projects/bleu-royal/bleu-royal-03-1600.avif",
   "srcset": "/media/projects/bleu-royal/bleu-royal-03-800.avif 800w, /media/projects/bleu-royal/bleu-royal-03-1600.avif 1600w, /media/projects/bleu-royal/bleu-royal-03-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgC7AdwLg7Tk+mDb8JJFFtul3TAAy0xe7wLfnJytCmROnUvOjuyVxcxPzIj+86nXyoRbSd1SNIHd29pF3XqoRUw2cRdYkG6SVDl/RLO6rYDepszFO1Zh4G5v+wBvwI9fxENSh+6ATzdNtHJz2HXOIKkNjOXiNw/qKD5ybexGM2aV2Sf9tKFOwAA="
  },
  "gallery": [
   {
    "file": "bleu_royal_01.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-01-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-01-800.avif 800w, /media/projects/bleu-royal/bleu-royal-01-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCdAywYYA0GeS+3bUPJ7wjcAAD+s5IVvuUd3iP2AVd0182xVERopJODewuJ6oNQ/CWrUYRfxYAgKRVsNmIfLhNEQHLKo1td+X+8XbuXYKKFEA/WagKK5McNISqghNHWssMtOMkH87w8onjOzpAQ9qMvAAAA"
   },
   {
    "file": "bleu_royal_02.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-02-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-02-800.avif 800w, /media/projects/bleu-royal/bleu-royal-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQBOmUGQ/T/i1+hFd+Bc8OfAAAP6zTyRdCYpo49XcahZF2xyPQvqrEl0f8YD1vZeCs0PGZtb3x80VQTXFDUQNNKIOG8onV4aWKZkdX0kuPDXuw2bLHfoWcMYFi7/3dGcdw6dlgEX/qGdW4570lcshcKPPf9dMiETCpapWkBHR06hkekp7rAAA"
   },
   {
    "file": "bleu_royal_05.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-05-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-05-800.avif 800w, /media/projects/bleu-royal/bleu-royal-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgAt7bN/d3HbuIy2fAAM2hYVJWDC/2N2bN8WbLhp4b2A8sRHkjjj9mH2hSxHUIZvhV9+28qgJV/lfzWaVDG05H/snsgnjBirOZJntwpe+epdGOnwWWaAb8j5Kyg42Bitm3FQIaDT5nkSf8UQz061QwCUMDWDdP720jPb762VuSHIyTx6zWKAAAAA=="
   },
   {
    "file": "bleu_royal_06.jpg",
    "src": "/media/projects/bleu-royal/bleu-royal-06-1600.avif",
    "srcset": "/media/projects/bleu-royal/bleu-royal-06-800.avif 800w, /media/projects/bleu-royal/bleu-royal-06-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCdACD/OK/v+2jq/LkgAP0rSbla2ex8zfE6ta2DqaO2/M6fKHeh4/X3ftW58qH9h2Nwvt8AKC35nedEAfpv5Fm96WpKqsS4o/GE6uesS2a1aGsPSo2C31Ftp6LP7DVyoWT9H/N6XvKhjwnJm443xk0tGfic6B1AAA=="
   }
  ]
 },
 "alcala-solvilla": {
  "hero": {
   "file": "alcala_solvilla_02.jpg",
   "src": "/media/projects/alcala-solvilla/alcala-solvilla-02-1600.avif",
   "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-02-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-02-1600.avif 1600w, /media/projects/alcala-solvilla/alcala-solvilla-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgAvaA1wWdtOgqnF/uZ9gA/Mu78GAtLygKk/K+HvUr+gVXJ7g+uh1ya2dB8GTSkQpnsSESgFWrp6t4F/q+aFtthoXNFWiaOfVEvk1sPqkhxoC5Hn4ee/BZ4sL6RUDpvJe6e7NDW8SWQlv43GSYd2/nrEFOO2+UWV04jS0tYAAA",
   "jpg": "/media/projects/alcala-solvilla/alcala-solvilla-02-og.jpg"
  },
  "pause": {
   "file": "alcala_solvilla_06.jpg",
   "src": "/media/projects/alcala-solvilla/alcala-solvilla-06-1600.avif",
   "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-06-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-06-1600.avif 1600w, /media/projects/alcala-solvilla/alcala-solvilla-06-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUGYW6Qw5U7U/mJBjnS+z0XPAAP3idn+GHdqW+H3TZ34yu8TyovgU11TP+tkpqxU+8IhC+1CS/AoXNuurtvMlokLVOZd+n1B1g2x3wEn8/lEvDVbgaxcKkBka245fQpxzJ10dfhS/aQnLsM3yCymfQ/9x6HDBcuuqAAA="
  },
  "gallery": [
   {
    "file": "alcala_solvilla_01.jpg",
    "src": "/media/projects/alcala-solvilla/alcala-solvilla-01-1600.avif",
    "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-01-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-01-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoYAA4APu1iqk2ppaQiMAgBMB2JZQC7ACKmEWYy+cC0VGZAAMtOoAwkDvkzYt7Z6oK7lYqY+QMvYQPAyRoU5YoFXVJy8xI7yMkMuUimR+zjw/zg7PvkpMdB9VWtzGUwOEqAbdqGgZ8bfItO7S9W0caCrP+62+HwIfkPj4dV/zv31aRyqv2rMGloc48KNAAA"
   },
   {
    "file": "alcala_solvilla_03.jpg",
    "src": "/media/projects/alcala-solvilla/alcala-solvilla-03-1600.avif",
    "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-03-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAA4APu1kqk2ppaQiMAgBMB2JZACdINiCsC5uatOeRtLLw4CUAP6wI1PM7xFk/oRCksNgnRGNgNPltmaJBqN903flIOL4tQifiz87ZoVhB9MgtLoW8n6W/9TbUR51jy4KFPC24uDgz48B8xRlbWluYghijoYg9+f59QpjR9sw+ipcc5bSK/nscND+aVJDqArY0dPwCfeWDAAA"
   },
   {
    "file": "alcala_solvilla_04.jpg",
    "src": "/media/projects/alcala-solvilla/alcala-solvilla-04-1600.avif",
    "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-04-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdMoADEb8VXdpBdaDbw4wAAP66UQr/QT0hFt+0hTPNj+idHSncBEW0C50Kz3HM/kCC9Yo1kHp3Njxu9BYZxg9l4em6aFVzgpMUcHvnODotX4Zkd8OUpxfk5OJVlvDHCWc/vC33Yfjmf9+UBCvO5mAqxC7dstoSKh2kDqaeYAAA"
   },
   {
    "file": "alcala_solvilla_05.jpg",
    "src": "/media/projects/alcala-solvilla/alcala-solvilla-05-1600.avif",
    "srcset": "/media/projects/alcala-solvilla/alcala-solvilla-05-800.avif 800w, /media/projects/alcala-solvilla/alcala-solvilla-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUGYwBmpCpxa5XiKA0FNQAP37WoawN6fLn1eBWLqm7jn4eqs5qvtbAlCL+6MN98O+EdhYEbvb8c64wbvNmnISWoO6UjcVKkigRuXikM+vM0g98vTpa5/bmKObuRrgRZ2ZSHY9u+F0HWBPyqjS8eIhPCvd3v/JhR30AAA="
   }
  ]
 },
 "elviria": {
  "hero": {
   "file": "elviria_02.jpg",
   "src": "/media/projects/elviria/elviria-02-1600.avif",
   "srcset": "/media/projects/elviria/elviria-02-800.avif 800w, /media/projects/elviria/elviria-02-1600.avif 1600w, /media/projects/elviria/elviria-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgtQAv3MYrbYPJIH/iSukAAP2z9eEcJmPzvhm9s9dH9XWBSbRAIMVqsPU0+0gzLgBpGSqbN9Eb/fbTZwHbQEEI62YiZpPBt6ClihrA2NaYxOe4/LY/Jd3fKhgexuTxAuhOF+l3hwr6IgpBuEmD5r6wrXNL4IptcIZ8AAA=",
   "jpg": "/media/projects/elviria/elviria-02-og.jpg"
  },
  "pause": {
   "file": "elviria_01.jpg",
   "src": "/media/projects/elviria/elviria-01-1600.avif",
   "srcset": "/media/projects/elviria/elviria-01-800.avif 800w, /media/projects/elviria/elviria-01-1600.avif 1600w, /media/projects/elviria/elviria-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdAB583XxIB1t3RnopKAD+qOGF3lIEUT9iWdrpr9YXQMKuEWaLD69RCaAPs0q7QnQ97n0/Z2D80bBoEKsXgnOsd/wy3qW/l5OcT9OeNJUGqVQfD2s+9ShDOz1FfwBunRXBRQycf04cT3vKFqjAu5u17NZdqwPpfsAeLAUm1/YBXDSYQ+HK5shXnsmlCzI0lGAA"
  },
  "gallery": [
   {
    "file": "elviria_03.jpg",
    "src": "/media/projects/elviria/elviria-03-1600.avif",
    "srcset": "/media/projects/elviria/elviria-03-800.avif 800w, /media/projects/elviria/elviria-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdIIjC9XfAXtioFBs8oAD+lN1uFBxOgcxb24m/y9Eta1apQegeELQ2imelWqaXp0oKktm4D3CfIgWzPct0sjNcJL0pPRQRyvvrKwPk4Ps9bhmEqtux8nqiZwJ/CAv6k/WamU7T1CorLXOD9mdopwQ276m6Kjdn2s5DVlWKjOaEEdzogpWXELXSPaAA"
   },
   {
    "file": "elviria_04.jpg",
    "src": "/media/projects/elviria/elviria-04-1600.avif",
    "srcset": "/media/projects/elviria/elviria-04-800.avif 800w, /media/projects/elviria/elviria-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdAB3Hw3BGe++LEHU1AAD+b53v6TudcHKXlEsyxZkFQAL7AswQOkduHNb+fVyEZpxb60JljY7bfEFmaKnQApDEl+YmmTsOisD2rIIvTxbQ8H8EvnQUJzfVZ6+I/FRrNyIdFkj+YHy/RI+UlMfZUNXtauHEw7T6LXQvnP9bE8QSgmI2WgJmwAA="
   },
   {
    "file": "elviria_05.jpg",
    "src": "/media/projects/elviria/elviria-05-1600.avif",
    "srcset": "/media/projects/elviria/elviria-05-800.avif 800w, /media/projects/elviria/elviria-05-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdAYye4+7vNYvMqubYlAAA/P8Kv12FgTOOD8Bd5jNccgkJiD8YeJ0z8jZ5CIY7K4LbO+NdM24yKwwkQ5ecax0EvOwSzm1I/RlqtDWPbS6JLyQpYWX8qNE1Bt2Pm+fC//2IDtOxw6MEGTV13CxmMc35LY8gKWyHzH5gv7RHi3S8F0AAAA=="
   },
   {
    "file": "elviria_06.jpg",
    "src": "/media/projects/elviria/elviria-06-1600.avif",
    "srcset": "/media/projects/elviria/elviria-06-800.avif 800w, /media/projects/elviria/elviria-06-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdACFb6exYRT7LDNFYkAD+sVMo3l/7A6EFcGGindwxpg1ExUkcpkK2jbAUXtFdjLYmvCfi8Cqwn0mMzHw/WkhZJkutJOdqatrIYzQOP7BkK1DcgDpPXcZUt8Maopj19EEVtIuNaLbmirlJdEnW/BILMXGqzoqbiIkO0nGT0Si+AAA="
   }
  ]
 },
 "cortijo-nagueles": {
  "hero": {
   "file": "cortijo_nagueles_44_04.jpg",
   "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-04-1600.avif",
   "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-04-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-04-1600.avif 1600w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-04-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBWCP/wICPqwmY6P9oPAltBAAPiyLgCHozjhcV6vSPdkRPUxXmwgEASP3eQcLqS94b8wClThVHvayDza2D+MlZXdaC8oJvtWlLxROgNFEce7+2L2Pd1iczrdLr2eGayYgg3h4eXqSNGVtAMcs3NAM6uHPNO9ISlPT5h3AAA=",
   "jpg": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-04-og.jpg"
  },
  "pause": {
   "file": "cortijo_nagueles_44_03.jpg",
   "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-03-1600.avif",
   "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-03-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-03-1600.avif 1600w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-03-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoGv/gKMypVOTwg3UAAA/eF9L4DZI5NQYIYSSYwsAGP8btpF2BDOfPc2ts6XltQ4NcQq76iIENu6+nsFSqHwIbIb3uO6BvcWR/d7oI4/8kntJmPnHhZe4GOnp79fSx1tdCu17xTW7knfJY9rR+6EQWu+Li2jNPW5AfBNXP1kcRwAAA=="
  },
  "gallery": [
   {
    "file": "cortijo_nagueles_44_01.jpg",
    "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-01-1600.avif",
    "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-01-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-01-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdMoADQjZCLZdrxiqCPJgA/eHqxQEofSkM7QbOECZrC3ugej6SfoBT2dn/Ut63sOoCWT25HnXoM7nZOVQctzNgGdq2rFtEcxNQzlBofvVTqOHKAe2RjweOhrfZ9IaL6sAL4BFLg0/MQD0mP0fsIWxPj4Pe5x9vFj63BcH6hYqIBwxVivGm18z2Ly7ag60dy0kgAWQAAA=="
   },
   {
    "file": "cortijo_nagueles_44_02.jpg",
    "src": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-02-1600.avif",
    "srcset": "/media/projects/cortijo-nagueles/cortijo-nagueles-44-02-800.avif 800w, /media/projects/cortijo-nagueles/cortijo-nagueles-44-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoRwJoADp54MOLHaJayBAzmlAADh/uEhwX7rx6IGGz10XEQ4U2sJjlIk0eJeaVj2PkVIaLtAwDGC80hBp37Z5OsUrZrGtlhZ0gZb+PRsHvEKwmKAYVXVWa4OGGiQf+DfYq/v3MqHq3qrTuIKrubTEPTpv422H+EUareitbcGleTU5fnEJLcPAAAA"
   }
  ]
 },
 "villa-pareja": {
  "hero": {
   "file": "villa_pareja_01.jpg",
   "src": "/media/projects/villa-pareja/villa-pareja-01-1600.avif",
   "srcset": "/media/projects/villa-pareja/villa-pareja-01-800.avif 800w, /media/projects/villa-pareja/villa-pareja-01-1600.avif 1600w, /media/projects/villa-pareja/villa-pareja-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JYgCdAA2KJEvOB2kr6AAA/vFwxKrq48ht7DBJVu5Zzb6kPoHPXTAQ+eZk2ea3PGLQTa7HnIGA7Zp0t1wYAoSpVI2rQayD6acioeK0K65POOE5O1FMCgZ9pHmq6PKuv5XhfOihY9BnaQ3RHIt+auzQBakhsMMIjkAAAA==",
   "jpg": "/media/projects/villa-pareja/villa-pareja-01-og.jpg"
  },
  "pause": {
   "file": "villa_pareja_04.jpg",
   "src": "/media/projects/villa-pareja/villa-pareja-04-1600.avif",
   "srcset": "/media/projects/villa-pareja/villa-pareja-04-800.avif 800w, /media/projects/villa-pareja/villa-pareja-04-1600.avif 1600w, /media/projects/villa-pareja/villa-pareja-04-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAACQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JbACdMoLT/uugLLhI0JuoSraSl+AA/GeRczGJS5vYxsJL4+pP12PU7aat/He1jQVcdBhUjdLQ1ZxPQTttNMt5RsNhAkt4SPt6Y5Artz3cW2eP+facucn203xRgviTfHAPqyGfKHmoZ7mdHfOzDq3UilFO+Srzikf+A1JyWsFWdqEX4EJGjF7e88TJdVLzAogOQAAA"
  },
  "gallery": [
   {
    "file": "villa_pareja_02.jpg",
    "src": "/media/projects/villa-pareja/villa-pareja-02-1600.avif",
    "srcset": "/media/projects/villa-pareja/villa-pareja-02-800.avif 800w, /media/projects/villa-pareja/villa-pareja-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQBOgBD0KMuURdMygAYElAAD+WZK6Gj7nk89hXh5/i1LIxyDJkp230ho0Cds9zZhr1al3N7IJFiDzKlPRfPTGmJ8c3SE7hrl7Zx7vPcMMz7YyUX1ot5ybKj4lU/iqaALglTMLqesfL7KrY5IoLtgQqhjtRAAA"
   },
   {
    "file": "villa_pareja_03.jpg",
    "src": "/media/projects/villa-pareja/villa-pareja-03-1600.avif",
    "srcset": "/media/projects/villa-pareja/villa-pareja-03-800.avif 800w, /media/projects/villa-pareja/villa-pareja-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwCnFCKe8SOPknfxu6hxWUgAzVwaN0LLDuj8PnaZ1RCZK64ARJdCxKpuivSckTJtgvQmZFuxtXM7zBTO0ZrSgiPTnhntcACg7M53odsXYQsS8OeT1jK1zcTKt3YY7XMsMR18qSPE6D7oIzWgC3XyFZQ2dVlI1M5QAA=="
   }
  ]
 },
 "sirio": {
  "hero": {
   "file": "sirio_01.jpg",
   "src": "/media/projects/sirio/sirio-01-1600.avif",
   "srcset": "/media/projects/sirio/sirio-01-800.avif 800w, /media/projects/sirio/sirio-01-1600.avif 1600w, /media/projects/sirio/sirio-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoR4LyAAMyiSD3B5eSOgAP6Q3sjrGbRw5jVLqmeIQ0QLk9PrTRzNPpNyrbq4hEUkx1IOr6lRbE8B93YlAVRFPbgKfPjdCm7FIu/KbmiSGgSrCTQvneGGLhP+VeE12L/fE5mF9wubATa1od8ZUDzvQFRRHK4sRC+Rkz0cmfwbYicP+8jYVAIZiRbLxpYAAA==",
   "jpg": "/media/projects/sirio/sirio-01-og.jpg"
  },
  "pause": {
   "file": "sirio_05.jpg",
   "src": "/media/projects/sirio/sirio-05-1600.avif",
   "srcset": "/media/projects/sirio/sirio-05-800.avif 800w, /media/projects/sirio/sirio-05-1600.avif 1600w, /media/projects/sirio/sirio-05-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdAYyypgaV4SGn2MyAAPHRPrJRMNfEtQlzm71FCmB6RzFXdDbISYnW2kOSevn3aLpi7ZzlSF++6bRdREAvwNQSf+V4Bqk7jXPIwS0OYfGPZey5WWXix6Qq09zt+YO/cCtO1+TZM7aBaAO6S5XxwKJBkLIIXwRU4WUebPdrSuaLMhIKELzWroTjsmJpqnQwgAAA"
  },
  "gallery": [
   {
    "file": "sirio_02.jpg",
    "src": "/media/projects/sirio/sirio-02-1600.avif",
    "srcset": "/media/projects/sirio/sirio-02-800.avif 800w, /media/projects/sirio/sirio-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdMoABcNYJsEpnwswAAP4nixHysmEHjjMl65O8HvfvsLJzlc7U3Hf+T+4pL9nnB9VzFXoqs4fDXt4+6tAzGIAbRHbOuwh672lFTErqor/ayEkWAE7nOUeWvoK1uUmsRLf5NgHwDCv98rwk8p0Y9iBswpEoEmr7X91SOfGxMu+nG4tZ6yAAAAA="
   },
   {
    "file": "sirio_03.jpg",
    "src": "/media/projects/sirio/sirio-03-1600.avif",
    "srcset": "/media/projects/sirio/sirio-03-800.avif 800w, /media/projects/sirio/sirio-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUGbaCTcXC+qw7wS/rp1xTpw4AP7k0q6S9YHW0be4A4TbkNFhsL02NWxnmw0HWkvewD0iWmTuKH2OylGX4zbPy1uKnp1jjbSeAr9XsaRb3uZaZH3ovzxgbVw7XFyjwZTCumaOSIW4X0jkAAAA"
   },
   {
    "file": "sirio_04.jpg",
    "src": "/media/projects/sirio/sirio-04-1600.avif",
    "srcset": "/media/projects/sirio/sirio-04-800.avif 800w, /media/projects/sirio/sirio-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBABBgTgAM8rsrMpNSlUoHmhwQAA/u/ERBMJmApj3TbwvrsOMfPJ0Cs4thaQrhkZXDSfPzb6ERxNnqMf5OhA0Oic8eUKk/Xb8CCoOYblZoK1g3Va6WfeXEXDV4o2NgeAwOUS/O91wiEAmzA5feXT+EcqwgsBkDaw81B31GPC4AAA"
   },
   {
    "file": "sirio_06.jpg",
    "src": "/media/projects/sirio/sirio-06-1600.avif",
    "srcset": "/media/projects/sirio/sirio-06-800.avif 800w, /media/projects/sirio/sirio-06-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQBACdASoYAA4APu1kqU4ppaOiMAgBMB2JYgC7ACILmYkCXHHN+n0Y/3gbfeAA/vKkOfHRb5FLSP1ONc9FzmxLVH7A0F+JUt5NW1h7uSnvgAHSWbABiClvOlI8F+0rZ+oRLztvEp4Ugze2ycB8LOq+Fc7DpRTzdGtfGiURw3P1o3BCQZCp2AR/x3hS9MJOqSMp8gAA"
   }
  ]
 },
 "villa-relojero": {
  "hero": {
   "file": "carril_del_relojero_03.jpg",
   "src": "/media/projects/villa-relojero/carril-del-relojero-03-1600.avif",
   "srcset": "/media/projects/villa-relojero/carril-del-relojero-03-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-03-1600.avif 1600w, /media/projects/villa-relojero/carril-del-relojero-03-1920.avif 1920w",
   "width": 1920,
   "height": 1080,
   "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACxC8ADMpTFV0SyZJWtr8VZAAD+7H5BNdUMUAjjOCH0ZWE8S/kLKHvL5crDF8NI+NbeygAO6RjgbJ0IWEiSLQY3yWEBx2F8la9yvvjnWgLzWwYD53i2WMMyEYoQjEYVt2VTUpM3AXlSxITF0pctM+zhkCxI64oR393gPR3i6Fb6PVDH2hb6/DzTjCtCuAA=",
   "jpg": "/media/projects/villa-relojero/carril-del-relojero-03-og.jpg"
  },
  "pause": {
   "file": "carril_del_relojero_05.jpg",
   "src": "/media/projects/villa-relojero/carril-del-relojero-05-1600.avif",
   "srcset": "/media/projects/villa-relojero/carril-del-relojero-05-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-05-1600.avif 1600w, /media/projects/villa-relojero/carril-del-relojero-05-2560.avif 2560w",
   "width": 2821,
   "height": 1080,
   "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBACdASoYAAkAPu1mqk4ppaOiMAgBMB2JQBdmUABoYySzOuVpvKmpVIAA/ujQ6Lc5Frz5q1nJXD5M+jEwPbuWnplT+UICTOPhXg288+KbxkLPHQfKLBspeE29+RUR8yS/mVWwogo+XYXqmO+LAny18ilAAA=="
  },
  "gallery": [
   {
    "file": "carril_del_relojero_01.jpg",
    "src": "/media/projects/villa-relojero/carril-del-relojero-01-1497.avif",
    "srcset": "/media/projects/villa-relojero/carril-del-relojero-01-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-01-1497.avif 1497w",
    "width": 1497,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBQCdASoYABEAPu1kq0+ppSOiMBgIATAdiWQAnTKAAcWSvtid+xlJ8ynSlVQq7Q8jAADN3PSzdCn4MyPatH/ox1rpK2wBHy4MwLv8D9Ju09UeKLsK9eiUWJLiBi4tnJ72EIk1IVo9Vo+y3JxkVhbER0kaVwYsUz3zezKIFH2fHecApfUMeUgiSFyV2Zaz2RlUhIgNswml2rvAAAA="
   },
   {
    "file": "carril_del_relojero_02.jpg",
    "src": "/media/projects/villa-relojero/carril-del-relojero-02-1600.avif",
    "srcset": "/media/projects/villa-relojero/carril-del-relojero-02-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-02-1600.avif 1600w",
    "width": 1920,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUABsCWGYHB66dEwReWH/AAD+WV0U5z5MPQKs0Kcc5U4zhccP29RNctuuZfanPnJqSwtKrRqBWzeKi2AW8CcA5YVDookmpCgwNlSikZj/V2OYvfVtn43dmrR9p0O4y+tR7P+AxWPiEm4/OVn0TWpWSDe9Ca+h5Pu0oHv3YK+lQ/TXogQyjmHEAA=="
   },
   {
    "file": "carril_del_relojero_04.jpg",
    "src": "/media/projects/villa-relojero/carril-del-relojero-04-1600.avif",
    "srcset": "/media/projects/villa-relojero/carril-del-relojero-04-800.avif 800w, /media/projects/villa-relojero/carril-del-relojero-04-1600.avif 1600w",
    "width": 1920,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JagCdIMgCdpD5HZwCB978RQC+qAD+6QPpE03xBQZWT95zbfogWipCLh6BuyN7sNgMS9ucBc70Zdp7BkIkoMUKFCjvt+wsdCg4WeyCkqBEcewdgOe/NzY+6q0wZ3fJ42aqdbmD1Et6/4TpEAAAAA=="
   }
  ]
 },
 "villa-ambar": {
  "hero": {
   "file": "villa_ambar_04.jpg",
   "src": "/media/projects/villa-ambar/villa-ambar-04-1600.avif",
   "srcset": "/media/projects/villa-ambar/villa-ambar-04-800.avif 800w, /media/projects/villa-ambar/villa-ambar-04-1600.avif 1600w, /media/projects/villa-ambar/villa-ambar-04-2560.avif 2560w",
   "width": 4256,
   "height": 2832,
   "lqip": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAAAwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JaAC7ACHALJ7cB5/lXU9qg4AA/urWoJfZr3vIpbguanC4/ZT4gmklmcMbdZxBK/wdhYqNO9/WMzZLwc6dfo6iR9jGJ4iJc9j5Bh+eMhat5vLV5pflvM0xD1s7X1I/IEJofsapFKuhPSmvlzzuE4y/7g9cLnnHKx37zo6HUI6CPeHe0yynDeCBeGMaH80liKr0JSWrFNuYmT4AAAA=",
   "jpg": "/media/projects/villa-ambar/villa-ambar-04-og.jpg"
  },
  "pause": {
   "file": "villa_ambar_03.jpg",
   "src": "/media/projects/villa-ambar/villa-ambar-03-1600.avif",
   "srcset": "/media/projects/villa-ambar/villa-ambar-03-800.avif 800w, /media/projects/villa-ambar/villa-ambar-03-1600.avif 1600w, /media/projects/villa-ambar/villa-ambar-03-2560.avif 2560w",
   "width": 4256,
   "height": 2322,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABwBACdASoYAA0APu1kqU2ppaOiMAgBMB2JZgCdIMggvhI9VxBV7Njsll/jwAD8j6Orp0j+E76EURnnt1NVAH01LqbWPE6NIx13t9nP0PdeK3pUGrXcEXg8FmvfWUUH3Fz1MiOl0NoIIRxjM2PsgWs2ob1RXx3HlIv4q5EQVDTewBdhGlHVtjLKSAZmG6ljQqvdHti6/oo3TT2eVALy1kFaAAA="
  },
  "gallery": [
   {
    "file": "villa_ambar_01.jpg",
    "src": "/media/projects/villa-ambar/villa-ambar-01-1600.avif",
    "srcset": "/media/projects/villa-ambar/villa-ambar-01-800.avif 800w, /media/projects/villa-ambar/villa-ambar-01-1600.avif 1600w",
    "width": 4256,
    "height": 2832,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZgC7ACP7FvOkrUE3XLoUAM3qspr58QsZnY/CvyaeHgNvcfJlJkQXJfGfFpJG8eawynCyv6a/TkLasU9+Ig5FLv8NRN06Qa+rl4tc5Gu/nLK3FjF5vcTIgrdDZkktiHuUjHnWXZNOes2jfEWo0N35Bu1eo4PUgNZa9dVXp/MsAAAA"
   },
   {
    "file": "villa_ambar_02.jpg",
    "src": "/media/projects/villa-ambar/villa-ambar-02-1600.avif",
    "srcset": "/media/projects/villa-ambar/villa-ambar-02-800.avif 800w, /media/projects/villa-ambar/villa-ambar-02-1600.avif 1600w",
    "width": 4256,
    "height": 2832,
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOkERhdqafxhYmPpNifXv9AAP7qeF0QBg7N4BRoVGXJy/tcaOI+9zoDeHeLG1bKP7I7O7RSa6Oide/L3dkrwJJwSOmPp1zxCFRWiyvrh9Fsh+FqreHvQhNTzUIK97eavmqrWdn9burGmiYuK4Fy4ehYjTdc0YnqQnj7N6cAMAArQDs/uL5cV5+4fvzHnW3W/6EU44AAAA=="
   },
   {
    "file": "villa_ambar_05.jpg",
    "src": "/media/projects/villa-ambar/villa-ambar-05-1600.avif",
    "srcset": "/media/projects/villa-ambar/villa-ambar-05-800.avif 800w, /media/projects/villa-ambar/villa-ambar-05-1600.avif 1600w",
    "width": 3978,
    "height": 2705,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMrnGqJ0AEVw7EpQAD+q37cuPSan8zKLFCPgk8TzGLTEfrbGXufQ4HBcziGi/T30qr1DmV+brcs0mk0CQ8rnhY7kHlUsJJ2EwkNHfVIDs5vlmkrZ5ek4Iy83iJCSc6VN5IHc9rv3Sk7PBf2NFkArRlo2hxAAA=="
   }
  ]
 },
 "villa-pino": {
  "hero": {
   "file": "calle_pino_01.jpg",
   "src": "/media/projects/villa-pino/calle-pino-01-1600.avif",
   "srcset": "/media/projects/villa-pino/calle-pino-01-800.avif 800w, /media/projects/villa-pino/calle-pino-01-1600.avif 1600w, /media/projects/villa-pino/calle-pino-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoMpJn/Ad2RXnr38jdeCKcgA/onIfElDKLSlNR+aQHD5hHijM8soX9p221zbo2n3vpEVbGlS8IyKKsrbp8BFf8qlIzkVa8AoxHpCuv5LAZdV81Sggivmrs0eyNykjv6aHQpz/lAn0wXj7v1AUpqYSDbWUYnhbSXSRLrIYkUIcs3CSYnSDQAAAA==",
   "jpg": "/media/projects/villa-pino/calle-pino-01-og.jpg"
  },
  "pause": {
   "file": "calle_pino_02.jpg",
   "src": "/media/projects/villa-pino/calle-pino-02-1600.avif",
   "srcset": "/media/projects/villa-pino/calle-pino-02-800.avif 800w, /media/projects/villa-pino/calle-pino-02-1600.avif 1600w, /media/projects/villa-pino/calle-pino-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JZACdAYwSuW4g/wcH9KcMxE7okADeXyUHCD/UW7v4l4D1zoQyaIMhvThtiACE9H6y19k4oxUq7od0gjVYqiMN2Q3cCqgToaHc552akconS1fc/ODlPDUP3XntoyD74kVHdnXAmNc5FSLm6fctERdX/mVV9JcXVB740fH1Og24mO4BH8WUkAAA"
  },
  "gallery": [
   {
    "file": "calle_pino_03.jpg",
    "src": "/media/projects/villa-pino/calle-pino-03-1600.avif",
    "srcset": "/media/projects/villa-pino/calle-pino-03-800.avif 800w, /media/projects/villa-pino/calle-pino-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCsH8AgqQ2dpK5yj3h/+C0IAAD+hBw85DYQxFO5Y8MCgW7AWNgVP8iVn4PMEfIrLY/fprragNJGr9ldWYXObVpfw5fWXJVtyggRlSkOuc05buT4848Fu/fmidy9EE0v51P/l9jEkI98jYsAg8JFvqWzkCaGB5LilSUPQ3bWHx89Abqeql+Z0BVMnHO9+bUUDsfyCfGgSt+vVrPcBrfIa5IFcAAA"
   },
   {
    "file": "calle_pino_04.jpg",
    "src": "/media/projects/villa-pino/calle-pino-04-1600.avif",
    "srcset": "/media/projects/villa-pino/calle-pino-04-800.avif 800w, /media/projects/villa-pino/calle-pino-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACdMoGv/gNaXgHxqGs9F5AA/maqDRzmptMn0kwTpsQoIup1fCrd6O055/VVFHgu0aQ9XoFkKFVPD6rYZJlMNn/SvE2BD7+NXpSsD6YvwOJdBpMpFD0rxQBevssivIL/Nk9cGTOiGwL4QMfc5w3r+zQTRzXtfHy8pOegZv+kfXD9bdv8Kh8uv6vQvmLYaawHWyVwAAA="
   }
  ]
 },
 "atalaya": {
  "hero": {
   "file": "atalaya_01.jpg",
   "src": "/media/projects/atalaya/atalaya-01-1600.avif",
   "srcset": "/media/projects/atalaya/atalaya-01-800.avif 800w, /media/projects/atalaya/atalaya-01-1600.avif 1600w, /media/projects/atalaya/atalaya-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdMoMljEFAelf8OZ4XbnFlu4KAAP7VxDF8mx/N27+/u7Qs5iJakCbpFhh6OMqks5gX0te4EmPXEfvSFW6307BmH5CLBw1AO9MGFLkY6rvg8HCxTxmnBjn6BVP0JPjc2nvlZ/+PovPXZ5NIEwX+POv3tD3DTAZNc5qujL8NkZ1ZNQWiXpgqf79Bh/9Gjdsg9uZ6NQsXTzNuvX5gAA==",
   "jpg": "/media/projects/atalaya/atalaya-01-og.jpg"
  },
  "pause": {
   "file": "atalaya_03.jpg",
   "src": "/media/projects/atalaya/atalaya-03-1600.avif",
   "srcset": "/media/projects/atalaya/atalaya-03-800.avif 800w, /media/projects/atalaya/atalaya-03-1600.avif 1600w, /media/projects/atalaya/atalaya-03-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBACdASoYAA4APu1iqk2ppaQiMAgBMB2JYgCo9YyA31KKWVdckqjZioGAAP7nYQ/gsErAw7Se3QudN55H+aWh7rsM9xNGSEyCg96+lOsyZmmiLeoky+9/o5jVO7BMz1asSnW8K7GcvXNzJwa6s18XpeT+eTL9Xqos0NH47OwvtUEru/6F2XriZKlumVP2v2Oqi3Y48xR6TwaEgGb2NwECAAA="
  },
  "gallery": [
   {
    "file": "atalaya_02.jpg",
    "src": "/media/projects/atalaya/atalaya-02-1600.avif",
    "srcset": "/media/projects/atalaya/atalaya-02-800.avif 800w, /media/projects/atalaya/atalaya-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgC+SYx24PkNtBxSpeb1ZLQIMAD+52ETEss+Cr/DH4SaZ2eMP+0nyGWdQEG9qgv6mYj2sb4OYqH+nMpxf8OCHIWObswvzJmK1t0SjDhuwHLOOVpCyH9x4JikkvP+o95JjHXmHjmWkdlRoEbmkA8GYtz41Cph7fwJ05ViQZwOiVIAAAA="
   },
   {
    "file": "atalaya_04.jpg",
    "src": "/media/projects/atalaya/atalaya-04-1600.avif",
    "srcset": "/media/projects/atalaya/atalaya-04-800.avif 800w, /media/projects/atalaya/atalaya-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwDCgdwLfrVJxFdVnI3pEdLIr/BAAP7CQL4W4ZQyzlekfZo9fRuleMXNr78zX6V4pbl6r5gyPe1XL+pNIw1IhTsRe3iTpfn1qCxLWglVFweUDaJRbZLKVoonBithWr596yqJwfAfUfqjt4ou6BjNrSyA/eTi3kQ0+dviLe15khxH2ylscbdeodT+z45NHidivaAOv0QAAA=="
   }
  ]
 },
 "hotel-boutique": {
  "hero": {
   "file": "hotel_boutique_02.jpg",
   "src": "/media/projects/hotel-boutique/hotel-boutique-02-1600.avif",
   "srcset": "/media/projects/hotel-boutique/hotel-boutique-02-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-02-1600.avif 1600w, /media/projects/hotel-boutique/hotel-boutique-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JQBOgAagbLO3KDM07AAD+np9rq2PKHrrPpmMlyxOrutoxM2mQCGlwsyGNq0EYY+Kt1P+1hbYDMuSmr0XGBs6PyrEcyfmHEZgKKqbxIjEXGGo0waD6zgcLF/XCX9kJ0qAwfqpf6S5HVaYA",
   "jpg": "/media/projects/hotel-boutique/hotel-boutique-02-og.jpg"
  },
  "pause": {
   "file": "hotel_boutique_01.jpg",
   "src": "/media/projects/hotel-boutique/hotel-boutique-01-1600.avif",
   "srcset": "/media/projects/hotel-boutique/hotel-boutique-01-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-01-1600.avif 1600w, /media/projects/hotel-boutique/hotel-boutique-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOkDgBeksLahavPLS4jgAD8reZUK5C3kZ+NWGyo7Qt7n3k89m7Kpff7r7YkEQZHomAAFpO48MQ09JXP4Te6urO9vC1qOmxZtM9rKrerF+xqmQ6N5nGjlwqY8Ug3iB9JhhjA8wAAAA=="
  },
  "gallery": [
   {
    "file": "hotel_boutique_03.jpg",
    "src": "/media/projects/hotel-boutique/hotel-boutique-03-1600.avif",
    "srcset": "/media/projects/hotel-boutique/hotel-boutique-03-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCsAB7DiuE5J2LPS+P1gAD45QYfe4XXZXlozcUbxZM5Sz4oZzEt9RvgAUMzAle0Zb4/UKV7wWcjfLcyzOZVqIymWL1BmPHSMwvxu2GpTJzUBITThHeDlZcXjxoYwwFcAl6akQv3K0SY7vaXjPqgPKEMrwu9fwrHAAAA"
   },
   {
    "file": "hotel_boutique_04.jpg",
    "src": "/media/projects/hotel-boutique/hotel-boutique-04-1600.avif",
    "srcset": "/media/projects/hotel-boutique/hotel-boutique-04-800.avif 800w, /media/projects/hotel-boutique/hotel-boutique-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCw7B5eDwq4xy5woAD+ZspXNwNkfREhNuhiFQXW+OuAfOck2MxfuLiqR4uaAJBZ19Sr9zMM8bzlfv9puAi/TWeo+wtVCIy6zLYk9hXtS+Ut4bUDRZcYM3m8DAbDZxVI6KG33ZNQGBdMiFE9p/YGcFrexpeYAAA="
   }
  ]
 },
 "huerta-belon": {
  "hero": {
   "file": "huerta_belon_34_01.jpg",
   "src": "/media/projects/huerta-belon/huerta-belon-34-01-1600.avif",
   "srcset": "/media/projects/huerta-belon/huerta-belon-34-01-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-01-1600.avif 1600w, /media/projects/huerta-belon/huerta-belon-34-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JaACdIExC4uU87LMeBQ0ssuYuIAD6hADGO4j38zhldygtAz3z0UwjmQf6vlsmD46x86oYqspQTcun0u10pK4tOXAmPo7SAjs3qa4shBpg5de2i+Cw33/XNvevs8P1pGkHXcleVmvstZREeaP77sJhwdaMgXO0bCkXtmIt5WfGS98p1y77XAAA",
   "jpg": "/media/projects/huerta-belon/huerta-belon-34-01-og.jpg"
  },
  "pause": {
   "file": "huerta_belon_34_03.jpg",
   "src": "/media/projects/huerta-belon/huerta-belon-34-03-1600.avif",
   "srcset": "/media/projects/huerta-belon/huerta-belon-34-03-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-03-1600.avif 1600w, /media/projects/huerta-belon/huerta-belon-34-03-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADQBACdASoYAA4APu1kqU2ppaQiMAgBMB2JbACdMoR3Ff/gNdBSVVEuVEZRFm/cAAD+370S3sEGoQuVUZUu3fqAHC9gNzGxmBsyIVFdvvaWv8L0vlnGGyOSf3Ky6OJrFq/dEs0w8gLxqUwCBUO8yejMAOcGhleGoG4K2zU6WahytuH/Lv+M4MbmgJtoxstCHdNKKKWPkvPNaDTCjHvY4A2v6TM93ndIB6K6mAAA"
  },
  "gallery": [
   {
    "file": "huerta_belon_34_02.jpg",
    "src": "/media/projects/huerta-belon/huerta-belon-34-02-1600.avif",
    "srcset": "/media/projects/huerta-belon/huerta-belon-34-02-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABwBACdASoYAA4APu1kqU4ppaOiMAgBMB2JbACdH8GJ/gKMa3l1OidRDtSkmADdigUdQ+zB506stAmnnbrwuO6bCO7fiIflm52l3vyS2Dh3hMkPyb5ldwmEP9/ZZf4OZZabAzrtsP5b41GrlT00UfeH6pqRAM1XJ83jOYzXbLH3oKGaDiXpmAJE4zPNV6DzFFygwME++GPgC8MN3qMguwbn7AHJsMk8es0Vf6/tRVl0g/vrEQAAAA=="
   },
   {
    "file": "huerta_belon_34_04.jpg",
    "src": "/media/projects/huerta-belon/huerta-belon-34-04-1600.avif",
    "srcset": "/media/projects/huerta-belon/huerta-belon-34-04-800.avif 800w, /media/projects/huerta-belon/huerta-belon-34-04-1600.avif 1600w",
    "width": 5472,
    "height": 3078,
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAAAQBACdASoYAA0APu1iqU2ppaQiMAgBMB2JZACdAYxiuwN2P4KWizMqCADdB6mMSqZGNOLfuRLxycFiKv1fGlRi2fFrGr9VffRawT22c3+NGSQHIwtlzJOnzwgAf6Msj5rqBYilRIYHoi5xOh8JCb/99qdbUi0OaaPNjxEyLWSHgYSZ6uEI0vBCE0S6yrk5aph/2TRP1ueMo1qU4AcR9nl1Q1ql7nwRQ9SnHTzof6AAAAAA"
   }
  ]
 },
 "castilla": {
  "hero": {
   "file": "castilla_01.jpg",
   "src": "/media/projects/castilla/castilla-01-1600.avif",
   "srcset": "/media/projects/castilla/castilla-01-800.avif 800w, /media/projects/castilla/castilla-01-1600.avif 1600w, /media/projects/castilla/castilla-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYgCdAYy8wPypE1CkGrdlGAD878NkSAqG4sv2jIzJK92YU4N2/+ICo/KYrFknL+L0Dt3u4RpTDUlKC0byYTUYMc+30dNs0jJjRHW2SXnz1jMhufIve8suU1yBEf9eDJcq07rf/HJSTZyayf2VToFxVyeSlvRwC+VeHKYYma5MjT9sgsAAAA==",
   "jpg": "/media/projects/castilla/castilla-01-og.jpg"
  },
  "pause": {
   "file": "castilla_04.jpg",
   "src": "/media/projects/castilla/castilla-04-1600.avif",
   "srcset": "/media/projects/castilla/castilla-04-800.avif 800w, /media/projects/castilla/castilla-04-1600.avif 1600w, /media/projects/castilla/castilla-04-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAwBACdASoYAA4APu1iqk2ppaQiMAgBMB2JZQDE2Yx2xN1np7sUGEME64AA4n66mEy7KuDrpqBauIloaf3nqEWyWoKQ+3f8/yWXECk2wF2OysZIw2QPnyWwbI6TSXYSDbXx+QcKveBrQNwzW5lHJjyeYZE5NKXc/6Z4UJ2gR//2s7/vNchCRB7xKPvMYNyXJ+lQKZyAAAA="
  },
  "gallery": [
   {
    "file": "castilla_02.jpg",
    "src": "/media/projects/castilla/castilla-02-1600.avif",
    "srcset": "/media/projects/castilla/castilla-02-800.avif 800w, /media/projects/castilla/castilla-02-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JaAC7AYvWuxFcecdPNKbjst7+EAD8+6HALky+EbSANQGLRizYmd9q+4Qpi9l9DxEiyYEp5a7P3nHvNK5Wa3zZlVhARhee8lvhBzrJG/vhJDblCFOFukFJxR9p6KCM7B3Ai3s/4zet54qY3LMFnbRM/WCadYw4QKDIQXjILELcdDDOJOIZpM86Ety/7ESg1pEqPbwMJyF1KPaVbS5UOwAA"
   },
   {
    "file": "castilla_03.jpg",
    "src": "/media/projects/castilla/castilla-03-1600.avif",
    "srcset": "/media/projects/castilla/castilla-03-800.avif 800w, /media/projects/castilla/castilla-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAADQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUDX/xbIq7mOhPYgFBqHyMGV7oAD9d+vkXLm7wcs4ELhGEyPhV46G0UdECVAPCR/ZQrlCtvmXveWiiMLz2Vvt6AnQ8dZzCJTdaRhpzfK+00xCJIt85piDjwrh9rbseddZ0EtlcyzXp/gr291fOsaZ2MjnfvHu39qCWQ9MZ5xx382hQNGxQPiidtttIV5M4jS75yBdkrgA"
   }
  ]
 },
 "villa-del-golf": {
  "hero": {
   "file": "parcelas_del_golf_02.jpg",
   "src": "/media/projects/villa-del-golf/parcelas-del-golf-02-1600.avif",
   "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-02-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-02-1600.avif 1600w, /media/projects/villa-del-golf/parcelas-del-golf-02-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JQBafP/wFEDuEF3HctdaYqAAA4cLEYTsS/k0U0NVevZSuwFgzapDBSN7uXsQMPN7DqaoWuGxJ0NBH2ckMWQllH5Kr+mzxedQD1e9AHK77ckYaggfDjk8hClL8awgY578Cjkp28npHOwGy+6gOLjHqv0wssz/exBFcAAAA",
   "jpg": "/media/projects/villa-del-golf/parcelas-del-golf-02-og.jpg"
  },
  "pause": {
   "file": "parcelas_del_golf_01.jpg",
   "src": "/media/projects/villa-del-golf/parcelas-del-golf-01-1600.avif",
   "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-01-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-01-1600.avif 1600w, /media/projects/villa-del-golf/parcelas-del-golf-01-2560.avif 2560w",
   "width": 3840,
   "height": 2160,
   "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JagCdMoADgkZOmb4aCuky+1Ay4ADyiPH/a+lNkWvsZ/AGcJeDb6yMfwhl/o10vLXQTZA5LzqfZai+2qaJnDPWtCUYvz/AhL8H7hGkfDn7T5idqcU3PT5WtgJRocV0QIEpcyQKy6V1xZBbS3SmmZdUwcbAAA=="
  },
  "gallery": [
   {
    "file": "parcelas_del_golf_03.jpg",
    "src": "/media/projects/villa-del-golf/parcelas-del-golf-03-1600.avif",
    "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-03-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-03-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdAB3YD7ZLxfdzt2IAAMtLeHwu/7bm+n2xsCgthiAQs54US39Z/dKnGgEMPUGBnXepMyyf87if42rG6JN9MhrmFkIkX733gRGWoTjsfBCfcl6e1NsOGh6nY3Zt/8rAhMnAfJM6YfjUV0G8ojMD7HZheeNX1boTVUTGaNqfZWSR7wAAAA=="
   },
   {
    "file": "parcelas_del_golf_04.jpg",
    "src": "/media/projects/villa-del-golf/parcelas-del-golf-04-1600.avif",
    "srcset": "/media/projects/villa-del-golf/parcelas-del-golf-04-800.avif 800w, /media/projects/villa-del-golf/parcelas-del-golf-04-1600.avif 1600w",
    "width": 3840,
    "height": 2160,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoYAA4APu1iqk2ppaQiMAgBMB2JagCdMoR3AdCU6FcGGizaGppRYgD2Puov8qcGyRkUcnoLRxBSBIL3QZgvzmnIOAxW8wmglcDifIDfVZpFiNURsryBkEhI6cw6WXtXsj/4yLb8JMOP//9SvwR2rAe/Hyi13KpAUrhrS/ifgCDfTHDrOqMAsUxNBBM18wdxA+1S32bf2eTw0gAA"
   }
  ]
 }
}
