#!/usr/bin/env python3
"""Physical models on the studio page: reads scripts/media/models.json and the originals in
public/media/studio/maquetas (git-ignored, never linked), writes AVIF derivatives to public/media/studio/models/<id>/
and the manifest app/data/studio-models.generated.ts.

Same recipe as build_projects.py: never upscales, incremental (--force rebuilds), content hashes in filenames.
--src DIR reads the originals from another folder. Uses the vips CLI when present, otherwise Pillow 11.2+ (built-in AVIF).
"""
import argparse, base64, hashlib, io, json, re, shutil, subprocess, unicodedata
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

APP = Path(__file__).resolve().parents[2]
OUT = APP / 'public' / 'media' / 'studio' / 'models'
CACHE = APP / '.cache' / 'lqip'
MANIFEST = APP / 'app' / 'data' / 'studio-models.generated.ts'
MODELS = json.loads((APP / 'scripts' / 'media' / 'models.json').read_text(encoding='utf-8'))['models']
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--force', action='store_true')
parser.add_argument('--src', type=Path, default=APP / 'public' / 'media' / 'studio' / 'maquetas')
ARGS = parser.parse_args()
SRC, FORCE = ARGS.src, ARGS.force
ENGINE = 'vips' if shutil.which('vips') else 'pillow'
WIDTHS = [800, 1600, 2560]  # stage (about 60vw on desktop) and the full-screen viewer
THUMB = 400                 # thumbnails strip
RECIPE = b'v1:avif-Q52-effort4-strip:srgb:webp-Q40' + (b':pillow' if ENGINE == 'pillow' else b'')
SAVE = {
    'avif': ('Q=52,effort=4,strip', {'quality': 52, 'speed': 5}),
    'lqip': ('Q=40,strip', {'quality': 40}),
}


def slugify(stem: str) -> str:
    s = unicodedata.normalize('NFKD', stem).encode('ascii', 'ignore').decode().lower()
    return re.sub(r'[^a-z0-9]+', '-', s).strip('-')


def pillow(path: Path):
    from PIL import Image, ImageCms, ImageOps
    im = ImageOps.exif_transpose(Image.open(path))
    if icc := im.info.get('icc_profile'):
        im = ImageCms.profileToProfile(im, ImageCms.ImageCmsProfile(io.BytesIO(icc)), ImageCms.createProfile('sRGB'), outputMode='RGB')
    im = im.convert('RGB')
    im.info.clear()
    return im


def size(path: Path) -> tuple[int, int]:
    if ENGINE == 'pillow':
        return pillow(path).size
    run = lambda f: int(subprocess.run(['vipsheader', '-f', f, str(path)], check=True, capture_output=True, text=True).stdout)
    return run('width'), run('height')


def derive(src: Path, dest: Path, width: int, kind: str) -> None:
    if dest.exists() and not FORCE:
        return
    opts, save = SAVE[kind]
    if ENGINE == 'vips':
        subprocess.run(['vips', 'thumbnail', str(src), f'{dest}[{opts}]', str(width), '--export-profile', 'srgb'], check=True, capture_output=True)
        return
    from PIL import Image
    im = pillow(src)
    im.resize((width, round(im.height * width / im.width)), Image.LANCZOS).save(dest, **save)


def process(model_id: str, file: str) -> dict:
    src = SRC / file
    if not src.exists():
        raise SystemExit(f'{model_id}: {file!r} not found in {SRC}')
    w, h = size(src)
    name = f'{slugify(Path(file).stem)}-{hashlib.sha256(src.read_bytes() + RECIPE).hexdigest()[:12]}'
    folder = OUT / model_id
    folder.mkdir(parents=True, exist_ok=True)
    variants = []
    for width in sorted({min(x, w) for x in WIDTHS}):
        dest = folder / f'{name}-{width}.avif'
        derive(src, dest, width, 'avif')
        variants.append((width, f'/media/studio/models/{model_id}/{dest.name}'))
    thumb = folder / f'{name}-{THUMB}.avif'
    derive(src, thumb, min(THUMB, w), 'avif')
    CACHE.mkdir(parents=True, exist_ok=True)
    lqip = CACHE / f'model-{model_id}-{name}.webp'
    derive(src, lqip, 24, 'lqip')
    return {
        'file': file, 'src': next((p for wd, p in variants if wd >= 1600), variants[-1][1]),
        'srcset': ', '.join(f'{p} {wd}w' for wd, p in variants), 'width': w, 'height': h,
        'lqip': 'data:image/webp;base64,' + base64.b64encode(lqip.read_bytes()).decode(),
        'thumb': f'/media/studio/models/{model_id}/{thumb.name}'
    }


def main() -> None:
    print(f'Models: {len(MODELS)} from {SRC} ({ENGINE})')
    with ThreadPoolExecutor(max_workers=4) as pool:
        jobs = [(m['id'], [pool.submit(process, m['id'], f) for f in m['files']]) for m in MODELS]
        media = [{'id': model_id, 'images': [j.result() for j in images]} for model_id, images in jobs]
    keep = set()
    for image in (i for m in media for i in m['images']):
        keep.add(Path(image['thumb']).name)
        keep.update(Path(entry.split(' ')[0]).name for entry in image['srcset'].split(', '))
    for stale in OUT.glob('*/*.avif'):  # derivatives of replaced or removed photographs
        if stale.name not in keep:
            stale.unlink()
    MANIFEST.write_text(
        '// Generated by scripts/media/build_models.py from scripts/media/models.json. Do not edit.\n'
        "import type { ProjectImage } from './projects/types'\n"
        'export type ModelImage = ProjectImage & { thumb: string }\n'
        'export const studioModelMedia: { id: string; images: ModelImage[] }[] = '
        + json.dumps(media, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
    print(f'  {sum(len(m["images"]) for m in media)} images -> {MANIFEST.relative_to(APP)}')


if __name__ == '__main__':
    main()
