#!/usr/bin/env bash
# Replace only the Home reel from the master; keep the original outside public/.
# Run from the Nuxt root. An optional first argument selects another master MP4.
set -euo pipefail
source_video=${1:-../Graphics/VISENI/galvan-arquitectos_video_reel_40s_hero.mp4}
output_dir=public/video
stage_dir=$(mktemp -d /tmp/galvan-home-reel.XXXXXX)
trap 'rm -rf "$stage_dir"' EXIT
mkdir -p "$output_dir"

# H.264, original 25 fps, no audio, bounded bandwidth and metadata first for playback.
ffmpeg -v error -y -i "$source_video" -map 0:v:0 -an \
  -vf 'scale=1920:-2,fps=25' -c:v libx264 -preset slow -crf 30 \
  -maxrate 2400k -bufsize 4800k -pix_fmt yuv420p -movflags +faststart \
  "$stage_dir/home-reel.mp4" &
desktop_pid=$!
ffmpeg -v error -y -i "$source_video" -map 0:v:0 -an \
  -vf 'scale=720:-2,fps=25' -c:v libx264 -preset slow -crf 30 \
  -maxrate 800k -bufsize 1600k -pix_fmt yuv420p -movflags +faststart \
  "$stage_dir/home-reel-720.mp4" &
mobile_pid=$!
wait "$desktop_pid"
wait "$mobile_pid"

# Match the beginning of the replacement reel, including the reduced-motion fallback.
ffmpeg -v error -y -ss 0.04 -i "$source_video" -frames:v 1 \
  -vf 'scale=1920:-2' "$stage_dir/poster.png"
VIPS_WARNING=0 vips copy "$stage_dir/poster.png" "$stage_dir/home-reel-poster.avif[Q=50,strip]"
VIPS_WARNING=0 vips thumbnail "$stage_dir/poster.png" "$stage_dir/home-reel-720-poster.avif[Q=50,strip]" 720

for asset in home-reel.mp4 home-reel-720.mp4 home-reel-poster.avif home-reel-720-poster.avif; do
  mv "$stage_dir/$asset" "$output_dir/$asset"
done

# A content version prevents the old reel/poster surviving the 30-day media cache.
node --input-type=module <<'JS'
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, statSync } from 'node:fs'
const files = ['home-reel.mp4', 'home-reel-720.mp4', 'home-reel-poster.avif', 'home-reel-720-poster.avif']
const hash = createHash('sha256')
for (const name of files) hash.update(readFileSync(`public/video/${name}`))
const version = hash.digest('hex').slice(0, 12)
const assets = Object.fromEntries(['desktop', 'mobile', 'poster', 'mobilePoster'].map((key, i) => [key, `/video/${files[i]}?v=${version}`]))
writeFileSync('app/data/home-reel.ts', '// Generated by scripts/media/replace_home_reel.sh from the Home reel master.\nexport const homeReel = ' + JSON.stringify(assets, null, 2) + ' as const\n')
for (const name of files) console.log(`${name}: ${(statSync(`public/video/${name}`).size / 1e6).toFixed(2)} MB`)
JS
